### ISSUE TITLE
Show exercise progress over time

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1013]
Progress bars showing progress of a class for a given exercise could be made more dynamic by replaying the progress over time (from first to last submission in course for that exercise). This could be done for an individual exercise (e.g. by clicking the progress bar) or for all exercises in a series simultaneously. This could give an impression on i) when students worked on the exercises, ii) how long students linger in "not correct" state (red segment in bar), iii) order in which they work on the exercises.

![image](https://github.ugent.be/storage/user/6/files/4d749280-56b7-11e9-807e-9cf8a8f81728)

This would better reflect that the progress seen while students work on the exercises is not necessarily the same picture that is seen at the end of a course or after a deadline.

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1013) by @pdawyndt on Thu Apr 04 2019 at 08:58._

**Comment by chvp** [comment]
Also a part of #2598?
