### ISSUE TITLE
Add tips to exercises

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1045]
From Brecht Willems (brecht.willems`@ugent`.be):

> De mogelijkheid toevoegen om tips/hints toe te voegen aan de opgave, die pas weergegeven worden als de gebruiker klikt op de titel van de tip/hint. Op die manier kunnen studenten, wanneer ze daar nood aan hebben, een extra tip/hint krijgen voor die opgave

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1045) by @pdawyndt on Thu Apr 25 2019 at 18:50._

**Comment by BTWS2** [comment]
For now I use this in the exercise description.
<details>
  <summary>Tip (Click <b>here</b> to expand)</summary>
  This is a useful hint.
</details>

```
<details>
  <summary>Tip (Click <b>here</b> to expand)</summary>
  This is a useful hint.
</details>
```

**Comment by BTWS2** [comment]
This was related to https://github.com/dodona-edu/dodona/issues/5237 and is ok for me.
