### ISSUE TITLE
Allow linking to exercises in the same repo 

### ISSUE THREAD

**Issue by beardhatcode** [dodona-edu/dodona#1050]
It would be nice to be able to link to an other exercise in a repo.

I was thinking of something like this:

```markdown
Write a `goal` predicate for an  
[iterative deepning](exercise:/SearchAlgorithms/ItterDepth) 
algorithm that ...
```

This link should refer to the exercise that is at `/SearchAlgorithms/ItterDepth` as seen from the root of the current repository:

- in the scope current course if is in one of the series
- just the exercise page if it is not in the course

---

I don't know what should happen with 

- `[iterative deepning](exercise:/SearchAlgorithms/ItterDepth/meta) `
- `[iterative deepning](exercise:SearchAlgorithms/ItterDepth) `
- `[iterative deepning](exercise:../ItterDepth) `
- `[iterative deepning](exercise:/NonExisting/Path) `

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1050) by @beardhatcode on Tue Apr 30 2019 at 13:42._

**Comment by JoFAM** [comment]
@bmesuere Any update on this? I could really use this to be honest...

**Comment by bmesuere** [comment]
@JoFAM We have no way to implement this without a significant refactor of how Dodona works, so don't expect this any time soon.

**Comment by jorg-vr** [comment]
For now not feasible
