### ISSUE TITLE
export submitted solutions in PDF format

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1105]
Suggestion/question from Annick: export submitted solutions in PDF format in bulk. All solutions for a single exercise (for all students in class) or all solutions per student for a single series (as is done by Indianio). In extenso, we could also add the description in combination with the solutions, so that users can export their solutions/descriptions as they come to class.

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1105) by @pdawyndt on Wed Jun 19 2019 at 18:06._

**Comment by bmesuere** [comment]
Part of #1107
