### ISSUE TITLE
consistent object-level menu icons

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1122]
Each course has its own set of menu icons that link to particular information on that course

![image](https://github.ugent.be/storage/user/6/files/7f0c7500-a235-11e9-8c58-d3a0c7cca906)

Would be more consistent if we give other object the same kind of menu structure for object-level information

- users
  - courses: list of courses of the user
  - exercises: list of exercises the users has been working on across all courses (with status for each of the exericses)
  - submissions: list of submissions of the user
  - statistics: learning analytics of the user
  - edit: update the user information
- exercises
   - courses: list of courses that use the exercise
   - users: list of users that have submitted solutions for the exercise (across all courses)
   - submissions: list of submissions of the exericse
   - statistics: learning analytics of the exercise
   - edit: update the exercise information
- institutions
  - courses: list of courses linked to the institution
  - users: list of users from the institution
  - submissions: submissions of users from the institution
  - statistics: learning analytics of the institution
  - edit: update the institution information

_[Original issue](https://github.ugent.be/dodona/dodona/issues/1122) by @pdawyndt on Tue Jul 09 2019 at 10:43._

**Comment by bmesuere** [comment]
If they are relevant pages, we will, of course, use the same icons, but I'm hesitant to add icons to pages just because we can. For example, listing the courses which use an exercise can be a useful page, but this is not something you want in the top navigation.
