### ISSUE TITLE
ill-formatted comparison of expected and generated return value

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1248]
There are some issues with the feedback table for [this submission](https://dodona.ugent.be/nl/submissions/3676762/) (Python). It's about the function `front_view` that returns a multiline string.

In the unified view, the single-testcase that fails is not properly formatted.

![image](https://user-images.githubusercontent.com/5736113/64273109-f3ffe080-cf40-11e9-9b92-1a85a1bb48c8.png)

In the side-by-side view, the single-testcase there no specific highlighting that gives a visual clue about what's wrong (except for the fact that there's an issue with the last line).

![image](https://user-images.githubusercontent.com/5736113/64273237-2f9aaa80-cf41-11e9-8948-14cfdb056c42.png)

Since the Python judge has special treatment of multiline strings (representing them as a multiline string, rather than as a string with explicit `\n` characters in to), the issue might be caused at various places.

**Comment by pdawyndt** [comment]
The mistake in the students' code is that all whitespace is stripped from the last line, instead of only the final newline that was initially added (the string should not end in a newline), which also removes the spaces at the end (because the last apartment has height zero). So I would at least expect that Dodona highlights the extra spaces that are present in the expected return value in a darker green color, to flag that these are missing from the generated return value.

No idea why the unified view goes astray.

**Comment by charvp** [comment]
Pretty printed JSON for the test looks like this:
```json
{
  "accepted": false,
  "data": {
    "statements": "front_view([3, 1, 0, 6, 0], apartment='[', width=4, distance=3)\n"
  },
  "description": {
    "description": "<span class=\"code\">front_view([3, 1, 0, 6, 0], apartment=&#x27;[&#x27;, width=4, distance=3)</span>",
    "format": "html"
  },
  "maximal_score": 1,
  "runtime_metrics": {
    "wall_time": 7.904693484306335e-05
  },
  "score": 0,
  "status": "wrong answer",
  "tests": [
    {
      "accepted": false,
      "data": {
        "channel": "return",
        "diff": [
          [
            1,
            1,
            "                     [[[[       ",
            "                     [[[[       ",
            true
          ],
          [
            2,
            2,
            "                     [[[[       ",
            "                     [[[[       ",
            true
          ],
          [
            3,
            3,
            "                     [[[[       ",
            "                     [[[[       ",
            true
          ],
          [
            4,
            4,
            "[[[[                 [[[[       ",
            "[[[[                 [[[[       ",
            true
          ],
          [
            5,
            5,
            "[[[[                 [[[[       ",
            "[[[[                 [[[[       ",
            true
          ],
          [
            6,
            6,
            "[[[[   [[[[          [[[[       ",
            "[[[[   [[[[          [[[[",
            false
          ]
        ]
      },
      "status": "wrong answer"
    }
  ]
}
```

So it looks like the python judge is the one dropping the ending whitespace and Dodona is responsible for the misrendered table.

**Comment by charvp** [comment]
Actually, because this exercise still use the old diff system, the python judge is responsible for highlighting the missing whitespace.
