### ISSUE TITLE
charset issue in username

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1269]
There seems to be a charset issue in the name of this [user](https://dodona.ugent.be/nl/users/7356/). Could be in external source that provides use the username.

**Comment by charvp** [comment]
The character in our database is the [unicode replacement character](https://en.wikipedia.org/wiki/Specials_(Unicode_block)#Replacement_character). When looking at the logs it looks like this is the value we got from google (although it's impossible to verify this 100%). Even if the error happened at our end, it happened in a library so it would be hard for us to fix. (A quick look through the source of the relevant libraries also didn't reveal any obvious mistakes.)
