### ISSUE TITLE
Scratch-LN

### ISSUE THREAD

**Issue by dvdewall** [dodona-edu/dodona#1308]
A lot of work to get [Scratch-LN](https://github.com/scratch4d/scratch-LN)  (Ellen Vanhove) working on an exercise description page. Don't know if it's an idea to make this project available in Dodona?
<img width="1065" alt="Schermafbeelding 2019-09-22 om 09 25 57" src="https://user-images.githubusercontent.com/10370487/65383829-03da3b80-dd1b-11e9-9bc9-15e6dd34e955.png">

**Comment by charvp** [comment]
I don't see any reason to do this before there is actual scratch support in Dodona, but I guess it can be part of the thesis working on that this year. Moving this to the document outlining the work to be done in that thesis.
