### ISSUE TITLE
failed to parse partial output

### ISSUE THREAD

**Issue by ninewise** [dodona-edu/dodona#1329]
The following series of json cannot be parsed by the resultcontstructor:

```rb
rc = ResultConstructor.new('nl')
rc.feed('{ "command": "start-judgement" }')
rc.feed('{ "title": "Test", "command": "start-tab" }')
rc.feed('{ "description": { "format": "code", "description": "..." }, "command": "start-context" }')
rc.feed('{ "description": { "format": "plain", "description": "" }, "command": "start-testcase" }')
rc.feed('{ "expected": "70", "command": "start-test" }')
rc.feed('{ "generated": "45", "status": "wrong", "accepted": false, "command": "close-test" }')
rc.feed('{ "accepted": false, "command": "close-testcase" }')
```

I think this is valid partial-output and I should check why it crashes.

**Comment by charvp** [comment]
Problem was introduced in this commit: https://github.com/dodona-edu/dodona/commit/a50d574eac51def1121f1c8c87bd62c01aa83562

`escalate_status` assumes the `status` field is an object like `{ "enum": "wrong", "human": "Wrong" }` while `status` can also be a simple string (`"wrong"`).

**Comment by ninewise** [comment]
Thanks for pointing out, I even looked at this commit (thanks to git blame) and didn't see it. I'll make a PR to fix this.

**Comment by charvp** [comment]
The problem is more complicated:
```
> JSON::Validator.validate(ResultConstructor::FULL_SCHEMA, '{ "generated": "45", "status": "wrong", "accepted": false, "command": "close-test" }')
true
```

This is correct, which is why no errors were thrown about the JSON being invalid.
