### ISSUE TITLE
Group progress column not shown on mobile

### ISSUE THREAD

**Issue by thepieterdc** [dodona-edu/dodona#1360]
The progress header is shown, but the column itself is not.
![Screenshot_20191005-083659](https://user-images.githubusercontent.com/6131398/66251054-af3bb500-e74b-11e9-9796-5d26c4c0f752.png)

**Comment by bmesuere** [comment]
Because of space limitations, the bar is indeed hidden on small screens. The bug is that the header should also be hidden.
