### ISSUE TITLE
exercise info page

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1386]
Each exercise should get an info page, visible for course admins. This page could contain the following things:
- who is responsible for the exercise (i.e. who to contact in case of questions or errors)
- in what language the exercise is available (also store this in the database)
- a 'description' sourced from the repo. This would allow exercise makers to add hints for other teachers
- an optional example solution sourced from the repo
- the config that will be used for judging (e.g. time and memory limits)
- where the exercise is used? (maybe this should only be visible to the exercise owner)

**Comment by pdawyndt** [comment]
Will this information be extracted from the config files of the exercises (or from other locations in the exercise directory), and as a result, will it also be possible to setup directory-wide defaults for each of these information fields?

**Comment by rien** [comment]
Yes.
