### ISSUE TITLE
Add content pages

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1387]
Create the concept of repository-backed content pages. In its most basic form, this would be something like an exercise, but without the possibility to hand in.

This would be the first step in becoming a learning platform instead of just an exercise platform. 

There are already a few requests to also use notebooks for this. While it is relatively easy to just render those, making them interactive will require a backend.

Internal changes
- I suggest adding a "type" field to the config file. If this value is not present (i.e. all current exercises), it defaults to "exercise". The only other option right now is "content".
- Create a new "Content" model and extend Exercise from that. Move all common code from Exercise to Content. Alternatively, Content and Exercise share a common super class (name to be discussed)
- We must track the user status of the content page (within a course). No such thing currently exists for Exercise (it entirely depends on the submission status). A new model must probably be added for this. While at it, we could also use this same model to track the user status for exercises (instead of putting it in the cache which is another open issue).

UI changes
- Content type must be indicated in the exercise indexes
- We must be able to search for the content type (when adding exercises)
- Content type must be indicated in an exercise series
- On the content show page, don't show the option to hand in and the top left "hand in" link, instead add a "mark as read" UI below the exercise. The "submissions" navbar link should not be present
- The info page should not show solutions and number of submissions

**Comment by pdawyndt** [comment]
Since we now work with iframed descriptions, we might even consider notebooks being hosted on e.g. Google Colab

**Comment by pdawyndt** [comment]
Visit at Codefever also brought back a request to mix content and exercises in one exercise series, creating a learning path.

**Comment by rien** [comment]
I'm not a fan of tracking a 'visited' status and showing it to the user as if they have 'completed' the exercise. I personally dislike platforms that do this because it feels much like I'm being spied upon. Also, it could give the false impression to the teacher or the student that they understand the topic.

My opinion would be to make these items 'status'-less.

**Comment by rien** [comment]
We need a way to tell whether a repository item should become a content page. A flag `submitable: false` in the configuration file maybe? Do we want to make this a inheritable setting, so you could make a whole directory `submitable: false`?

What should happen if an exercise (with existing solutions) is set to `submittable: false`?

**Comment by pdawyndt** [comment]
The `submission:handler` part of the config file was an initial attempt to anticpate on multiple "handlers" for submission, so one possibility could be something like:

```json
{
    "submission": {
        "handler": "none"
    }
}
```

But I don't know if these "handlers" in the config are officially supported, but the original idea was to enable specifying handlers for description, submission and evaluation

```json
{
    "description": {
        "handler": "default"
    },
    "submission": {
        "handler": "default"
    },
    "evaluation": {
        "handler": "default"
    },
}
```

Where e.g. a jupyter notebook-handler for description could be specified, or a Scratch-IDE for submission could be specified. The "handler" for evaluation is what we now call a "judge".

**Comment by beardhatcode** [comment]
I would like to have this feature to provide an information page about the test my judge executes.

The output of the QuickCheck tests in the prolog-judge could benefit from a "how to read this output" page, where I could explain what the concept of QuickCheck without having to put it in every generated feedback table. 

For this is need:
- Judge description pages,
- A way to link to them in the feedback table.

**Comment by pdawyndt** [comment]
I'm in favor of having a visited status for content pages. Might also be usefull in light of following the progress of students.

If we add icons for exercises in the right-margin of exercise-in-series pages, we might as well do this for content pages. Probably we also want to make a distinction between content and exercises in this overview as well.

**Comment by pdawyndt** [comment]
In a learning path (series) of content pages (intermixed with exercise pages), there's usually also a "previous" and "next" option.

**Comment by bmesuere** [comment]
Analysis of this feature, open for discussion. I also added this to the initial issue and will keep that up to date with suggestions.

Internal changes
- I suggest adding a "type" field to the config file. If this value is not present (i.e. all current exercises), it defaults to "exercise". The only other option right now is "content".
- Create a new "Content" model and extend Exercise from that. Move all common code from Exercise to Content. Alternatively, Content and Exercise share a common super class (name to be discussed)
- We must track the user status of the content page (within a course). No such thing currently exists for Exercise (it entirely depends on the submission status). A new model must probably be added for this. While at it, we could also use this same model to track the user status for exercises (instead of putting it in the cache which is another open issue).

UI changes
- Content type must be indicated in the exercise indexes
- We must be able to search for the content type (when adding exercises)
- Content type must be indicated in an exercise series
- On the content show page, don't show the option to hand in and the top left "hand in" link, instead add a "mark as read" UI below the exercise. The "submissions" navbar link should not be present
- The info page should not show solutions and number of submissions

**Comment by pdawyndt** [comment]
Here's some terminology I see regularly used for [learning paths](https://en.wikipedia.org/wiki/Learning_pathway) and [learning management systems](https://en.wikipedia.org/wiki/Learning_management_system):

```
learning path(way) / trail [course with "exercise series" overview]
	learning module (term used in Canvas/Brightspace) [series]
		learning activity (also encountered term "event") [exercise]
```

**Comment by pdawyndt** [comment]
@bmesuere Common use of the term `content` seems to be much more generic than our intention to describe a "type of learning activity".

How about configuring a "learning activity" as having three components:

- a `description` (mandatory): what should the learner do
- a `submission` (optional): what should the learner submit as an outcome of the activity
- an `evaluation` (optional): how is the submission evaluated

By default, a learning activity then only has a description. This is a pure "content page": no submission, no evaluation. The fact that we want to track (or not) whether a learning has seen/read the description is something we could configure at this level.

The default submission we have been using so far is the ACE editor. The different types of learning activities, then resolve to different types of submissions: none, source code (single file/mutiple files), file upload (as in Indianio), multiple choice, ...

The evaluation is what we have called a "judge" so far in the context of a "source code" submission. Of course, there's no evaluation if there's also no submission (unless we have a default evaluation that is purely based on whether the learner has seen the description).

**Comment by pdawyndt** [comment]
We may also take a look at the [Shareable Content Object Reference Model](https://en.wikipedia.org/wiki/Sharable_Content_Object_Reference_Model) (SCORM) collection of standards and specifications for web-based electronic educational technology. i-Learn also asked about SCORM-support during our latest meeting.
