### ISSUE TITLE
add CSP headers to description iframes

### ISSUE THREAD

**Issue by charvp** [dodona-edu/dodona#1418]
Since the `X-Frame-Options: allow-from` directive [is deprecated](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options), we should add a Content Security Policy [`frame-ancestors`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-ancestors) directive to support modern browsers. Firefox nightly already errors on the `allow-from` directive.

**Comment by pdawyndt** [comment]
Will this issue resolve that fact that JavaScript does not work in [this description](https://dodona.ugent.be/en/courses/172/series/1696/exercises/1186776322/)? Clicking the link in the first paragraph after "Assignment" should display a hidden element, but issues the following error in Chome

```
Invalid 'X-Frame-Options' header encountered when loading 'https://medusa.ugent.be/en/exercises/1186776322/description/?token=PNPris4XqSUlfPr2': 'allow-from https://dodona.ugent.be:443' is not a recognized directive. The header will be ignored.
```

**Comment by charvp** [comment]
This pull request will fix the error you see, but will not fix the description.

**Comment by pdawyndt** [comment]
In effect, is the result that no JavaScript can be included in descriptions. The same kind of JavaScript to toggle portions of a description has been used elsewhere. Here's a full list of all descriptions in the Python programming repository that are now broken:

- reeks04:het raadsel van Nob
- reeks04:rorschachtest
- reeks04:Trevanion
- reeks04:valentijn
- reeks06:herschikking
- reeks07:dubbele vrijspraak
- reeks08:code 39
- reeks09:bewoonbare exoplaneten
- reeks09:chemie in poezie
- reeks09:de parsons code
- reeks09:nonsens
- reeks09:plutokiller
- reeks09:rorschachtest
- reeks09:sequentielogo
- reeks10:cowsay
- reeks10:genetische code
- reeks10:massacentrum
- reeks10:rontgendiffractie
- reeks10:sushi

**Comment by charvp** [comment]
As mentioned, this is unrelated to this PR.

**Comment by rien** [comment]
@pdawyndt the reason why the JavaScript in [Code 39](https://dodona.ugent.be/en/courses/172/series/1696/exercises/1186776322/) doesn't work is because we set `target="_parent"` as default for links. This would cause the `href="javascript:..."` to be executed in the parent window, but this is prevented in iframes.

Adding `target="_self"` to the anchor fixes the issue. In this case:
```html
<a style="margin-top:8px; margin-bottom:8px;" target="_self" href="javascript:(function(){$('#tip01_en').toggle(); })();">here</a>
```

The `Invalid 'X-Frame-Options' header ...` error is indeed unrelated to this JavaScript issue and can be ignored.
