### ISSUE TITLE
replace glyphicon in exercise descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1420]
For links to external resources in exercise descriptions, I have been using the following Bootstrap glyphicon.

```html
<span aria-hidden="true" class="glyphicon glyphicon-share-alt hidden-print"></span>
```

Aparently this is not longer supported. Any proposals on how to replace that by another icon? Images are not an option, otherwise they are displayed in the popup when clicked.

**Comment by pdawyndt** [comment]
Sample description with link to external resource at the end of the description: [510279751](https://dodona.ugent.be/nl/courses/172/series/1699/exercises/510279751/).

**Comment by thepieterdc** [comment]
Glyphicons are replaced by mdicons (see #1144).

**Comment by pdawyndt** [comment]
@thepieterdc ok, thanks for reminding me
