### ISSUE TITLE
Printing exercise descriptions gets screwed up

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1421]
Since the introduction of iframes in exercise desciptions, printing those pages gets screwed up.

**Comment by pdawyndt** [comment]
Same happens when printing the overview containing all exercise descriptions of a series. Actually, it seems as if the page layout in the printed version is too narrow.

**Comment by charvp** [comment]
Can you post a screenshot/explain more what you think is wrong? Things look fine when I print to a PDF.

**Comment by pdawyndt** [comment]
![image](https://user-images.githubusercontent.com/5736113/67157428-4435d500-f32c-11e9-8513-bd964e208a1f.png)

**Comment by rien** [comment]
I have fixed the width issue with cc9b5761. However, I have bumped on another problem: the iframe-resizer library we use [doesn't support resizing PDF's](https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/troubleshooting.md#pdf-and-opendocument-files).

**Comment by bmesuere** [comment]
@rien I think the unsupported thing is resizing iframes (only) containing a PDF, which is not something we do as far as I know.

**Comment by bmesuere** [comment]
This seems to be fixed?

**Comment by pdawyndt** [comment]
Not on my machine.

**Comment by rien** [comment]
I have done some further investigation and printing seems to be broken in different ways in firefox and chromium. I guess while using iframe's we've entered the land of obscure render engine bugs which may not be easy to solve.

However, printing seems to be good when going to the iframe's location (e.g. https://medusa.ugent.be/nl/exercises/1281456553/description/adleTCAeEJlDEEj8/).

I suggest closing this issue because the effort is probably not worth the reward.

**Comment by pdawyndt** [comment]
Is there a way we could automatically redirect the printing to medusa from dodona? I guess we don't want users to delve into the iframe content themselves?

**Comment by niknetniko** [comment]
> Is there a way we could automatically redirect the printing to medusa from dodona?

This isn't possible; the best we can do is include our own print button on the page and/or intercept the Ctrl-P shortcut. The print menu option from the browser is not modifiable, so when a user clicks the menu, it will always print the current page (this is how e.g. Google Sheets works).

We can apply the CSS fix for the width, but Chromium & Safari will still have semi-broken results, and Firefox will be completely broken (the [relevant bug](https://bugzilla.mozilla.org/show_bug.cgi?id=113217) was opened 19 years ago, so I wouldn't count on it being fixed any time soon)

**Comment by pdawyndt** [comment]
Printing exercise descriptions look better after move to Bootstrap 5, but components of the page that used to be hidden, are now visible again in the print-version.

![image](https://user-images.githubusercontent.com/5736113/119159747-d85fa500-ba57-11eb-9c00-16a9d178e438.png)

**Comment by chvp** [comment]
Not fixable due to our use of iframes.
