### ISSUE TITLE
iframe on exercise description pages never shrinks

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1426]
The iframe showing the exercise descriptions only extends automatically, but never shrinks automatically. This might leave some empty space at the end of the exercise desciptions. This happens:

- when exercise descriptions are shorter than the initial height of the iframe ([example](https://dodona.ugent.be/nl/courses/172/series/1704/exercises/1555355466/))
- when exercise descriptions dynamically grows and shrinks (try expanding the epilogue at the end of [this exercise](https://dodona.ugent.be/en/exercises/1068912807/) description)

**Comment by bmesuere** [comment]
https://github.com/davidjbradshaw/iframe-resizer/blob/master/docs/troubleshooting.md#iframe-not-downsizing
