### ISSUE TITLE
exercise descriptions load very slow sometimes

### ISSUE THREAD

**Issue by charvp** [dodona-edu/dodona#1427]
We parse the html of the description, which makes it slow. Check if we can do this in JS maybe?

**Comment by charvp** [comment]
https://medusa.ugent.be/nl/exercises/467970954/description?dark=false&token=ECwe6DZoWd-6pWUP

**Comment by bmesuere** [comment]
Alternative or complemental solution is more agressive caching of the entire iframe page since it's no longer dynamic.

**Comment by rien** [comment]
Another possible solution: most descriptions don't use custom Javascript or styling. We could sanitize the exercise description by default and allow exercise creators to _opt-in_ for the sandbox if they wan to use custom styling or Javascript.

Of course caching would still be needed to compensate for the performance hit we get from sanitizing every description.
