### ISSUE TITLE
Remember "hide correct test cases"-toggle

### ISSUE THREAD

**Issue by thepieterdc** [dodona-edu/dodona#1437]
If you toggle the "Hide correct test cases" switch after submitting an incorrect solution, this is not remembered the next time you submit an incorrect solution.

**Steps to reproduce:**
1) Submit an incorrect solution to any exercise.
2) Click on the "Hide correct test cases"-switch.
3) Click the edit-pencil.
4) Re-submit the same incorrect solution.
5) Observe that the incorrect test cases are not hidden anymore, and you have to re-click the switch.

**Comment by thepieterdc** [comment]
This could be stored in e.g. local storage/session storage, or as a user preference.

**Comment by jorg-vr** [comment]
gain not worth the potential confusion
