### ISSUE TITLE
undefined translation string

### ISSUE THREAD

**Issue by thepieterdc** [dodona-edu/dodona#1457]
![image](https://user-images.githubusercontent.com/6131398/68120389-86067400-ff05-11e9-9790-ff5c4f0db585.png)

**Steps to reproduce:**
1. Go to a course-scoped exercise which is publicly accessible, without registering for the course.
2. Attempt to submit anything.

**Comment by charvp** [comment]
Can't reproduce. Are you sure you have internet access/this isn't some other problem? Can you check the request details in the dev tools of your browser?

**Comment by thepieterdc** [comment]
@charvp this is the response:

![image](https://user-images.githubusercontent.com/6131398/68120819-8f441080-ff06-11e9-8501-df062fc019d1.png)

**Comment by charvp** [comment]
Ok, I've figured out what goes wrong here. A few issues:
* There is a code path in the case that a submission fails where we don't set an error message, this shouldn't happen.
* When checking if a submission is allowed to be made, we use the course in the submission. However, the course is thrown away when the user isn't subscribed to the course, so just the public/private status of the exercise used.
* Private exercises can be seen by unsubscribed users in moderated courses.
