### ISSUE TITLE
width difference when rendering input and output in the feedback table

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1465]
The following [screenshot](https://dodona.ugent.be/nl/courses/172/series/1993/exercises/1440716836/) shows and example of input (`stdin`) and output (`stdout`) in the feedback table that has the same number of characters on each line (in the output certains columns of the input have to be replaced by spaces), but differs in width.

![image](https://user-images.githubusercontent.com/5736113/68394415-134c0180-016e-11ea-8527-09251632f7d0.png)

Don't know if the difference in width is because the font is not truely fixed width or because there's a slight difference in font size between input and output, but it slightly hampers the comparison between input and output.

**Comment by beardhatcode** [comment]
Odd, it seems to work correctly for me 
https://dodona.ugent.be/nl/submissions/4196831/

![2019-11-07-150130_grim-slurp](https://user-images.githubusercontent.com/662538/68395126-768a6380-016f-11ea-84b3-4c78874adf10.png)

**Comment by beardhatcode** [comment]
The forntsizes appear to be 13px and 14px

**Comment by rien** [comment]
This is not the case in my browser when looking at [this exercise](https://dodona.ugent.be/en/submissions/4196822/) locally.

**Comment by bmesuere** [comment]
The top "code" span has an explicit font size of 13px, the bottom "output" span has no font size set and renders it in 14px in Chrome.
