### ISSUE TITLE
wrong display of help on menu items in feedback table

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1469]
When clicking on of the menu items on top of the feedback table, the popup containing the help won't disappear until the next mouse click.

![image](https://user-images.githubusercontent.com/5736113/68568555-2f94ba80-045c-11ea-800d-a42e0f9bd90c.png)

Is this expected behaviour? Since the popup is also triggered when hovering over a menu item, it may cause two popups to be displayed at the same time (causing potential overlap).

![image](https://user-images.githubusercontent.com/5736113/68568633-6c60b180-045c-11ea-9474-9f35a2b53ad6.png)

![image](https://user-images.githubusercontent.com/5736113/68568649-78e50a00-045c-11ea-839b-b9748a1cc484.png)

Would seem more logical if the popup always disappears when hovering away from the menu item.

**Comment by charvp** [comment]
This is expected behaviour. Clicking the button focuses it, which is (next to hovering) also a trigger for bootstrap to show the tooltips. Except for overriding default bootstrap behaviour there is little we can do about this.
