### ISSUE TITLE
optimize cropping at shaded margins of wide tables

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1514]
The new release gives a visual hint that tables extend to the left or to the right. However, some redundant pixels are displayed to the left of the left shade or to the right of the right shade.

![image](https://user-images.githubusercontent.com/5736113/69753312-8fc17700-1153-11ea-8df5-fc34617ecbc7.png)

**Comment by charvp** [comment]
Sadly, this is not really fixable.
