### ISSUE TITLE
Line number of Invalid syntax-error in Python is missing

### ISSUE THREAD

**Issue by twalcari** [dodona-edu/dodona#1521]
Currently, when a student makes a syntax error, it does not mention the line number on which this happened anymore.

Can this be hotfixed on dodona.ugent.be ASAP (There is a test for the students of Informatica I on Monday)?

> Compilatiefout · Ongeldige broncode
> 10 minuten geleden
> Traceback (most recent call last):
> SyntaxError: invalid syntax

**Comment by charvp** [comment]
Do you have links to submissions where this occurs? I'm not entirely sure where you expect a line number to show up but don't see one.

**Comment by charvp** [comment]
I can't think of any changes in the latest release immediately that would impact that.

**Comment by twalcari** [comment]
https://dodona.ugent.be/nl/submissions/4388047/

**Comment by charvp** [comment]
The traceback at the top of the feedback table has never contained the line number. Students can see the line with the error in the code tab beneath.

**Comment by charvp** [comment]
Does the feedback table look different for you?
![image](https://user-images.githubusercontent.com/42220376/69810199-a87d6b80-11eb-11ea-85ad-7f6d04c93718.png)

If so, do you have any errors in the console?

**Comment by twalcari** [comment]
I just compared a screenshot I made this morning, and it seems to have changed since then..

https://dodona.ugent.be/nl/submissions/4383629/ looked this morning like this:

![image](https://user-images.githubusercontent.com/1088931/69810613-9819c080-11ec-11ea-8d1d-9b51cb91afe8.png)

When I revisit the page, it mentions  the error inline:

![image](https://user-images.githubusercontent.com/1088931/69810675-b8e21600-11ec-11ea-8d3e-60da503c5a32.png)

I guess a hotfix is in place, as Peter Dawyndt and Bart Mesuere were already mailed about the problem this morning.

As I couldn't find anything in the commit log about a fix, and I was pleasantly surprised by how fast my other issue created here was fixed, I decided to create an issue for it here.

I'll leave this issue open, so that you can confirm that the codebase also contains the (hot?)fix for this issue?

**Comment by charvp** [comment]
Your screenshots are not of the same submissions. Since I am the one who actually makes releases and deploys them, I am very sure that no fix was deployed today.
