### ISSUE TITLE
images can no longer be included in course/series descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1527]
It seems no longer possible to include images (hosted elsewhere) in the course/series descriptions. Is this the result of sanitizing. Don't we want to allow this?

**Comment by bmesuere** [comment]
We opted for a strict implementation on the Dodona domain with the plan to allow more where needed. This is obviously a valid use case, so the CSP will be updated accordingly. 

When do you have a session today, so we don't accidentally break thing during a demo?

**Comment by bmesuere** [comment]
a fix was deployed a few minutes ago
