### ISSUE TITLE
pylint messages are displayed incorrectly

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1531]
Some linters such as pylint try to highlight the exact location of the issue. They do this by copying the offending line in their output and adding a line below containing spaces and `^` to show the position.

Right now, we render the linting messages in Roboto which is not monospaced. The result of this is that the location indication is incorrect:
![image](https://user-images.githubusercontent.com/481872/69899422-f8803d80-1365-11ea-880b-96491dd3156c.png)
vs:
![image](https://user-images.githubusercontent.com/481872/69899426-15b50c00-1366-11ea-8725-21934b86b623.png)

Solutions are:
- Render the real message in roboto, the other lines monospaced
  - This is not possible without introducing message types (and multiple types within a single message) and modifying the judge.
  - Alternatively, this could be hacked into the pythia renderer instead
- Render everything monospaced
  - Not a fan of this. We will want to render review comments in a nice font anyway
- Strip the location stuff out of the messages
  - This is my preferred solution. Adding a column position might be a valid use case, but we should add generalized support for this. Repeating the code line seems unnecessary in our use case where the code is displayed directly above.

**Comment by rien** [comment]
I'm not a huge fan of stripping location information. With this error message it's pretty clear where you should look. But if you get an `unexpected token` message it's guesswork to which token is unexpected, especially if you are new to programming.

I would suggest adding message types and rendering all judge messages in a monospace font.

**Comment by charvp** [comment]
Pretty sure this is fixed already? Annotations are shown in a monospace font.

**Comment by bmesuere** [comment]
Indeed
