### ISSUE TITLE
Illogical order of series in course scoresheet

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1538]
In [this course](https://dodona.ugent.be/en/courses/220/) the series have been ordered as follows on the course page:

- getting started
- if-statements
- loops
- strings
- functions

However, they are listed in reverse order in the course scoresheet, which does not feel natural in this case.

![image](https://user-images.githubusercontent.com/5736113/69914447-d90c1200-1444-11ea-97e6-defa65a3fa6d.png)

This is caused by the fact that Dodona lists the series in reverse chronological order on the course page, but in chronological order in the scoresheet. For this course, the series have been listed in "chronological" order on the course page, so they should stay in that order in the scoresheet.

The only solution to remedy this, seems to give courses an extra parameter that indicates how the series are listed on the course page. When a new series is added, it will also appear either at the beginning or the end of the course page, based on the setting of this parameter.

**Comment by bmesuere** [comment]
The issue is valid, but the explanation is not. Series can be reordered by teachers for some time now. The dropdown probably sorts by id instead of the set order.

**Comment by pdawyndt** [comment]
Note only in the dropdown, but also the columns in the overview itself.
