### ISSUE TITLE
make english the default language for Dodona

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1539]
The default language for Dodona is currently set to Dutch. This feels odd for non-Dutch speakers. Since Dutch speakers would probably have less issues with the fact that the default language is English upon first arrival at Dodona, I would recommend switching the default setting.

**Comment by thepieterdc** [comment]
It would make more sense to detect the language using the `Accept-Language` header, if the language has not yet been chosen by the user. Simply changing the default language to English seems odd, given the fact that the vast majority of Dodona users are native Dutch speakers.

**Comment by thepieterdc** [comment]
This gem should be able to do the job: https://github.com/cyril/accept_language.rb
