### ISSUE TITLE
reduce information overload in Code tab

### ISSUE THREAD

**Issue by twalcari** [dodona-edu/dodona#1540]
I'm observing students during a test, and the following code review screen caught my eye:

![image](https://user-images.githubusercontent.com/1088931/69943452-a8c88000-14e5-11ea-9a45-585ada5a1b3d.png)

This student has a total overload in messages to process.

Can you hide the tips (blue left bar), and maybe the warnings (orange  left bar), as long as one or more syntax errors (red left bar) are present? Imho, they have no value towards the student on such a moment.

**Comment by bmesuere** [comment]
Good suggestion!

We'll need to find the best way to implement this. One way is to filter this server side, but it would be better to handle at the client. We planned to add a "hide annotations" button in a future release anyway

**Comment by pdawyndt** [comment]
Note: the 'undefined variable' annotation will also be available directly from the other tab, where the unit tests are reported. There it won't be mixed with the info and warnings.
