### ISSUE TITLE
homepage cards do not fit nicely

### ISSUE THREAD

**Issue by rien** [dodona-edu/dodona#1551]
@pverscha mentioned the course cards on his homepage were shown in a weird way:

![image](https://user-images.githubusercontent.com/3226995/69968973-cca6b880-151b-11ea-9590-8771117bb481.png)

The 'Programming' course card should ideally fit closer to the card above, like the 'Computergebruik' card does.

**Comment by chvp** [comment]
Is this fixed by bootstrap 5?

**Comment by bmesuere** [comment]
In a way
![image](https://user-images.githubusercontent.com/481872/120882465-6ef3a080-c5d8-11eb-9411-e039456c7d8b.png)

**Comment by chvp** [comment]
Why is advent of code taller in that screenshot?
