### ISSUE TITLE
students indicate that Python Tutor does not work anymore

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1555]
seems to be specifically for exercises of series 09, where we work with files

**Comment by rien** [comment]
This is caused by the recent firewall changes, blocking docker containers from reaching our hosts.

I will add an exception for Python tutor traffic to the firewall.

**Comment by rien** [comment]
Should be fixed.

**Comment by pdawyndt** [comment]
Works with me if I do some manual testing.
