### ISSUE TITLE
display of extra text-test-files does not contain trailing newline

### ISSUE THREAD

**Issue by toonijn** [dodona-edu/dodona#1556]
When the content of a data file is viewed, trailing newlines are omitted (see screenshot). This causes confusion.

See also: https://dodona.ugent.be/nl/submissions/4456002/

![Selection_102](https://user-images.githubusercontent.com/9020072/70308436-87c89d80-180b-11ea-88ff-79dc48e901c8.png)

**Comment by pdawyndt** [comment]
While we're at it, maybe also add line numbers?

**Comment by toonijn** [comment]
Expected view:
![Selection_103](https://user-images.githubusercontent.com/9020072/70310456-f7d92280-180f-11ea-980f-56ba805876e3.png)
