### ISSUE TITLE
syntax highlighting of return values hard to read in dark mode

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1559]
In dark mode, syntax highlighting of return values should be light grey instead of dark grey, so that it's easier to read.

![image](https://user-images.githubusercontent.com/5736113/70387133-829d5700-19a1-11ea-8729-c078787844c3.png)

**Comment by MrKickkiller** [comment]
![image](https://user-images.githubusercontent.com/5099359/70388234-43760280-19af-11ea-86b3-7e4896500692.png)
