### ISSUE TITLE
Cloud IDE

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1575]
Schools sometimes find it hard to install software locally and might therefore prefer to work completely in the browser. This issue is a starting point to collect some features that might be requested from a full-fledged IDE integrated in Dodona, and some existing implementations that we might look into as possible candidates to be integrated in Dodona.

**Comment by pdawyndt** [comment]
## IDE features

- run source code in browser before submitting it
  - enter input interactively
  - work with files
- debug source code in browser before submitting it
- run limited sequence of predefined tests on code before submitting it

**Comment by pdawyndt** [comment]
## Existing implementations

- [repl.it](https://repl.it/) (open source???)

**Comment by rien** [comment]
@niknetniko suggested another platform which is _like_ VS Code but with more possibilities: https://theia-ide.org/.

**Comment by pdawyndt** [comment]
https://www.pythonanywhere.com/

**Comment by pdawyndt** [comment]
[AWS Cloud9](https://aws.amazon.com/cloud9/)

**Comment by bmesuere** [comment]
https://pyodide.org/en/stable/

**Comment by bmesuere** [comment]
This was superseded by #3141.
