### ISSUE TITLE
custom diff of Python judge not displayed in feedback

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1579]
The Python judge adds a custom diff if a function returns a dictionary that differs from the expected dictionary. Dodona no longer shows this custom diff and also does not perform a diff by itself. Is that due to the length of the string representation of the dictionary and/or the length of the custom diff?

![image](https://user-images.githubusercontent.com/5736113/70850556-f355df00-1e8b-11ea-9875-bf3f0e501904.png)

In the above [example](https://dodona.ugent.be/en/submissions/4526839/), the key `'RGG'` maps to `'?'` instead of `','`, which is not immediately clear without highlighting.

**Comment by charvp** [comment]
The custom diff of the python judge was removed to harmonize the diffing between the python judge and the other judges (this also removed bugs in the custom python diffing, since it isn't used anymore). The reason there is no line-level diffing in this case is indeed because the line is too long.

**Comment by pdawyndt** [comment]
This is a serious reduction in the ease of interpretation of the feedback for end users. As this is the core business of Dodona, I suggest we should reconsider this.
