### ISSUE TITLE
git command missing in Bash judge

### ISSUE THREAD

**Issue by pverscha** [dodona-edu/dodona#1580]
I received an email today from one of the "Computergebruik"-students informing me of the fact that `git` is not available in the Dodona judge for Bash. This command is however required for [this exercise](https://dodona.ugent.be/en/exercises/325238119/). Is it possible to update the Bash judge and install git?

**Comment by thepieterdc** [comment]
This should be possible by modifying the Dockerfile https://github.com/dodona-edu/docker-images/blob/master/dodona-bash.dockerfile

**Comment by charvp** [comment]
I created a PR in the docker-images repo. It's probably best if you make issues like these in that repo from now on.

**Comment by charvp** [comment]
Fix has been deployed.
