### ISSUE TITLE
Code copied from code tab contains extra newlines

### ISSUE THREAD

**Issue by charvp** [dodona-edu/dodona#1581]
When selecting all the code in the code tab and then copying it, each line will have an extra newline. This is annoying.

**Comment by cedricdeboom** [comment]
I've seen the following happening with my students, and it turns out that:
- in Firefox, for each pep-8 comment there is an extra newline in the copied code.
- in Edge, the pep-8 comments are copied together with the code (which is quite annoying).
- in Chrome, there are no issues.

**Comment by pdawyndt** [comment]
Why can't we pass the original code, as is, to the page where the code can be edited?

**Comment by bmesuere** [comment]
@pdawyndt this is about manually copy-pasting text

**Comment by pdawyndt** [comment]
Thanks for the info. Maybe in addition to a proper solution for the manual copy-paste issue, we could also provide a copy-to-clipboard button for the entire code.

**Comment by MrKickkiller** [comment]
Note to self: Safari also allows you to copy the line numbers

**Comment by charvp** [comment]
Fix is deployed.

**Comment by ninewise** [comment]
Copying to clipboard is indeed fixed; using primary selection still includes additional lines with the line numbers (but only a minority of the users would notice).
