### ISSUE TITLE
Media folder of private exercises not accessible

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1588]
At the start of today's evaluation, we had to make the exercises public, otherwise the files from the media folder were not accessible (both images, text files or any other files). Private exercises were contained in a hidden exercise series, so they should have been accessible, but they didn't.

note: @rien observed that the media files were pointing to dodona instead of medusa

**Comment by charvp** [comment]
Two separate issues AFAICT:
 * Requests are redirected to `dodona.ugent.be` and lose the query part of the URL at that point.
 * `src` attributes of images are not rewritten.

**Comment by rien** [comment]
There is no translation happening because there is no URL rewriting
happening for closed exercises. The request to medusa is redirected to
dodona, and if the user doesn't have permission the image doesn't work.

Possible solutions: again trying to send a token with the image URL, or
checking whether a student could have access trough a token link.

**Comment by charvp** [comment]
When I tested just now (by impersonating a student) the rewriting did happen. On the K3 exercise, the links to the files had been changed. Then the token was lost when the redirect to Dodona happened.

**Comment by rien** [comment]
The first issue should have been fixed by #1553.

The rewriting should only happen on links (because these are not immediately loaded), other items (images, videos, etc.) cannot be rewritten by JavaScript because this breaks them in some cases.

**Comment by rien** [comment]
This should also be thoroughly tested with puppeteer.

**Comment by MrKickkiller** [comment]
@rien Running puppeteer in Github Actions should be fixed soon (only need to fix/patch seeding), but my branch is based from the `annotation-submission-button` branch, so will include more code than you would probably want.

**Comment by charvp** [comment]
Fix is deployed.
