### ISSUE TITLE
Add number of items to headers of course/series overview

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1593]
We could add badges to the headers of the series overview that indicate how many users are included in the view (user header) or how many correct solutions there are for each exercise in the view (exercise headers). Here's a mockup.

![image](https://user-images.githubusercontent.com/5736113/70911029-460cd380-2011-11ea-9a50-ba3eeda0a654.png)

**Comment by pdawyndt** [comment]
Or badge in user header indicates how many have correctly solved all exercises in the view and indicate the total number of users elsewhere. Or we could add a column indicating how many exercises each student has solved correctly (and make this column sortable).

**Comment by bmesuere** [comment]
This is not the correct usage of a badge. It should only be used to indicate if there are a number of "hidden" things (such as annotations on another tab). Adding a "summary" line to the table might be a better solution UI-wise.

**Comment by pdawyndt** [comment]
@bmesuere  I'll leave the UI solution to the specialist, but when I look at the screenshot above, it also reminds me that there was an issue introduced with ALL dropdowns (#1537) and also the text on the orange button (top left) is a bit long and often overflows the width of the button. Was there actually a reason why a button was needed here, instead of adding this functionality to the three-vertical-dots-menu next to the search bar?
