### ISSUE TITLE
"Only last submission" option does not work correctly

### ISSUE THREAD

**Issue by jvdrhoof** [dodona-edu/dodona#1596]
When downloading the submissions to a given series of exercises, choosing to include only the last submission still results in all submissions being present, both in the directory and the (optionally) included CSV file.

**Comment by charvp** [comment]
We've seen this happen as well. I will make sure this is fixed while working on #1572.

**Comment by bmesuere** [comment]
Thank you for your report, @jvdrhoof. This will be fixed in a next release. We already have a github issue for this problem #1578 so I'll close this one.
