### ISSUE TITLE
Viewing a submission that reads files in the debugger shows a 404 HTML page being read, even when the file is there and works in evaluation

### ISSUE THREAD

**Issue by MrKickkiller** [dodona-edu/dodona#1599]
Example submission: https://dodona.ugent.be/nl/submissions/4568217/
If we debug the `.hoofdstad` exercise, we see that the `__init__` code is reading a 404 HTML page even when the file is simply there, as shown by the exercise output.

**Comment by pdawyndt** [comment]
Clicking the filename to download the file doesn't work either.

**Comment by pdawyndt** [comment]
@rien will this also be solved by PR #1598? This is a public exercise, so the media files should also be accessible.

**Comment by charvp** [comment]
The problem here is in the exercise, not in Dodona.  The link goes to `data/landen.csv` while the files of the exercise contains `workdir/landen.csv`.
