### ISSUE TITLE
Remove previously highlighted line

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1601]
This [submitted solution](https://dodona.ugent.be/nl/submissions/4580192/) has an error with two links to the source code.

![image](https://user-images.githubusercontent.com/5736113/71321620-785c7c00-24bc-11ea-8ed4-afbb7798bb75.png)

If both lines are clicked in succession, only the last line should be highlighted, but both lines are highlighted:

![image](https://user-images.githubusercontent.com/5736113/71321615-611d8e80-24bc-11ea-9c27-07be8f6d287e.png)

**Comment by charvp** [comment]
Fix is deployed.
