### ISSUE TITLE
Incorrect links to media documents in descriptions of private exercises

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1632]
Links to document in the media folder from the description of private exercises are not correct (and so don't work). See the links in the example section of [this description](https://dodona.ugent.be/nl/courses/186/series/2083/exercises/235452497/).

**Comment by pdawyndt** [comment]
Ignore this one. Apparently they started working after some time. May have been an issue with the exercise not having been reprocessed completely after pushing to the repository.

**Comment by charvp** [comment]
The exercise token changes when the exercise is changed, so that could have been the issue. (Note that the link to `Rogelio Mcdaniel.pdf` is wrong in the exercise description, but this is not a Dodona issue.)
