### ISSUE TITLE
Exercise order in CSV file created during export is not stable

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1633]
The API used by Indianio no longer preserves the original order of the exercises in a series.

**Comment by charvp** [comment]
Can you explain in more detail what you mean? AFAIK the only "API" that Indianio uses is the download of the zip-file containing a student's solutions.

**Comment by pdawyndt** [comment]
We have a script to configure Indianio project for a given exam series. This script no longer preserves the order of the exercises in a series. I was assuming the script (by Niels Neirynck) was using the Dodona API to fetch information for an exercise series, but this might be wrong. @toonijn might provide more details about how the script fetches its info from Dodona.

**Comment by charvp** [comment]
It seems like the script just uses the order the files were added to the zip. I honestly don't think this is something that should be fixed on the Dodona side.

**Comment by charvp** [comment]
I read it incorrectly: it uses the order of the entries in the CSV file. This is something that should be fixed.
