### ISSUE TITLE
Exercise access token changes with every update

### ISSUE THREAD

**Issue by rien** [dodona-edu/dodona#1634]
The exercise access token changes with every update, revoking access for users who have an exercise description with an old token.

In the scenario of an exercise which is updated during an exam, this would require all students to refresh their pages, which is not ideal. Correcting a simple typo is enough to trigger this.

I suggest to change this behavior to only change access token when the permissions change. This fix could be combined with #1233.

**Comment by charvp** [comment]
I think it's more complicated than that. What makes the most sense is that the access token should change when a student's access to the exercise is taken away. This means that the permissions of the series containing the exercise are more important than the permissions of the exercise itself.

Some remarks:
 * Tokens of public exercises don't ever have to change.
 * When a series is made open, the tokens of the exercises contained in it don't have to change either.
 * When a series is closed or made hidden, the tokens of the exercises contained in it should change.
 * When an exercise is added to or removed from a series its token should change as well. (Not entirely sure about this last one.)

**Comment by ninewise** [comment]
Wouldn't it be easier to use user tokens instead of exercise access tokens? Then you can just check if that user has access to the exercise at the moment of the request?

If you change this token periodically (on logout or at the end of a session), it wouldn't be to bad if users passed their tokens to others.

**Comment by rien** [comment]
That sounds like  a simple, but effective solution. I currently can't think of any downsides to that.

What do @bmesuere and @charvp think of this proposal?

**Comment by charvp** [comment]
I can't think of any problems immediately and it seems like an elegant system, but I am hesitant to overhaul this system completely just after we got it working again.

**Comment by rien** [comment]
After a more closer look, moving tokens to users does not actually change the situation.
