### ISSUE TITLE
Bulk review

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1642]
UNDER CONSTRUCTION

List of requirements for a bulk review feature (e.g. after test or exam) from first prototype. Please comments/complete. This may serve as a first steps toward prioritising the individual features and planning the iterations for implementing a bulk review feature.

- [code review](https://en.wikipedia.org/wiki/Code_review) to submission(s) for a single exercise/student
  - manually add an annotation about the entire code or to a selection of the code (single line/multiline, code range, set of code ranges)
  - specific types of annotations: strikethrough (e.g. for unnecessary parts of the code, or code sections that are completely wrong), linking multiple sections in the code (e.g. when code duplication is detected), ...
  - allow both student and course managers to make annotation on a submission (e.g. for students to ask a question about a specific point in the code)
  - student/teacher may respond to previous annotations (e.g. asking questions or giving clarifications)
  - either linked to review (visibility dependent on release conditions of review) or independent of review (immediately visible for submitter)
  - expose or hide identity of reviewer to student (anonymous reviews)
  - iterate over all submissions for a selected user and a selected exercise
  - reuse annotations made previously (as is or with slight modifications)
  - automatically hint that previously made annotations also apply to a submission
  - change-based reviews: map annotations from one submission to another student for the same exercise of the same student
  - reviewers submit updated versions of the code under review (e.g. to check if an update would work correctly) that are evaluated the same way as regular submissions, but are stored differently (e.g. not stored at all or stored as part of the review, not as a personal submission of the reviewer)
  - export/print reviewed code
- grading of submission(s) for a single exercise/student
  - global grade and subgrades (e.g. for individual functions/methods) as a numeric score
  - rubrics
  - link grades as penalty to (common) mistakes encountered during review (see [ans Delft](https://www.ans-delft.nl/))
  - export/print graded code; transfer scores to learning platform via LTI
- bulk review
  - always linked to course
  - link selection of exercises (from course) to review (add/remove); what if exercise is removed from course
  - link selection of users (from course) to review (add/remove); what if user unregisters from course
  - iterate over all users linked to the review for a selected exercise; anonymised students, random order
  - iterate over all exercises linked to the review for a selected user
  - select one of the submissions for a selected exercise and a selected user (e.g. based on submission deadline set in review, manual selection)
  - release conditions: manual release, set release date, revoke release?
  - statistics about common mistakes across all reviews of an exercise, time invested in review, whether students have look at the reviews and/or acted upon them
  - reuse common mistakes as tips & tricks for an exercise; distinction between exercise-specific mistakes and more global mistakes (e.g. linked to a programming language or well-known code smells)
  - iterate all submissions linked to a particular mistake
- peer review
  - distribute review assignments over group of students

**Comment by pdawyndt** [comment]
## other review platforms for (student) code

- [Gerrit Code Review](https://www.gerritcodereview.com/)
- [Gradescope](https://www.gradescope.com/)
- [GradeWork](https://www.xebic.com/nl/oplossingen/gradework)
- [Canvas](https://community.canvaslms.com/)
- [Ans Delft](https://www.ans-delft.nl/)

**Comment by charvp** [comment]
This would be better as a wiki article or something else. This issue is essentially uncloseable because it will be impossible/probably undesirable to implement all ideas presented in this issue.
