### ISSUE TITLE
scrollbar is light themed in dark mode

### ISSUE THREAD

**Issue by Zelzahn** [dodona-edu/dodona#1645]
At the bottom of Code (when looking at submitted solutions):
![2020-01-18-163550_526x134_scrot](https://user-images.githubusercontent.com/2775701/72666302-0884d700-3a11-11ea-849a-7c4bb581f49c.png)
While typing out code:
![2020-01-18-160321_207x466_scrot](https://user-images.githubusercontent.com/2775701/72666303-0ae73100-3a11-11ea-9bb8-8c3e15cddf87.png)

**Comment by bmesuere** [comment]
These are browser/OS elements. If we override these manually, it's hard to make them look good on all platforms. If you want them to look good in dark mode, switch your os and/or browser to dark mode.
