### ISSUE TITLE
Elixir request

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1646]
> Het ELIXIR Belgium logo toevoegen aan de websites van beide tools (zie bijlage)

About page seems to be the best place for this

> Dodona registreren op het ELIXIR Tools and Services Registry bio.tools

> Terms of use voorzien op de websites van beide tools (hier vind je enkele voorbeelden van hoe andere services dit aanpakten: https://bioinformatics.psb.ugent.be/plaza/pages/terms_of_service , https://orval.ibsquare.be/about#disclaimer , https://tcrex.biodatamining.be/terms_conditions/  )  

Maybe this is already covered

**Comment by niknetniko** [comment]
Status update:
- [x] Logo was added
- [x] Adding to terms of use: we don't have that, so nothing to do I guess, otherwise we'll have to write some.
- [ ] Register Dodona in https://bio.tools/

**Comment by bmesuere** [comment]
I made the registration on bio.tools, so this can be closed.
