### ISSUE TITLE
Search bar isn't shown on some submission index pages if user isn't Zeus

### ISSUE THREAD

**Issue by beardhatcode** [dodona-edu/dodona#1660]
The filter button (![Screen Shot 2020-01-25 at 17 10 39](https://user-images.githubusercontent.com/662538/73123980-1351e580-3f96-11ea-92fd-491b27cfc659.png)) shown in the submission list on exercise pages outside a course, on the submissions page of a judge and on the submissions page of a user don't work. Those views also don't have a search bar if you are not Zeus.

Examples:
https://dodona.ugent.be/nl/judges/10/submissions/
https://dodona.ugent.be/nl/exercises/1970586606/submissions/
https://dodona.ugent.be/nl/users/3624/submissions/

**Comment by charvp** [comment]
Solution here seems (to me) adding a search bar to those views.

**Comment by beardhatcode** [comment]
_update_: also for user submission list outside course

**Comment by beardhatcode** [comment]
_update_: Problem only occurs when user is not Zeus.

**Comment by beardhatcode** [comment]
Probably caused by following `if`

https://github.com/dodona-edu/dodona/blob/2c3d429f90deb850827440fa23c0326f769d886b/app/views/submissions/index.html.erb#L30-L36
