### ISSUE TITLE
Copy course page does not list own courses first

### ISSUE THREAD

**Issue by beardhatcode** [dodona-edu/dodona#1661]
I was going to copy the 2018-2019 course page from last year when creating a new course.

When I wanted to select the course to copy from, the list did not contain courses I was admin for on the first page. I feel like it would make sense to put these courses first initially.

https://dodona.ugent.be/nl/courses/new/

**Comment by charvp** [comment]
You can just go to last year's course and use the copy option in the menu there if you know what course you're going to copy.
