### ISSUE TITLE
Add option to remove courses

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1683]

**Comment by bmesuere** [comment]
- ask for a very clear confirmation
- remove the course id from the submissions within that course
- limit removal to courses with fewer than _x_ submissions

**Comment by pdawyndt** [comment]
Why not mark courses with submitted solutions as "deleted" without actually deleting it from the database. This would allow to delete any course, irrespective of the number of submitted solutions, and would also enable to easily restore the course upon request.

I guess courses (and their series) don't take up a lot of resources in the database. The option to delete courses is more something to keep a clean list of courses in the user interface, by getting rid of unused or test courses, rather than an issue of reducing the size of the database.

By not actually deleting courses with associated submisssion, we also keep the number of dangling submissions (submissions not linked to a course) low. We wanted to avoid dangling submissions as much as possible.
