### ISSUE TITLE
Bootstrap tooltips are only initialized on first load of course member listing

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1690]
The class progress bars have a popup showing the numerical values behind the bars.

![image](https://user-images.githubusercontent.com/5736113/74151758-2b1f9f80-4c0d-11ea-9de1-f0f004b0bed1.png)

This popup is missing from the user progress bars (on the list of course users), but could contain similar information as with the class progress bars (# exercises solved/started by the user in the course).

![image](https://user-images.githubusercontent.com/5736113/74151837-50aca900-4c0d-11ea-81e7-5d9623335d38.png)

**Comment by pdawyndt** [comment]
Apparently these popups are there, so no idea why they weren't there upon first inspection.

**Comment by pdawyndt** [comment]
Found the correct issue: the popups only appear on the first page !

**Comment by charvp** [comment]
The problem is that the `initTooltips` method is only called on first page load:
https://github.com/dodona-edu/dodona/blob/develop/app/javascript/packs/application.js#L52
Therefore the tooltips loaded via AJAX are not initialized.

**Comment by beardhatcode** [comment]
This SO post could help:
https://stackoverflow.com/a/10420203
