### ISSUE TITLE
Confusing icons for overdue series

### ISSUE THREAD

**Issue by jay-tux** [dodona-edu/dodona#1711]
Series for which the deadline has been passed, appear with a red clock on the homepage, which is confusing for those who finished said series. Is there an option to replace the red clock with another icon so it's clear that the deadline has passed, but the student has finished the exercise in time.

**Comment by bmesuere** [comment]
This is indeed a good suggestion and has been planned for a while. The reason it isn't implemented yet is that the series status isn't cached at the moment. On the course page it is recalculated from the individual exercises (which are already loaded), but doing that on the home page would be too slow.

**Comment by bmesuere** [comment]
This now depends on #1805
