### ISSUE TITLE
Best way to link between exercise descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1717]
What is the best way to make links between exercise descriptions in Dodona? What seemed to work best was using relative links using the exercise ID of the target exercise description (e.g. `../1410164294/`).

However, since we moved exercise descriptions into iframes, such relative links no longer work, as seen for the first link in [this exercise](https://dodona.ugent.be/nl/courses/65/series/708/exercises/1162710182/).

Is there a way to fix the relative links at the Dodona side (because they now link to medusa instead of Dodona), or should we use direct links to Dodona, as in

https://dodona.ugent.be/exercises/1162710182/

but this would lead us outside the course and outside the series.

**Comment by charvp** [comment]
We already have an issue for this: https://github.com/dodona-edu/dodona/issues/1050.

**Comment by pdawyndt** [comment]
Is there any documentation of this? E.g. do the relative links work, as was suggested in the issue where the solution was proposed?

**Comment by charvp** [comment]
No, the issue is still open, indicating we have not implemented the suggestion yet (it's not that trivial to do so).
