### ISSUE TITLE
Some exercise info pages are not displayed

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1730]
The info page of this exercise is not properly displayed (404):

https://dodona.ugent.be/nl/courses/264/series/2290/exercises/174432505/info/

According to @rien it may have something to do with the character encoding of the files in the `solutions` directory of the exercise

**Comment by rien** [comment]
The error seems to be cause by the `course.formatted_year`: https://github.com/dodona-edu/dodona/blob/7ba125e099cf91adc76d91511074bf36b07cdf65/app/views/exercises/info.html.erb#L205
