### ISSUE TITLE
Right margin when hiding annotations on submitted solutions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1735]
When all lines of a submission with annotation are shorter then the width of the submission view, the right margin has a slightly different color when annotations are hidden. Might be better to always show the code with 100% width.

![image](https://user-images.githubusercontent.com/5736113/75557243-f2226000-5a3f-11ea-82d8-c6c4449be181.png)

Example submission: [4960778](https://dodona.ugent.be/en/submissions/4960778/)

**Comment by MrKickkiller** [comment]
I'm unable to view the example submission (and see what is happening to the css), but it also seems that I can't reproduce this quickly in my browser (with the current version of develop loaded).

![image](https://user-images.githubusercontent.com/5099359/75559345-93f77c00-5a43-11ea-80d1-70c46284f6c2.png)
![image](https://user-images.githubusercontent.com/5099359/75559373-9c4fb700-5a43-11ea-8bf0-82e1d6f84f1e.png)

Also tested this in production
![image](https://user-images.githubusercontent.com/5099359/75559617-0ff1c400-5a44-11ea-8f4d-54791a073f04.png)

So this does look like it could possibly be different browser behaviour. @pdawyndt: Mind if I ask what browser you are using? My screenshots are taken on latest firefox

**Comment by pdawyndt** [comment]
I was indeed using Chrome ...
