### ISSUE TITLE
Cosmetic issues about info page

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1739]
- [ ] contact information is a link, but clicking it has no effect
- [ ] remove dot at the end of the `Created` and `Last edited` fields
- [ ] replace "submission count" by "submitted solutions" (or just solutions"); "Ingediende oplossingen" in Dutch; "Submitted solutions"/"Ingediende oplossingen" is also how this statistic is named on the course page
- [ ] avoid using "here" as an anchor for linking to the documentation; sentence can be rephrased as "See [documentation](url) for information about configuring exercises."
- [ ] link to create about information, creates about page at the wrong location in the GitHub repository; the markdown file is created in the parent directory, while it should at least create it in the exercise directory itself; why do we put the markdown file in the root of the exercise directory, and not in the `description` directory where we also put the descriptions and boilerplate?
- [ ] in the "Usage" table, links to courses open in a new tab, but there seems no reason for it
- [ ] I can't say why, but the icon for the info page in the navigation button does not seem to fit with the other icons surrounding it may it's because it's an open circle, where a filled circle with an inserted letter "i" may look better; or to be more consistent, we could use the same "stats" icon as used for courses
- [ ] statistics tiles are not always properly aranged in a grid (may have something to do with the fact that "Programming language" is split into two lines"

![image](https://user-images.githubusercontent.com/5736113/75604770-abcf0e80-5adc-11ea-9887-55d8d0413334.png)

**Comment by pdawyndt** [comment]
The exercise edit page still contains some static information (bottom) that now appears on the exercise info page, and so it may be removed at this point. The only information missing on the info page is the judge, so that information might be added there.

The info page provides the option to update the "about" information of the exercise, while it seems more logical to provide this option for updating on the edit page of the exercise.

If we have an extra information field to put in the grid of statistics tiles, we no longer have a multiple of three stats to show in the grid. As a solution, we could report separately on the stats of the submitted solutions for the exercise:

- number of submitted solutions (in general and/or in this course)
- number of users that submitted a solution (in general and/or in this course)
- number of users that submitted at least one correct solution (in general and/or in this course)
- number of correct submissions (in general and/or in this course), not needed if we have a pie chart as explained below
- pie chart showing the distribution of statuses of all submitted solutions (in general and/or in this course); this could give an idea about the difficulty of the exercise or the time (number of submissions) it takes to get it correct; we might have an analogue pie chart with aggregated info on the user level (e.g. by looking at the latest submission per user)

**Comment by charvp** [comment]
See #1732.
