### ISSUE TITLE
Purple colored top bar

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1740]
There must be a reason, but why does the top bar of the listing of all exercises with a given label get a purple color?

![image](https://user-images.githubusercontent.com/5736113/75605285-a9bb7e80-5ae1-11ea-9930-05fda5db0930.png)

**Comment by charvp** [comment]
Originally, labels got a random colour similarly to courses. The top bar was set to the label's colour. During review, we decided to give all labels the same colour (at least for now) but this implementation detail remained.
