### ISSUE TITLE
Combine exercise, judge and docker

### ISSUE THREAD

**Issue by rien** [dodona-edu/dodona#1754]
This issue is an extension to #574. I'm making a new issue because that is a migrated issue and our docker ecosystem has changed since then. This issue is the result of @ninewise and me brainstorming during lunchtime.

## Problem

Evaluating compiled languages (e.g. Java) is slow because we need to compile the judge, possible exercise-specific classes, and the submission. This is very noticeable in Java exercises, where it's common to have an evaluation time of 30s or more.

## Proposed solution

The ability to prepare docker image for a judge or even a specific exercise. If this is possible, the only thing that needs to be compiled is the submission.

Technically this would be possible by adding an optional `prepare` script (next to `run`)  to a judge which would prepare the judge for execution. A judge-specific image would then be created by appending this preparation step to the docker image. Similarly we could append exercise specific preparations in order to obtain a docker image specific for that exercise.

## Benefits

The main benefit would be a significant speedup for some exercises. Other benefits would be:
- the ability to have exercise specific dependencies without polluting the base docker image,
- the ability to prepare with network access `pip install my_package`, while disabling  networking for the actual evaluation,
- the ability to generate test data once,
- the ability to download this exercise-specific docker image in order to debug the judge locally.

## Downsides

Making this behavior optional will add some complexity to the evaluation code. But this can be limited. We would only need to pick the docker image dynamically and the rest of the evaluation code can stay the same (even though mounting the exercise working directory and judge would be redundant).

This would also add more complexity to the documentation and to debugging exercises and judges.

If a judge changes, we would not only need to rebuild the judge's docker image, but all the dependent exercise docker images as well.
 
## Technical hurdles

- We would need to have a system to efficiently queue docker builds as delayed jobs in order to limit deploy time.
- Building the exercise or judge docker can fail, rendering the associated exercises to be unusable.
- We would probably want to set up a custom docker hub for this.

----

Is this something we want to put our shoulders on? Or is this not worth the effort and added complexity? Do you see other downsides, benefits, or hurdles?

**Comment by beardhatcode** [comment]
Hmmm, Isn't is possible to put a jar of precompiled classes in the exercise repository. And add a key to `evaluation` that is true is there is such a jar? Or has this been tried already? The JVM will need to be booted anyway.

**Comment by ninewise** [comment]
Is it possible: yes. It is ugly: also yes. We'd have to recompile and add the jar's to the repository for every change we make to the exercise. That's easily forgotten resulting in very hard bugs.

**Comment by bmesuere** [comment]
I think we first should discuss this further before going ahead with it.
