### ISSUE TITLE
Hide image popups with escape key

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1759]
When images in exercise descriptions are clicked, they are displayed in a popup on top of the page. Before the popup could be hidden by clicking the escape key, but this no longer seems the case. At least not in Chrome on Windows.

**Comment by pdawyndt** [comment]
The escape key only works after the popup is explicitly given the focus (e.g. by clicking its caption).

**Comment by thepieterdc** [comment]
I think that the proper solution here would be to change the focus to the `strp-window` element, this should automatically resolve the issue.

Opinions? @charvp @bmesuere

**Comment by charvp** [comment]
Seems like the correct solution to me. @rien might know more, since he did the sandboxing of exercise descriptions.

**Comment by rien** [comment]
Yes, it's possible that the changing of focus was handled by the library we're using. But because we now activate it programmatically, it is possible weird things happen with the focus.
