### ISSUE TITLE
Known issues with user annotations

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1767]
- [x] typescript code should be refactored, eg the creation of the annotation div is in the code twice
- [x] still relatively hard to click the add annotation button. It might help to increase the row height of the code listing with a few pixels
- [x] add timestamp to the user annotation
- [x] the badge of the code tab doesn't include the number of user annotations
- [x] add small info text under the text area mentioning markdown and shift+enter
- [x] move focus to the text area when adding an annotation
- [x] fix copy to clipboard. Do we still need the workaround to exclude annotations now that they can be hidden? We could restore the default behaviour and add a copy button (#1742)
- [x] some kind of overview of annotations (both received and given?) (#1774)

**Comment by beardhatcode** [comment]
Some ideas/sugestions

- There should be some list that list all the feedback you gave.
- maybe a UI hint to say that shift+enter sends? (I noticed it quite quickly, but then the message was already sent)
- the icon for mark as unread is not that clear. Maybe it should not be in a box?
- We need the bootstrap tooltips for the mark as unread and delete notification things
- It would be cool to see a message icon next to a submission checkmark/cross in the status overview

**Comment by pdawyndt** [comment]
- easy way to move manual annotations to another line (drag and drop?)
- manual annotation cannot be copied to the clipboard, so I lost it in an attempt to move an annotation to another line by copy-pasting it

**Comment by ManuDeBuck** [comment]
* I am not sure if students should be provided with the _'user annotations'_-feature, but at the moment I can click the 'add' button. Nevertheless when clicking the _'annotate'_-button nothing happens (except a `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`-error in the console).

**Comment by charvp** [comment]
>     * I am not sure if students should be provided with the _'user annotations'_-feature, but at the moment I can click the 'add' button. Nevertheless when clicking the _'annotate'_-button nothing happens (except a `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`-error in the console).

Students should not be able to see the button. I will fast-track a fix for this.

**Comment by charvp** [comment]
> > I am not sure if students should be provided with the _'user annotations'_-feature, but at the moment I can click the 'add' button. Nevertheless when clicking the _'annotate'_-button nothing happens (except a `SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data`-error in the console).
> 
> Students should not be able to see the button. I will fast-track a fix for this.

This is now fixed. Note that the button was only visible for users who are a course admin in *a* course. Now the button is only shown for submissions in courses where the user is a course admin.

**Comment by pdawyndt** [comment]
Allow more interactive reviews:

- allow students to ask questions about their code by allowing self-annotations (some teachers might also prefer to disable this option for their courses)
- allow replies to annotations (turning them into discussion threads)
- allow course admins to flag student question as answered, so that notification about the question disappears for other course admins

**Comment by pdawyndt** [comment]
Allow more flexible annotations:

- link annotation to sequence of lines (instead of individual line)
- link annotation to multiple segments (e.g. if it applies to multiple sections in the code)

**Comment by charvp** [comment]
Input field doesn't auto-focus when clicking the add annotation button.

**Comment by pdawyndt** [comment]
Input field might need a visual hint that it accepts Markdown (maybe using default value).

**Comment by bmesuere** [comment]
I updated the original post with valid issues mentioned in the comments. Many others are feature requests (or related to notifications) and should be moved to their own issue.

**Comment by rien** [comment]
- [ ] making an annotation for a `line_nr` that doesn't exist (trough the ai), breaks annotations for that exercise (https://dodona.ugent.be/en/submissions/5060927/)
- [ ] retrieving an annotation json gives a policy error

**Comment by MrKickkiller** [comment]
@rien 
> making an annotation for a line_nr that doesn't exist (trough the ai), breaks annotations for that exercise 
That validation was originally present, but removed here for performance constraints.

Suggestion for future: Whenever a submission comes in, store some metadata (eg, #lines) in database.
