### ISSUE TITLE
Colorblind mode

### ISSUE THREAD

**Issue by lars-vc** [dodona-edu/dodona#1773]
Having a colorblind mode for dodona would be really useful for people such as I.
Currently the dark mode is unuseable for me. Here are the black numbers almost invisible. 
Also differentiating the correct (green) color from the incorrect red color in darkmode is really hard too. This can sometimes even be hard in light mode.
![image](https://user-images.githubusercontent.com/57136208/76935603-abfb4680-68f1-11ea-8013-9eb93cec8a6b.png)

**Comment by charvp** [comment]
The black numbers are almost invisible to everyone in your screenshot. When teachers use transparent images in their exercise descriptions, there is very little we can do about this. We thought about applying automatic color inversion. You can find the discussion on that here: https://github.com/dodona-edu/dodona/issues/1397.

As for colourblind mode, we know it's important and that there are a few UI elements that are not clear to our colourblind users. We have talked about implementing it, but unfortunately we don't have the manpower right now to make it a priority. We would welcome contributions.

You could try [this Chrome extension](https://chrome.google.com/webstore/detail/color-enhancer/ipkjmjaledkapilfdigkgfmpekpfnkih) in the meanwhile.

**Comment by pdawyndt** [comment]
Tree nodes have been given a white background in the image of that particular exercise.

**Comment by pdawyndt** [comment]
Scooped by GitHub

![image](https://user-images.githubusercontent.com/5736113/135394741-f1aaa619-1e79-4476-be66-6def0aafdef4.png)

**Comment by jorg-vr** [comment]
If there are specific color blind issues, issues can be made. But we won't support a separate color blind mode for now
