### ISSUE TITLE
Status submission link on member page leads to wrong solution

### ISSUE THREAD

**Issue by ninewise** [dodona-edu/dodona#1775]
While correcting, I tried to open a submission to a series with a deadline through the [members page of this student](https://dodona.ugent.be/nl/courses/271/members/999/). The most recent solution "Correct" link for "Opdracht 1" with a deadline of 2020-02-28 leads to a submission on 2020-02-29, which is very confusing.

**Comment by pdawyndt** [comment]
With the new code review tool, the way to go will be to create a review session. Such a session will have its own deadline, and an overview of the submission-under-review per exercise/user, which will be the latest submission before the deadline by default. So I guess this will resolve your issue, unless everyone agrees that the members should also take deadlines into account.

**Comment by ninewise** [comment]
Just had a similar issue again, this time clicking on the "Correct" link in a series with a deadline (while impersonating).

This would not be resolved with review sessions, since the link is still just plain wrong.
