### ISSUE TITLE
Workdir files not availble in debugger

### ISSUE THREAD

**Issue by pjvolders** [dodona-edu/dodona#1778]
In [this](https://dodona.ugent.be/en/exercises/405940487/) Python exercise, the students have to open and read a file. The files are provided in the `workdir/` directory of the exercise. This approach works perfectly for evaluation but when the debugger is launched, the files are not available:

`FileNotFoundError: [Errno 2] No such file or directory: 'input_0.txt'`

**Comment by charvp** [comment]
I'm afraid the python judge only supports linking files to the debugger in "doctest" mode, not in "output" mode. Because of the way the debugger works, making the entire exercise workdir available to the debugger is infeasible.

**Comment by pdawyndt** [comment]
I'm afraid that's indeed the case, and not something we can fix on short notice. Sorry for that @pjvolders

**Comment by pjvolders** [comment]
Thanks for the prompt reply! I guess I'll have to look into the "doctest" type evaluation...
