### ISSUE TITLE
Exercise info - Invalid contact information

### ISSUE THREAD

**Issue by thepieterdc** [dodona-edu/dodona#1786]
I haven't had the time yet to look into the mechanics of how the creator of an exercise is derived, but the following exercise was created my myself and not by Steven, as indicated on the information page. This might be confusing in case questions arise. 

https://dodona.ugent.be/nl/courses/174/series/2059/exercises/45838667/info/

**Comment by charvp** [comment]
You can edit/add the contact field in your exercise config to override this information. See here: https://github.com/dodona-edu/dodona/pull/1489/files#diff-49548758a4a5dec25c73bebdedf3b1d5R33

If there is no contact field in the exercise config, we select the first repository admin as a best-guess effort.
