### ISSUE TITLE
Questions for course admins

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1788]
Allow students to ask questions to course admins. These questions might be:

1. general questions related to the course
2. questions concerning a particular exercise
3. questions concerning a particular submission
4. questions concerning a particular line/fragment of a submission

We might support different ways to support this, as we also want to allow that course admins answer these questions as easily as possible (e.g. immediately going to the relevant submissions/code fragment).

**Comment by pdawyndt** [comment]
The Flemish Programming Contest uses the [DOM judge](https://www.domjudge.org/) as a submission platform. The platform allows teams to ask questions (called "clarifications") to the jury, and the jury members to address these questions in the following way:

1. team ask questions: either general question or question related to a specific assignment
2. jury is notified when there are unanswered questions
3. jury has dashboard that shows unanswered and answered questions
4. jury member can assign unanswered question to self or other jury member
5. jury member can answer question; either to team that was asking the question or to all teams

Here's the [full documentation](https://www.domjudge.org/snapshot/manual/running.html#clarification-requests)

**Comment by pdawyndt** [comment]
Brecht Willems suggested:

> Als een student op de Dodona Duck klikt bij de feedbackpagina van een verkeerde oefening, krijgt hij een overzicht van de lesgevers (admins in Dodonacursus) en kan hij kiezen aan welke begeleider(s) hij/zij om hulp vraagt **(met selectievakjes (all/none))**. Die begeleider krijgt dan een notificatie via het bel icoon. Klikken brengt de begeleider naar de verkeerde oefening en kan onmiddellijk beginnen met annoteren. **Vanaf er één annotatie is toegevoegd door één begeleider, wordt de notificatie als gelezen gemarkeerd bij alle begeleiders.**

**Comment by pdawyndt** [comment]
Added this to the next release as post evaluation surveys brought up the need for an easy channel where students can ask questions about the assignments. Will serve both upcoming online exams and evaluations, but also online hands-on sessions and homework assignments.

**Comment by bmesuere** [comment]
I'm afraid this is not realistic.

**Comment by pdawyndt** [comment]
Off course, it's unrealistic to include this in the next release. I apologize for not expressing myself properly: "a next release" would have been better than "the next release". Feel free to change its assignment to any future release, but the label "untriaged" for me wasn't a good indication of the importance of this issue in the context of the online education that we'll have to support in the foreseable future.

**Comment by pdawyndt** [comment]
Request by Dominiek Vandewalle: course admins receive email when a new question was asked.

Maybe we should bundle multiple questions in a single digest. We could also allow course admins to switch on/of the option to receive emails upon questions.

**Comment by BTWS2** [comment]
I have some suggestions based on the request of Dominiek Vandewalle:
* When online on Dodona, no e-mails (when not answered in 1? hour, still send an e-mail)
* Option to only receive Dodona e-mails in office hours (similar to https://plato.ea.ugent.be/settings/) or own timeframe

**Comment by bmesuere** [comment]
To be clear, the first version of this will include the following features:
- A student can ask a question based on a submission within a course using the same UI as the manual feedback for course admins
- A question can have the state open/pending/closed
- Course admins have an overview page per course listing all questions. They are split over separate sections: open/pending/closed and the table refreshes automatically every few seconds
- Both the student and all course admins can change the status of a question. Course admins move the state to "pending" when they start answering a question to prevent 2 course admins from answering the same question at the same time.
- There is a red dot in the navigation bar to indicate that there are unanswered questions for that course
- Course admins can disable this feature for their course using the course settings

Not in scope for the first version:
- Answering questions. Course admins can of course use the manual feedback feature to answer questions, but the answer won't be linked to the question. Manual status updates will always be needed if questions are answered outside of Dodona (e.g. in person or over email)
- Sending emails to notify of new questions
- Other question status indicators
