### ISSUE TITLE
Countdown clock

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1808]
Add option to display a countdown clock to courses that displays time to the next deadline in the course. This could help students keep track of time while working on a test. This request is inspired from feedback from students after a recent test.

Back in time we have added this to [Indianio](https://indianio.ugent.be/) after we got emais from students that there was a time difference between their local clock and the master clock on Indianio. Ever after displaying the master clock, we had not a single remark from students anymore.

![image](https://user-images.githubusercontent.com/5736113/78452531-06cfc480-768c-11ea-9aaf-df5c6f45a974.png)

Some possible features:

- add course-level option to switch displaying the clock on/off
- switch between full digital countdown clock and a more minimal progress bar (e.g. only show full clock at start of exam, around multiples of half an hour before the deadline, and five minutes before the deadline; make a sound when the full clock is displayed)
- allow students to hide the clock if it gets on their nerves

**Comment by charvp** [comment]
We already show a countdown on the exercise page (which is what the student was talking about). See #1016.

**Comment by thepieterdc** [comment]
For what it's worth, the plugin for IntelliJ is able to show a list of upcoming deadlines with a stopwatch.

**Comment by charvp** [comment]
The decision was made to not do dynamic updating to avoid distracting users. I personally still stand by that decision.
