### ISSUE TITLE
Enable footnotes in descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1809]
Dodona lacks explicit support for footnotes in descriptions.

**Comment by pdawyndt** [comment]
Here's a [description](https://dodona.ugent.be/nl/courses/293/series/2533/exercises/1807370355/) that uses it.

**Comment by bmesuere** [comment]
This should be supported by kramdown. Did you use the right syntax? https://kramdown.gettalong.org/quickref.html#footnotes

**Comment by charvp** [comment]
Supporting this in HTML is something that (IMO) we really don't want to do. We've had a lot of performance problems related to the parsing of HTML files, doing more of that doesn't seem like a good idea. Especially some kind of LaTeX-like processing as you seem to expect in the description you linked.

**Comment by pdawyndt** [comment]
Thank for the tips. I handcoded the Kramdown-generated HTML, and that worked OK.
