### ISSUE TITLE
Support intra page links in exercise descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1810]
Links to another section within the same description page don't work as expected since the introduction of the iframes. Since there is no reference to the outer page, the links lead to a page only showing the iframe content.

```
<a href="#id-locator">xxx</a>
```

You can see it in action by following the footnote links in [this description](https://dodona.ugent.be/nl/courses/293/series/2535/exercises/1562705175/).

**Comment by beardhatcode** [comment]
Hmmm, setting `target="_self"` does not help. We'll probably need to do some ugly JavaScript thing here

**Comment by pdawyndt** [comment]
The `footnote` class could also use some specific CSS, e.g. draw a horizontal line to separate footnotes from the main body of the description, and give footnote descriptions a smaller font.
