### ISSUE TITLE
Balance top and bottom margin of descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1811]
Description do not have the same top and bottom margin of descriptions. This is especially clear with short descriptions.

![image](https://user-images.githubusercontent.com/5736113/78471205-d8a3c080-772f-11ea-80d0-2e4456d4b423.png)

**Comment by bmesuere** [comment]
The extra top margin was added to avoid overlap with the round edit FAB. Since that button is removed the extra margin can also be removed.
