### ISSUE TITLE
Add next and previous buttons to the exercise page

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1828]
On an exercise page within a series (if the series navigation at the right is active), add a next and previous button to exercise card header. If an exercise is the first or last in a series, replace the useless button with a "return to course".

![image](https://user-images.githubusercontent.com/481872/78594550-d08b7400-7848-11ea-9d87-df4791840314.png)

**Comment by bmesuere** [comment]
> Do we also want to bind this to left and right arrow keys?

No, definitely not :)

**Comment by rien** [comment]
Binding arrow keys (or any key) will cause more harm in accidental usage than it would save time. Changing an exercise is not something that is done a lot.
