### ISSUE TITLE
Download course as PDF

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1833]
Download entire course, with all descriptions of learning activities per series, as a PDF document.

**Comment by beardhatcode** [comment]
I don't feel like this is a job for Dodona. If a teacher would want this, they could make a decent document on their own. If a PDF download is provided, I feel like this should be a currated document. Such a document should be able to link between learning acctivites like being able to back-reference to where lists were introduced, ... . 

Just a `cat` of all descriptions is not a decent document. And I think the website as is is a better interface to interact with the course content on dodona. The website is also much more easliy navrigatable than a PDF.
