### ISSUE TITLE
Exercise statistics

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#1835]
Extracted from #1732.

Suggestions for data to show:
- number of submitted solutions
- number of users that submitted a solution
- number of users that submitted at least one correct solution
- number of correct submissions

Suggestions for visualisations:
- pie chart showing the distribution of statuses of all submitted solutions; this could give an idea about the difficulty of the exercise
- bar chart with the time (number of submissions) it takes to get it correct; we might have an analogue pie chart with aggregated info on the user level (e.g. by looking at the latest submission per user)

These stats could be useful in general and per course.

**Comment by beardhatcode** [comment]
lMaybe the mean amount of attempts to solve an exercise is more useful than the amount of correct submissions. I think giving the mean, of that could be a much more valuable metric to estimate the difficulty of an exercise. It would be interesting to see the difference between the average amount of attempts this year vs the average amount of attempts in the exercises history.
