### ISSUE TITLE
Tables show differently inside and outside centered groups

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1836]
There's a discrepancy between tables shown outside centered groups (full width, no centering)

![image](https://user-images.githubusercontent.com/5736113/78908097-e59f1780-7a81-11ea-8b64-dbb318bcaf68.png)

and inside centered groups (auto width, centering)

![image](https://user-images.githubusercontent.com/5736113/78908168-036c7c80-7a82-11ea-9519-856ac3c5aa42.png)

The same difference is not observed with images. Is this intentional?

Source [description](https://dodona.ugent.be/en/courses/293/series/2538/exercises/862338152/) for images.

**Comment by pdawyndt** [comment]
Also, tables in descriptions could do well with some more spacing below the table.

**Comment by bmesuere** [comment]
By default, tables have a width of 100%. Inside a centered group, this doesn't make sense because then there would be nothing to center.
