### ISSUE TITLE
Additional code review features

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1852]
Some additional code review features related to annotations:

- press escape to cancel editing of an annotation (**DONE**)
- support LaTeX-style formulas in annotations ($...$, $$...$$, \[...\]) #2049
- remove all text should result in removal of the annotation itself (now user is prevented to do some actions)
- separate global annotations that appear above the code from global annotations that appear below the code
- move annotation to another line (drag-and-drop)
- reorder annotations attached to the same line (drag-and-drop)
- show/hide annotations when clicked on the circle in the left margin (always show circles, #2037)
- duplicate annotations on same code (or link multiple sections to the same annotation)
- reuse annotations attached to other submissions (annotations could be scoped, such that one could e.g. easily retrieve previous annotations attached to lines of the same function)
- migrate annotations to next version of code (later submission by same user for same exercise)
- link annotation to sequence of lines (instead of individual line)
- link annotation selection (not necessarily an entire line or a sequence of lines)
- link annotation to multiple selections (e.g. if it applies to multiple sections in the code)
- support simple strikethrough (for a given selection) as a special type of annotation (possibly in combination with some text)
- anonymous annotations (students don't see name of reviewer; e.g. they see a rubber duck instead)
- option to manually hide/show annotations (only for annotations not linked to a review session)
- offline reviewing: local copy of code-under-review, review in editor/IDE, upload annotations
- allow students to ask questions about their code by 
  - asking for a "request review"
  - allowing self-annotations
  - some teachers might also prefer to disable these options for their courses
- allow replies to annotations (turning them into discussion threads)
- like an annotation
  - allow course admins to flag student question as answered, so that notification about the question disappears for other course admins
  - allow students to flag annotation as resolved (either as a reminder to self that an issue has been fixed or to indicate that a reply has been helpful)
- assign submission to course admin/course user for review
- peer review (bulk assignment of submissions to course users for review)
- provide way to quickly go to previous/next annotation (short key)
- editor for formatting annotations in Markdown
  - style as code fragment (in the programming language of the submission) would be a handy feature
- translate annotation to another language (e.g. using the Google Translate API); could be done statically by the reviewernd/or dynamically by the submittor reading the review
- lengthy annotations can be displayed in abbreviated form, with toggle to show more/less (see Google Doc annotations)
- what I like about making annotations in Google Doc is that you can select a code fragment and then add an annotation to it using the short key Ctrl+Alt+M
- track if students have seen all annotations; probably this is functionality that is both needed to show notifications and would also be interesting for course admin to see how many students have actually looked at the feedback
- add annotations to course statistics
  - number of annotations (visible, hidden)
  - number of questions from students (open, in progress, closed)

**Comment by pdawyndt** [comment]
### Notifications

- add annotation > notification; remove annotation > notification is not removed

**Comment by charvp** [comment]
> ### Notifications
> 
>     * add annotation > notification; remove annotation > notification is not removed

This is a known issue that will be fixed in #1777.

**Comment by BTWS2** [comment]
While commenting an GitHub I found that GitHub now has a feature to [comment on multiple lines](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/commenting-on-a-pull-request#adding-line-comments-to-a-pull-request) by dragging the `+`-icon. Similar UX can be used for adding a comment in Dodona.

![image](https://user-images.githubusercontent.com/56451049/92388282-515fdc00-f117-11ea-84ce-19eee544045c.png)
