### ISSUE TITLE
Centered group in Markdown

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1859]
A centered group in Markdown

```markdown
{: .dodona-centered-group}
![madlibs](media/madlibs01.jpg "madlibs"){:width="12%"}
![madlibs](media/madlibs02.png "madlibs"){:width="12%"}
![madlibs](media/madlibs03.jpg "madlibs"){:width="12%"}
![madlibs](media/madlibs04.jpg "madlibs"){:width="12%"}
![madlibs](media/madlibs05.jpg "madlibs"){:width="12%"}
![madlibs](media/madlibs06.png "madlibs"){:width="12%"}
```

should be rendered as

![image](https://user-images.githubusercontent.com/5736113/79718932-922c9500-82dd-11ea-80db-855964223bb0.png)

but is rendered as

![image](https://user-images.githubusercontent.com/5736113/79718949-a375a180-82dd-11ea-9977-145fc7a5fcf5.png)

Example: [Mad Libs](https://dodona.ugent.be/nl/exercises/1043446939/)

**Comment by LucianosLionakis** [comment]
I can't reproduce this bug. When I visit [Mad Libs](https://dodona.ugent.be/nl/exercises/1043446939/) the icons are rendered as suggested by @pdawyndt (tested on chromium and firefox).
![image](https://user-images.githubusercontent.com/48768719/89286148-fc313600-d651-11ea-9198-6a8ffd35be65.png)

**Comment by winniederidder** [comment]
Same holds for Edge (Windows 10), Firefox and Google Chrome, even after resizing.

**Comment by pdawyndt** [comment]
Confirmation that the description has not been altered. The issue also seems to be resolved on all browsers/machines I've tested it. Looks like can be closed.
