### ISSUE TITLE
Edit button broken

### ISSUE THREAD

**Issue by stijndcl** [dodona-edu/dodona#1879]
Clicking the edit button on a submission results in the following error:

![image](https://user-images.githubusercontent.com/60451863/79854863-6935fe00-83ca-11ea-8ff6-03c872d0003c.png)

![image](https://user-images.githubusercontent.com/60451863/79854821-558a9780-83ca-11ea-8931-ee80f1d28779.png)

**Comment by bmesuere** [comment]
Thanks for reporting. I can reproduce this, so we'll hopefully have a fix out soon.

**Comment by bmesuere** [comment]
It fails because `dodona.codeListing.code` is undefined.
