### ISSUE TITLE
Rejudged submissions can cause wrong values in ExerciseStatus model

### ISSUE THREAD

**Issue by charvp** [dodona-edu/dodona#1887]
`ExerciseStatus#update_values` is called for every submission save, but a submission save can also happen for a rejudge, which isn't necessarily the last submission.

**Comment by charvp** [comment]
@thepieterdc Any ideas on how to fix this? The only thing I can think of is just deleting the ExerciseStatus model on submission save, since rejudges make this very tricky. Everything in the ExerciseStatus model will have to be recalculated, but I think that's the case anyway (since, again, rejudges make things very tricky).

**Comment by thepieterdc** [comment]
For updates to series (actually, only when the deadline has been changed), the values are actually removed instead of recalculated. We could simply do the same and defer recalculation
