### ISSUE TITLE
Investigate why a random test sometimes fails

### ISSUE THREAD

**Issue by thepieterdc** [dodona-edu/dodona#1911]
**Findings:**
- The error is always `ActionView::Template::Error: 783: unexpected token at ''`.
- The failing test case appears to be random.
- **Assumption:** The failing test case is probably the first test case that requires asset precompilation

**Examples:**
- https://github.com/dodona-edu/dodona/runs/619738568?check_suite_focus=true
- https://github.com/dodona-edu/dodona/runs/619715150?check_suite_focus=true

https://www.youtube.com/watch?v=TxcDTUMLQJI

**Comment by charvp** [comment]
Haven't seen this in a while.
