### ISSUE TITLE
Use language-specific icons for programming exercises

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#1975]
In a series we could replace the neutral icon for a programming exercise by an icon specific for the programming language used in the exercise. There seem to be [material design icons](https://materialdesignicons.com/) for most of the popular programming languages.

An exam series that mixes Python and JavaScript exercises now looks like this

![image](https://user-images.githubusercontent.com/5736113/81150135-b516a480-8f7f-11ea-9fb5-ed0a61e7bfa7.png)

but could then look something like

![image](https://user-images.githubusercontent.com/5736113/81150097-a6c88880-8f7f-11ea-9d65-83567b206e63.png)

In case we later move to programming exercises that support multiple programming languages, we may then switch to showing the programming language of the latest submission, maybe still in combination with an icon for the exercise (e.g. related to the judge linked to the exercise).

![image](https://user-images.githubusercontent.com/5736113/81150709-8ea53900-8f80-11ea-9bba-a9670c6b51d9.png)

**Comment by charvp** [comment]
Not possible for the programming languages Dodona currently has: prolog, for example, does not have an icon in the material design icons set.

**Comment by pdawyndt** [comment]
[Does prolog have an official logo](https://github.com/exercism/meta/issues/67)? There are many flavors of prolog, some with official/unofficial logos. I guess the owl from the material design icons might do?
