### ISSUE TITLE
Add functionality to restart workers without deploy

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1977]
- Fix the UFW rule: There was an issue with a UFW rule related to docker. This caused the UFW setup to fail which in turn caused all outgoing network traffic to be blocked. Booting was then stuck on trying to mount the dodona nfs
- Check if we can set a timeout for mounting while booting. If dodona.ugent.be would be down, we can't reboot the workers (even if UFW would work)
- Next summer when we update the servers, install docker on the webserver. This way, we could start 1 or 2 workers there to evaluate submissions in case of emergency.
- Check if we can restart the workers without having to do a deploy

**Comment by charvp** [comment]
> Fix the UFW rule: There was an issue with a UFW rule related to docker. This caused the UFW setup to fail which in turn caused all outgoing network traffic to be blocked. Booting was then stuck on trying to mount the dodona nfs

I think the solution here is to make the ufw service depend on the docker service.

> Check if we can set a timeout for mounting while booting. If dodona.ugent.be would be down, we can't reboot the workers (even if UFW would work)

Adding `x-systemd.mount-timeout=60s` to the options in fstab should work.

> Next summer when we update the servers, install docker on the webserver. This way, we could start 1 or 2 workers there to evaluate submissions in case of emergency.

Agreed.

> Check if we can restart the workers without having to do a deploy

`cap production delayed_job:restart`

```
cap delayed_job:default            # Default task - conditionally restart
cap delayed_job:restart            # Restart the delayed_job process
cap delayed_job:start              # Start the delayed_job process
cap delayed_job:status             # Status of the delayed_job process
cap delayed_job:stop               # Stop the delayed_job process
```

**Comment by rien** [comment]
I think it would also make sense to have an emergency or maintenance mode which disables/minimizes database and filesystem writes and shows a notification to the users that we're experiencing some issues.

**Comment by rien** [comment]
About fixing the UFW rule: `DOCKER-USER` is an optional iptables rule chain which the user can create themselves if they want to add specific rules before those of docker. So adding dependencies won't solve the issue. The rule should only be flushed if it exists, but I'm looking at what the right way is to handle this.

**Comment by charvp** [comment]
Only "Check if we can restart the workers without having to do a deploy" is still relevant here.
