### ISSUE TITLE
Summer system upgrade

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#1990]
During summer, we will once again upgrade our servers. We will schedule 1 day of downtime for this. This issue gathers all information and a todo list.

## Before
- check with dict if we can use snapshots in VMware to roll back in case anything goes wrong

## After the exams
- [x] upgrade the workers one by one to Ubuntu 20.04
- [x] upgrade phocus to 20.04
- [x] upgrade pandora to 20.04
- [x] upgrade naos to 20.04
  - [x] pay special attention to the database upgrade from MySQL 5 to 8
- [x] upgrade the database tables on naos to utf8mb4 (#1961)

## During downtime day
- [x] upgrade elysium
  - pay attention to MySQL replica
- [x] upgrade lethe
  - pay attention to MySQL replica
- [x] upgrade dodona
- [x] install docker on dodona
- [x] make the underlying fs of the nfs mount on dodona read only

**Comment by bmesuere** [comment]
We should also figure out what to do with ruby 2.7

**Comment by rien** [comment]
- The Ubuntu 20.04 upgrade was rolled out on July 13, 14 and 15, with less than one hour of downtime on July 15 13:00.
- Docker was installed on dodona.ugent.be
