### ISSUE TITLE
Multiple shift+enter clicks repeats same annotation

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2031]
Quickly clicking shift+enter multiple times in succession, add the same annotation multiple times.

![image](https://user-images.githubusercontent.com/5736113/83624738-4a16b880-a593-11ea-8bc3-d54bbae54474.png)

**Comment by pdawyndt** [comment]
Question: why have we chose shift+enter. Both Google Docs and GitHub use control+enter.

**Comment by bmesuere** [comment]
> Question: why have we chose shift+enter. Both Google Docs and GitHub use control+enter to save a remark/comment.

slack, facebook messenger, google hangouts, ms teams and many others use the shift modifier. crtl+enter is "harder" because that would be OS specific: on a mac it would be cmd+enter instead of ctrl.

**Comment by pdawyndt** [comment]
@bmesuere OK, thanks for the update. I already got used to the shift+enter and if other platforms use it, then it's fine for me.
