### ISSUE TITLE
Unable to navigate to next feedback

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2034]
Even though there are still evaluations to be done, at some point I was unable to move to the next evaluation.

![image](https://user-images.githubusercontent.com/5736113/83630818-bf3abb80-a59c-11ea-9a61-e90c7b677213.png)

Changing the settings "automatically mark as completed" or "skip completed submissions" did not have an effect on this. Neither dit marking the evaluation as done.

**Comment by pdawyndt** [comment]
Also note that the "next" button is not translated in Engelish.

**Comment by charvp** [comment]
This is working as expected. The feedback objects are created in random order and the next button is disabled for the last feedback object.

**Comment by pdawyndt** [comment]
I started the evaluation with the first student in the overview (so probably halfway down the random order). My expected behaviour would be that you can always go to a next submission if there's still one left that meets the criteria. Maybe running round robin through the random order could be an option here.

**Comment by bmesuere** [comment]
We should probably cycle through everything so that it's only disabled when there aren't any unchecked left.
