### ISSUE TITLE
Show specific code-annotation when annotations are minimized

### ISSUE THREAD

**Issue by stijndcl** [dodona-edu/dodona#2037]
Currently, when code-annotations are minimized, Dodona shows a small dot next to lines that have one. It could be a useful feature to be able to click on these dots to show that specific annotation.

![image](https://user-images.githubusercontent.com/60451863/83775352-1c12a080-a687-11ea-967e-86b2276c8b14.png)

**Comment by pdawyndt** [comment]
Show dots only when "minimized" or always show dots (with functionality to manually show/hide corresponding annotations) and treat buttons on top as show all/show some/hide all?

**Comment by pdawyndt** [comment]
I was just furthering on your line of tought ...

**Comment by bmesuere** [comment]
This has been fixed with #4568. Hovering over the squiggly line shows the full annotation.
