### ISSUE TITLE
Add button to edit code and resubmit from evaluation

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2054]
When evaluating submitted solutions, there's no option to directly edit and resubmit a solution, as is the case from the submission page itself.

**Comment by pdawyndt** [comment]
In this context the result of editing and resubmitting the solution shouldn't probably even be stored in the database as a solution of the evaluator, as the evaluator doesn't want to submit the solution as his own. So it should be either stored as a "corrected version" attached to the submission under evaluation or not stored at all.

**Comment by bmesuere** [comment]
Reuse the available feature to submit an example solution. Should open in a new tab.
