### ISSUE TITLE
Reduce steps for creating an API token

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2095]
Is it possible to reduce the steps for creating an API token? PyCharm adds a lot of useful functionality and I would like to make the configuration process easier for young students.

Suggestions:

* https://dodona.ugent.be/nl/users/me/ redirects to logged in user (`me` is replaced by the user id).
* https://dodona.ugent.be/nl/users/me/edit/ redirects to page to create an API token.

### Use case:

Manual with only two easy steps.

**Step 1:**

Go to https://dodona.ugent.be/nl/users/me/edit/#API/?token=Dodona_Plugin_API_token and click on the orange button with a white plus sign.

* Jumps to the header **API tokens** and populates description textfield with `Dodona_Plugin_API_token` based on the link in the manual. This link redirects to https://dodona.ugent.be/nl/users/4307/edit/#API/ for example. (If the user isn't logged in, the user should be redirected to that page when login succeeded.)

* In case of an **error**:
  * Is it possible to add suggestions for possible solutions to the error message? Several students asked me what to do when they followed the same steps in the manual twice.
    *Beschrijving is al in gebruik* -> *Beschrijving is al in gebruik. Verwijder de oorspronkelijke API token of kies een andere beschrijving voor de API token.*
    *Description has already been taken* -> *Description has already been taken. Delete the original API token or choose another description for the API token*.
  * Can the text input field border for the description be changed to red, when an error occurred, to indicate what the user needs to change?

**Step 2:**
Copy and paste token.

**Comment by thepieterdc** [comment]
Also keep in mind that there are other plugins, beside the PyCharm plugin (e.g. https://github.com/thepieterdc/dodona-plugin-vscode) ; so the documentation should not focus on PyCharm too much.

Possible suggestion for duplicates: If the description already exists, maybe we can automatically add a numeric suffix.

**Example:**
- `My API Token`
- `My API Token #2`
- `My API Token #3`

**Comment by BTWS2** [comment]
I didn't know there already was a plugin for VS Code! Many thanks!

For the use case I had the manual of the teacher in mind, not the general manual on the official Dodona docs. Several students asked me if the description mattered, if they made a typo for example. If the teacher adds this link for example [https://dodona.ugent.be/nl/users/me/edit/#API/?token=Dodona_Plugin_API_token](https://dodona.ugent.be/nl/users/me/edit/#API/?token=Dodona_Plugin_API_token), there are less possible points of failure.
