### ISSUE TITLE
Can't login with OAuth2

### ISSUE THREAD

**Issue by nicoekkart** [dodona-edu/dodona#2133]
Logging in with ugent CAS on dodona.ugent.be gives the error: 

```
Ter info: Kan je niet aanmelden met OAuth2, reden: "een onbekende fout is opgetreden".". 
```

CAS works on other platforms of UGent, so doesn't seem to be a problem with this.

**Comment by bmesuere** [comment]
Should be fixed now. There was a UGent certificate change at noon which we had to update on Dodona.
Can you confirm it works for you?

**Comment by nicoekkart** [comment]
Jup, seems to work. Thanks!
