### ISSUE TITLE
Rename public folder to media in repositories

### ISSUE THREAD

**Issue by winniederidder** [dodona-edu/dodona#2147]
Part of #2145 but these folders (if they were used) can only be renamed when going in production

**Comment by pdawyndt** [comment]
For completeness: [original issue](https://github.com/dodona-edu/dodona/issues/524) about sharing files between exercises and the [pull request](https://github.com/dodona-edu/dodona/pull/583) with its implementation. Original proposal was to name the directory in the root directory of the repo `media`, in analogy with the name in the exercise `description` directories.

**Comment by bmesuere** [comment]
done by @rien
