### ISSUE TITLE
Sign in page rework

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#2162]
The sign in page should be reworked as follows:
- top section with high education institutions should stay the same
- middle section with smartschool/office/g suite should stay the same
- bottom section with secondary schools should be removed (also remove the images from the repo)
- The new bottom section should be 
  - a large, centered, auto-complete select with all schools
    - only include schools with smartschool/office/gsuite as primary provider
  - next to the select, there should be a big sign in button that redirects to the providers of the selected institution
  - the selected institution should be stored in local storage
  - if there is an institution in local storage (from a previous sign in), make it the selected institution on auto complete

**Comment by BTWS2** [comment]
Is it possible to display the Dutch version of the Ghent University logo (first button top left) when visiting https://dodona.ugent.be/nl/sign_in/ (and the English version of the logo when visiting https://dodona.ugent.be/en/sign_in/)?

You can find the logos here (NL and EN): https://styleguide.ugent.be/basisprincipes/logos-en-facultaire-iconen.html#corporate-logo
