### ISSUE TITLE
HTML5 video tag does not support skipping forward/backward

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2184]
Video fragments embedded using the HTML5 tag `video` cannot be skipped forward nor backward.

Example: [exercise description](https://dodona.ugent.be/nl/courses/172/series/3251/activities/357352739/)

OS: Mac OS X
Browser: Google Chrome
Observed by: @toonijn @pverscha

**Comment by pverscha** [comment]
The issue also occurs on Linux distributions.

**Comment by bmesuere** [comment]
Chrome uses "partial content requests" when skipping. The server must support this skipping to work. Since we simply serve the file, this does not work.

**Comment by bmesuere** [comment]
To support this on Dodona, we would have to manually parse the range headers and return a subsection of video files using the status code 206. Since I don't think we want to do video processing on our server, the best workaround is to use unlisted youtube videos.

**Comment by bmesuere** [comment]
It might be possible by changing the way we serve the file: https://github.com/accentor/api/blob/develop/app/controllers/tracks_controller.rb#L90

**Comment by winniederidder** [comment]
This link is not usable by summer interns. Can you provide a public example for us to test?

**Comment by pdawyndt** [comment]
https://dodona.ugent.be/nl/courses/172/series/1694/activities/2033201011/
