### ISSUE TITLE
Inconsistent series navigation for course admins

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2217]
As a course admin, clicking the name of a hidden series in the navigation bar has a different behaviour between different pages:

- on the page of an exercise in the series, you are navigated back to the course page (e.g. https://dodona.ugent.be/en/courses/172/#series-3251-exam-group-5-examen-groep-5)
- on the page of the evaluation of the series, you are navigated to a page only showing the series (e.g. https://dodona.ugent.be/en/series/3251/)

This should be made more consistent. Behaviour of first case seems the preferable one.

**Comment by bmesuere** [comment]
This is consistent with the behavior for students. They don't have hidden series on the course page, so we must redirect them to the series page.

**Comment by pdawyndt** [comment]
Sure, but then why are staff members redirected to the course page in the first case (exercises are seen by both students and course admins) and not in the second case (evaluations are never seen by students). So apparently in the first case we do already make a distinction between students and course admins. Definitely would seem logical to do the same thing in the second case as well (which is a navigation path that is only taken by course admins).

**Comment by chvp** [comment]
Series link on evaluation should point to course page.
