### ISSUE TITLE
Series status not updated after deadline removal

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2218]
This is the view I got after removing the deadline of a series. The status of the series has not been updated. Before the deadline there was one exercise where I had an incorrect solution before the deadline, and a correct solution after the deadline. After the deadline was remove, the status of the exercise itself was updated, but not the status of the series (or updated incorrectly (*)).

![image](https://user-images.githubusercontent.com/5736113/92299774-ca173a80-ef55-11ea-9810-b9ca93969110.png)

(*) If I recall well, the status before removing the deadline was actually showing a clock as an indication that the deadline was missed.

**Comment by bmesuere** [comment]
This is probably a result of #2079 although it might not seem like it.

The status you see actually is "updated", but unfortunately it is updated to the old stored version from when before the deadline was set. For normal users who never saw this series before without a deadline, it should recalculate.
