### ISSUE TITLE
Link to the manual where possible

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2229]
We should take a look at the manual pages we have an think where on Dodona we could link to those pages.
For example: every markdown text area should have a link to the markdown docs.

**Comment by bmesuere** [comment]
We'll first extend and improve the quality of the manual before making it more public ;)

**Comment by BTWS2** [comment]
@bmesuere What do you want to see added or changed in the docs?

**Comment by bmesuere** [comment]
Reviewing a series is just the basic version now, translations for some pages must be added (but not before @pdawyndt reviewed the Dutch version), existing judge docs should be added (r, java), the organization of the pages can be improved, the release notes for the last few versions are missing, ...

**Comment by BTWS2** [comment]
I would wait to update the docs about reviewing a series until the new update is released.

If users use the docs more and ask questions about parts that are not clearly explained, I can update the docs. You can forward such questions to me, if you want.

**Comment by BramDevlaminck** [comment]
Are there certain links between Dodona itself and the documentation that are clearly missing that I should focus on?
