### ISSUE TITLE
Consistent colored course cards 

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2240]
Course cards now have a color in the overview:
![image](https://user-images.githubusercontent.com/56451049/92699187-8fdedc00-f34d-11ea-848a-eeb672c849e5.png)

The course itself doesn't have that color and are blue:
![image](https://user-images.githubusercontent.com/56451049/92699327-bb61c680-f34d-11ea-91f8-54b6e6655d2b.png)

My suggestion would be to use the **same color as in the overview** to be consistent. This helps to tell the difference between different courses and the same course of a different academic year.
![image](https://user-images.githubusercontent.com/56451049/92699558-07147000-f34e-11ea-91c0-69f3d8170799.png)

When creating a new course a random color of the color palette is assigned, but teachers would be able to change the color in the settings: https://dodona.ugent.be/en/courses/???/edit/

**Comment by chvp** [comment]
Making the color configurable might be part of #2760.
