### ISSUE TITLE
Title of questions page should be updated with the number of open questions

### ISSUE THREAD

**Issue by charvp** [dodona-edu/dodona#2275]

**Comment by niknetniko** [comment]
I currently was thinking about something like this:

![image](https://user-images.githubusercontent.com/1756811/94153076-a07a7080-fe7c-11ea-9420-1cd2ea7aa23e.png)

One potential "problem" I've noticed is that the number is the first thing to be hidden when the tab width decreases. Other websites (github, gmail, google, facebook) seem to reverse the title order (resulting in "Vragen (3) - Dodona"). This would be a potential solution

**Comment by pdawyndt** [comment]
Twitter also changes the icon (red dot in bottom right corner). Is that also an option?
