### ISSUE TITLE
Alternative selection of recent exercises

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2279]
The selection of recent exercises on the home page seems to be based on the first time you made a submission for these exercises. As a result, exercises you have been working on before, and recently started working on again, will not appear in the list. Therefore, I would make the selection based on the latest submission for the exercises.

**Comment by charvp** [comment]
Can you give a link to a user profile where you've noticed this? It should work the way you propose it to work.

**Comment by pdawyndt** [comment]
Mine. Last submissions I made were “Sum of two integers” (as a demo in class) and the exercises of the first series in the Python programming course. None of these appear in my list of recent exercises, except for the exercise “Dogarithmic scale”, which is a brand new exercise.

**Comment by charvp** [comment]
Initial investigation makes me think this is a regression due to the database update from the beginning of summer. My hunch is that in the following query, the `distinct` is not done with the `ORDER BY submissions.id DESC` in mind.
```sql
SELECT distinct exercise_id FROM `submissions` WHERE `submissions`.`user_id` = 3 ORDER BY `submissions`.`id` DESC LIMIT 5
```
