### ISSUE TITLE
Wrong indication who answered the question

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2324]
The person that answered a question now appears in the dashboard. Elas, this is not always the correct person (most of the time it's the student who asked the question):

![image](https://user-images.githubusercontent.com/5736113/95350226-3a500d80-08c0-11eb-845e-64018fbc2859.png)

First line in the "answered questions" section is a question/answer where I have never been involved in the process.

Second line in the "answered questions" is actually a question that was answered by myself:

![image](https://user-images.githubusercontent.com/5736113/95350413-6a97ac00-08c0-11eb-806c-07f59aa92766.png)

**Comment by niknetniko** [comment]
This should only happen with existing questions: the name is actually the person who last edited the question; and before this deploy this wasn't tracked, so it uses the person who created the question as a fallback.
