### ISSUE TITLE
Remember scoresheet settings

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2356]
The scoresheet view provides the option to swith to another series using a dropdown. However, when switching to another series, the option to only show users that started at least one learning activity is not retained. It would give a better user experience to do so. 

Also, when activating/deactivating the option to "only show users that started at least one learning activity", the popup menu does not disappear until you explicitly click outside the menu.

**Comment by BTWS2** [comment]
The same is true for filtering with a label. When choosing another option from the dropdown, the label is removed.
