### ISSUE TITLE
Crash for question on submission without exercise

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#2364]
If an exercise is converted to a reading activity, the submissions lose their exercise. Question-related code currently assumes all submissions have an exercise.

**Comment by niknetniko** [comment]
After changing an exercise to a content page, the data in the database is kept. I.e. `exercise_id` is still correct in the `submission` table.

However, when using the `exercise` accessor on a submission, rails searches for the exercise like this: `SELECT activities.* FROM activities WHERE activities.type = 'Exercise' AND activities.id = 1041637989`. Since the exercise now has `type = ContentPage`, it is no longer found, resulting in `nil`. This issue does not only affect questions, but also seems to affect other pages where submissions are shown as well.

I see four possible solutions:
1. Delete the submissions when changing the type of an exercise. This has minimal impact on existing code, but does remove submissions from the user.
2. Change `exercise_id` to `activity_id` on the submission and manually force the activity to the `Exercise` type when needed. The impact is also fairly minimal, but it seems like a very brittle solution, since this assumes the exercise data is kept when changing an exercise to a content page.
3. Modify the code to account for `nil` exercise on a submission. This is fairly intrusive, since it is used in a lot of places, and it doesn't "solve" the issue that the database still contains the outdated information. This has been done for the home page already in #1931.
4. Clone the exercise on type change, and modify existing submissions to use the cloned exercise. E.g. if exercise A changes to a content page, we clone A to B, change all submission on A to point to B. The cloned exercise would be the same as if we deleted the exercise. This also has minimal impact on the code base.

To me, the last option seems the "cleanest". Additionally, it provides a place to handle #1962. One downside is that it is impossible to restore an activity if you accidentally change the type. E.g. if you change exercise A to a content page and back, there will be no submissions for exercise A, since those will now be linked to the clone, e.g. exercise B.

**Comment by charvp** [comment]
The problem with option 4 is that if the conversion is reversed the submissions are not linked to the original exercise anymore. I don't really have a better solution right now, but it seems like an important downside.

**Comment by niknetniko** [comment]
> The problem with option 4 is that if the conversion is reversed the submissions are not linked to the original exercise anymore. I don't really have a better solution right now, but it seems like an important downside.

We can perhaps save the "cloned" exercise in the reading activity, and re-link the submissions to the original when the conversion is reversed (if this is something that happens enough to not just ignore it). This doesn't seem very clean, but unsure if there is a better solution.

If we don't want option 4, I would go with a combination of option 2 & 3: change the column to `activity_id` and use as an activity wherever possible, but make the code that requires exercise-specific things nil-proof.

**Comment by charvp** [comment]
I think that last option is the most sensible, sadly.

**Comment by bmesuere** [comment]
Since the chosen option had a lot of code changes, we decided to go for option 4 instead.
