### ISSUE TITLE
Put submission/exercise in Evaluation mode

### ISSUE THREAD

**Issue by fgailly** [dodona-edu/dodona#2377]
When using Dodona in the context of evaluation an instructor might want to add additional tests. The outcome of these additional tests should not be visible to students during the evaluation phase. This would mean that the submission is in evaluation mode. After the evaluation of all submissions for an exercise, the instructor can decide to switch off the evaluation mode and the student can now see the results of the additional tests as feedback.

**Comment by chvp** [comment]
This is a quite complex feature that gives only minimal benefits. You can already get quite close to this when using the permission field of tabs (although no judge supports this currently, unfortunately - if you want this, you can make an issue on the judge repository). When the students should be allowed to see the extra feedback, you can then change the exercise and rejudge the submissions.
