### ISSUE TITLE
Cannot zoom images

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2403]
I'm regularly getting this JavaScript error when attempting to displaying zoomed versions images:

![image](https://user-images.githubusercontent.com/5736113/100547583-dfa3b400-3267-11eb-8274-01ee1345dea3.png)

Example exercise [grille](https://dodona.ugent.be/en/courses/359/series/3494/activities/1266932937/): 

1. clicking the first two images works fine
2. clicking any image after the second image fails

**Comment by niknetniko** [comment]
This happens when there is math in the image caption, but not sure yet why MathJax breaks.
