### ISSUE TITLE
Missing highlighting of numbers in light mode

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2411]
The `class="mi"` causes numbers in code blocks to be highlighted in dark mode

![image](https://user-images.githubusercontent.com/5736113/100880062-96907180-34ac-11eb-8aaf-aea14afbf95e.png)

but not in light mode

![image](https://user-images.githubusercontent.com/5736113/100880100-a14b0680-34ac-11eb-87fd-17399904dae1.png)

**Comment by TimonDB** [comment]
At the moment, numbers in light mode are grey (#666666). Would it be best to change this to the same colour as dark mode (purple, #bd93f9) or would it be better to use another colour?

Currently:
![Screenshot from 2021-08-02 16-40-07](https://user-images.githubusercontent.com/53220653/127879241-ca135fae-9cf6-4250-a3ac-948a728c45e5.png)

In purple:
![Screenshot from 2021-08-02 16-39-33](https://user-images.githubusercontent.com/53220653/127879298-aa51592d-1760-4e17-8c94-bf96558ac31d.png)

**Comment by bmesuere** [comment]
If they are currently gray as shown in the top screenshot, this is an invalid issue and can be closed.

**Comment by TimonDB** [comment]
They are indeed grey, the `class=mi` uses this colour for highlighting numbers in light mode. I will close this issue in that case.
