### ISSUE TITLE
Use alternative background color for line highlighting in dark mode

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2412]
The yellow background color that is used for line highlighting makes the actual code hard to read in dark mode:

![image](https://user-images.githubusercontent.com/5736113/101066924-31fe1100-3597-11eb-9c18-c16b2e6f1d33.png)

This is not the case in light mode:

![image](https://user-images.githubusercontent.com/5736113/101066990-4510e100-3597-11eb-8181-baaad57663bf.png)

Example: [submission 6623077](https://dodona.ugent.be/en/submissions/6623077/)

**Comment by TimonDB** [comment]
Is there a way to reproduce this issue? I don't see how I can highlight a line of code

**Comment by chvp** [comment]
You need to produce a runtime error in some Python code. The judge will output a link to the line where the error occurred.

**Comment by BTWS2** [comment]
@TimonDB, a line of code is highlighted in case of a Runtime error. Examples can be found [here](https://dodona.ugent.be/en/submissions/?status=runtime%20error&page=1).
Click on `<code>, line {??}` and go to the code tab. If I recall correctly Dodona switched to the code tab automatically in the past. Is this true @chvp?
![image](https://user-images.githubusercontent.com/56451049/127991365-14808ebf-fb38-4238-9492-ccf0e5ec4f57.png)
![image](https://user-images.githubusercontent.com/56451049/127991402-efa1b094-c238-4b1a-8e4d-d5fc6fa6933b.png)

**Comment by TimonDB** [comment]
Oke thanks! I am now able to see the marked code lines
