### ISSUE TITLE
Wrong number of incorrect testcases

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2414]
See [this issue](https://github.com/dodona-edu/universal-judge/issues/113) observed for TESTed. Is this due to the default behaviour in Dodona? Is this default behaviour (count both wrong contexts and wrong testcases) as expected?

**Comment by ninewise** [comment]
The partial result constructor (should) count the number of unaccepted testcases (see https://github.com/dodona-edu/dodona/blob/develop/app/runners/result_constructor.rb#L150) and reports this count if it's not overwritten by the enclosing tab.

**Comment by chvp** [comment]
Looking at the submissions for that exercise, it seems that the judge adds an extra testcase per not-executed testcase. This inflates the numbers, but is a judge problem, not a Dodona problem.
