### ISSUE TITLE
Extend in-page navigation on exercise page

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2437]
We now use the right margin for between-page navigation (series exercise) or in-page navigation (course page). On an exercise page we already used for in-page navigation (`Hand-in`), but this might be extended:

1. link both to the description and editor (might help to navigate to the top of the page when on the editor)
2. include (sub)titles in the description, as we also do in the manual (or as seen in other tutorials); this might help navigating in "reading activities"

![image](https://user-images.githubusercontent.com/5736113/102991470-8b63bb00-4519-11eb-9fc0-39abaff3711f.png)

**Comment by niknetniko** [comment]
Relevant for the second item is https://github.com/dodona-edu/dodona/issues/2194.
