### ISSUE TITLE
Remove difference in background color for code blocks in annotations

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2454]
Code blocks in annotations have a difference in background color, depending on the fact whether or not a programming language appears after the three back-ticks:

Specific background when there is a programming language after the three back-ticks:

![image](https://user-images.githubusercontent.com/5736113/104120304-158f8a00-5336-11eb-8ab0-eb5b51b29411.png)

No specific background when there isn't a programming language after the three back-ticks:

![image](https://user-images.githubusercontent.com/5736113/104120293-f85abb80-5335-11eb-9740-f1fc0bdbe408.png)

I would recommend to always use a specific background color.

**Comment by TimonDB** [comment]
How do you write code blocks in annotations? (with and without programming language)

**Comment by chvp** [comment]
It's Markdown, so a line with `\`\`\``  marks the beginning and ending. To specify a programming language you put the name of the programming language after the starting backticks.

**Comment by BTWS2** [comment]
@TimonDB You can find the docs [here](https://docs.dodona.be/en/references/exercise-description/#syntax-highlighting).
