### ISSUE TITLE
Dark mode should have a darker background color for .list-group-item

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2485]
Dark mode should have a darker background color for `.list-group-item`

![image](https://user-images.githubusercontent.com/5736113/106474886-a543d680-64a5-11eb-8c5e-093520a2c47b.png)

**Comment by chvp** [comment]
This is broken again since the bootstrap 5 update.

**Comment by TimonDB** [comment]
Is there a way to reproduce this bug? It seems like this is not possible at the moment using the 3 development accounts (zeus, staff, student)

**Comment by BTWS2** [comment]
@TimonDB, yes, go to https://dodona.ugent.be/nl/courses/453/ and click on "vorige jaargangen" in the introduction.
