### ISSUE TITLE
Allow export of submissions used by an evaluation

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#2503]
#2462 adds a basic export. However, it might be nice to provide a unified evaluation export that (can) include both the grades and the submissions itself.

**Comment by jorg-vr** [comment]
For now we don't see a usecase of adding the scores to the submission export.
Exporting scores and exporting submissions are separate issues, and can be handled with the current implementation.

**Comment by chvp** [comment]
For me this is not only about exporting the grades, but also being to export the exact submissions used by the evaluation. (Which is not necessarily the same as the series export, given that BSTs exist.)

**Comment by jorg-vr** [comment]
Okay then I misinterpreted the issue. I will reopen it

Could you specify the usecase, when and why you would use this?
This will help me determine the best course of action

**Comment by chvp** [comment]
The use case is mostly for plagiarism detection.

**Comment by jorg-vr** [comment]
Ok then it can be taken up when working on https://github.com/dodona-edu/dodona/issues/5338

**Comment by jorg-vr** [comment]
finished in https://github.com/dodona-edu/dodona/pull/5534
