### ISSUE TITLE
Improve user selection in evaluations

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#2516]
For user selection, the material design spec favors using checkboxes instead of buttons for selection. Selected rows should also have a slight background color:
![image](https://user-images.githubusercontent.com/481872/109280335-3004c080-781b-11eb-8fae-9b33fabc594b.png)
vs
![image](https://user-images.githubusercontent.com/481872/109280363-398e2880-781b-11eb-9441-c58e6291f67c.png)
In addition, clicking the add or remove button reloads the entire table which I think is not necessary. It also breaks the flow when adding or removing someone that is not on the first page.

_Originally posted by @bmesuere in https://github.com/dodona-edu/dodona/issues/2462#issuecomment-786515640_ (and extracted into another issue, since the PR is big enough already).

**Comment by BTWS2** [comment]
@niknetniko, is it possible to select all students with a certain label at once?
