### ISSUE TITLE
Use stepper component in evaluation wizard

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#2525]
![image](https://user-images.githubusercontent.com/481872/109142548-49483700-775f-11eb-8b5d-a73c2b003ac6.png)

This is the first screen a user gets when starting an evaluation and this might be optimized a bit. A user has to set a deadline here and indicate if he wants to enable grades. The rest is just extra information (eg, the series overview) but this isn't super clear.

- include something about grades in the info box
- make it clearer that the user has to pick a deadline and can enable grades. Some ideas which may or may not work:
  - slightly change the wording, eg Deadline -> Pick a deadline
  - add a "Settings" header to separate the top part of the page from the bottom part
- Add some text to the top of the series overview that makes it clear that the listing of exercises is just informational 
- Maybe also tweak the card title to make it more clear that we started some sort of wizard, eg "Configuring a series evaluation"

_Originally posted by @bmesuere in https://github.com/dodona-edu/dodona/issues/2462#issuecomment-785808920_

_The score-related options have been removed from this page, but we can still check if we can apply some of the other suggestions_.

**Comment by bmesuere** [comment]
I really like the stepper we now use to add the score items, so I think it makes sense to also include the deadline and user selection as steps to this UI.
