### ISSUE TITLE
Can not initialise development database due to missing remote for Python judge

### ISSUE THREAD

**Issue by nvgeele** [dodona-edu/dodona#2593]
I am trying to set up a local Dodona environment for development, but I cannot seed the database.

```
~/Projects/dodona ‹develop*› » rails --trace db:reset
** Invoke db:reset (first_time)
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
...
Create & clone judge
Create & clone activity repository
Add series, content pages, exercises, read states and submissions to courses
rails aborted!
NoMethodError: undefined method `name' for nil:NilClass
/Users/nvgeele/Projects/dodona/db/seeds.rb:231:in `block (4 levels) in <main>'
/Users/nvgeele/Projects/dodona/db/seeds.rb:216:in `each'
...
```

The relevant line in `db/seeds.rb` is the following:
```result: File.read(Rails.root.join('db', 'results', "#{exercise.judge.name}-result.json"))```

I suspected `exercise.judge` to be `nil` instead of the previously created Python judge. And indeed, it was missing from the database. After manually trying to create the Python judge in the Rails console I can conclude that this is indeed the issue, and it is caused by the missing remote repository. This also raises another issue: this failure is silent.

```
irb(main):021:0> x = Judge.create name: 'python', image: 'dodona-python', remote: 'git@github.com:dodona-edu/judge-pythia.git', renderer: PythiaRenderer
  TRANSACTION (3.2ms)  BEGIN
  Judge Exists? (2.8ms)  SELECT 1 AS one FROM `judges` WHERE `judges`.`name` = 'python' LIMIT 1
  TRANSACTION (1.7ms)  ROLLBACK
=> #<Judge id: nil, name: "python", image: "dodona-python", path: nil, created_at: nil, updated_at: nil, renderer: "PythiaRenderer", remote: "git@github.com:dodona-edu/judge-pythia.git">
irb(main):022:0> Rails.logger.info(x.errors.inspect)
#<ActiveModel::Errors:0x00007fa80c4ca5e8 @base=#<Judge id: nil, name: "python", image: "dodona-python", path: nil, created_at: nil, updated_at: nil, renderer: "PythiaRenderer", remote: "git@github.com:dodona-edu/judge-pythia.git">, @errors=[#<ActiveModel::Error attribute=remote, type=ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
, options={}>]>
=> 456
```

**Comment by bmesuere** [comment]
Hi Nils, thanks for reporting this issue.

It seems that we use the python judge in our seeds which is not public (code quality issues). We should indeed replace this by another public judge.

For now, as a workaround there are two options:
- Replace the url of the python judge with another one that is public in the `db/seeds.rb` file [on line 146](https://github.com/dodona-edu/dodona/blob/develop/db/seeds.rb#L146) (some other judge urls are mentioned in the lines below).
- Depending on what you are planning to do with your local instance, we can give you access to the python judge repo

**Comment by thepieterdc** [comment]
@nvgeele Example here in the `sed` lines https://github.com/dodona-edu/dodona/blob/b9596c2eaa7ddb92e53b9b6c8557249d477b2105/Dockerfile

**Comment by nvgeele** [comment]
@bmesuere @thepieterdc Thanks for the workaround. Maybe I'll just run Dodona in a container, might be easier. With regards to what I'm planning to do: I'm gauging how hard it would be to create a judge for Scheme. We have heard good things about Dodona and I want to see if we can use it for a course at the VUB.

**Comment by bmesuere** [comment]
A Scheme judge sound cool, maybe @chscholl is also interested. We'd be happy to give you some pointers, so let us know if you're interested and we'll set up a call.

**Comment by chvp** [comment]
We should make this configurable using an ENV variable when seeding (where the default is not to use the python judge).
