### ISSUE TITLE
Move staff requests into the platform

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#2599]
By far the highest support load is giving staff access to teachers. This will only increase in the next years. To reduce the load, it would make sense to move these requests inside the platform.

- For signed in users, enable a separate form where they can request staff access. The form should include a motivation field and offer the ability to change the school's name if it wasn't manually set before.
- These requests are not granted automatically, but end up in a queue for our approval
- We can see a list of open requests and easily approve or deny them, possibly updating the school name in the process
- Teachers receive an automated email telling them their request was granted

**Comment by pdawyndt** [comment]
Some additional options we might consider:

- Let teachers already propose a school name in the process of requesting staff access (especially if they are the first teacher of their school); are there any other properties they can set for the school (login method)
- Empower users with staff access to manage their own institute: update institute properties, assign other users of the institute as staff
