### ISSUE TITLE
Move the tutor iframe to a sandboxed domain

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#2601]
We don't have a lot of faith in the JS code of the python tutor. Since it's shown in an iframe already, it would be good to host it from a separate domain, similar to exercise descriptions.

**Comment by bmesuere** [comment]
This is easy to do (just use a different url), but hard to get the right url in the right place because the sandbox hostname lives in ruby land and needs to get in heavily nested JS code. There are several options:
- The obvious solution would be to pass this along the call tree. The problem is: this is heavily nested code and adding the hostname should be done in the pythia renderer and passed along many times as extra parameter.
- Add the hostname as a data attribute to the submissions, so we can fetch it when running the tutor. Adding should also be done in the pythia render, but we skip the passing along.
- Add it to the dodona js namespace on the submission page so we can easily use it wherever we want
- Add it to the dodona js namespace globally (so other code could use it in the future as well + grouping the dodona namespace assigns)
- Hard code the sandbox url in JS

What do you think @chvp @rien?

**Comment by chvp** [comment]
My first instinct is to add it to the global dodona js namespace. I guess it could be done just on the submission page. I don't have a strong preference about that.

**Comment by rien** [comment]
I agree with adding the link to the JS namespace, either globally or just for the submission page.
