### ISSUE TITLE
Use URL API in util.js

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#2614]
The functions `updateURLParameter`, `updateArrayURLParameter`, `getURLParameter` and `getArrayURLParameter` in `util.js` can probably be re-implemented using the [URL](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL) and [URL.searchParams](https://developer.mozilla.org/en-US/docs/Web/API/URL/searchParams) APIs. These are supported in all modern browsers: [URL](https://caniuse.com/url) and [URLSearchParams](https://caniuse.com/urlsearchparams).

**Comment by TimonDB** [comment]
I started working on this issue and made a (draft) redesign of `getURLParameter`, is there a way to locally test if this function still delivers the correct output?

![Screenshot from 2021-08-03 16-17-48](https://user-images.githubusercontent.com/53220653/128031392-d38bb207-d62f-4c6f-8614-61c4dc697022.png)

**Comment by chvp** [comment]
We don't have tests for this file specifically, sadly. You can check where it is used and see if the functionality that uses it still works (e.g. for `getURLParameter`, it is used by the tab switching code on the course members page).
