### ISSUE TITLE
Logos on about and sponsor page are ugly in dark mode

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#2645]
![image](https://user-images.githubusercontent.com/481872/116009191-6fcc0680-a618-11eb-831c-7a0f8750ae5b.png)

**Comment by BTWS2** [comment]
@bmesuere do you prefer a transparent background for all images in your screenshot? If so, I'm willing to make a pull request for this.

**Comment by bmesuere** [comment]
That would help make it less ugly, but still not ideal. e.g., UGent has an inverse logo for this use case.

**Comment by BTWS2** [comment]
I'm unable to reach the homepage in dark mode, but I changed it anyway (see PR).
