### ISSUE TITLE
Switch order of thumbs up/down buttons in grading panel

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2715]
In the grading panel, the 0/max buttons have been replaced by thumbs up/down icons. Where it was clear that with the 0/max buttons, the expected locations of the buttons was zero-left and max-right, this is no longer the case with the thumbs up/down icons.

Proposal: Put the thumbs up button to the left and the thumbs down button to the right. As a signal that we prefer good scores over bad scores. If most students have done a good job at an exercise, the thumbs up button also comes first in the left-to-right reading order while filling up the scores. 

This way

![image](https://user-images.githubusercontent.com/5736113/118353574-3a577080-b567-11eb-9067-ec79709e8409.png)

would become

![image](https://user-images.githubusercontent.com/5736113/118353505-d16ff880-b566-11eb-8dbd-76d141568296.png)

**Comment by rien** [comment]
I also intuitively reach for the left button as the "approve" button somehow, but I also think the current configuration is more aesthetically pleasing.

Maybe it is an idea to add some color coding (thumbs up = green, thumbs down = red) to nudge towards the correct button?
