### ISSUE TITLE
Clear grades

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2716]
The thumbs up/down buttons at the "total"-level fill up all scores, but there is no way to also clear all scores if this actions was mistakenly done. Adding this option has even become more important for evaluations with scores, since filling up all scores has replaced manually marking the evaluation of a solution as completed.

I only felt a need to add a clear button for the top-level actions, but for better UI-alignment similar buttons might also be added to clear the individual score items. EDIT: I only discovered afterwards that the individual score items already have the clear option (paste-bin on the left; would have expected something like a cross on the right); still think it's equally (even more) useful top-level

**Comment by pdawyndt** [comment]
The thumbs up/down buttons at the "total"-level fill up all scores, overwriting any previous scores that could have been assigned already. We might consider that these buttons would only full the empty score items.

**Comment by pdawyndt** [comment]
Today, I again had the same idea that the top-level thumbs up/down buttons should fill up the empty score items, not overwriting the score items that have already been filled. Apparently I already had the same idea some months ago.

**Comment by BramDevlaminck** [comment]
If I understand correctly: the 2 features we want to implement are
1.  The 👍 and 👎 button only fill in the values of the score items that are still empty.
2. A top-level clear option to empty all the score items of the current submission.

**Comment by pdawyndt** [comment]
That's indeed what I would suggest.

**Comment by BramDevlaminck** [comment]
@bmesuere mentioned he was not convinced of changing how the 👍 and 👎 button work.
Is it worth it to change how this works?
