### ISSUE TITLE
Obscure reviewers

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2717]
When publishing evaluation feedback (grades and annotations) the name of the reviewer is visible for the students. Since the grades and annotations should (in theory) not depend on the reviewer, we might provide an option to obscure the name of the reviewer towards the students, as we always obscure the name of the student for the reviewer in demo mode.

**Comment by pdawyndt** [comment]
An idea for obscuring is replacing the name of the reviewer by "rubber duck", as a reference to the feedback given in the rubber duck debugging process.

**Comment by BramDevlaminck** [comment]
If I understand this right, we would like to give an option to the reviewer to anonymize his/her name in the feedback.
I think we could do this for an exercise or series? The button to activate/disable this would be located where you set up the evaluation as a teacher.

I imagine we could place the buttons somewhere here:
![Image](https://user-images.githubusercontent.com/68779933/183075730-b4f54f5d-6205-49d4-8ccc-e6491b65458b.png)

There would be a button per exercise. But this might be a bit overkill? We could also just provide 1 button per series or a combination of both.

The name that would be anonymized is circled in this picture:
![Image](https://user-images.githubusercontent.com/68779933/183075207-2faaa6c0-93ab-4dcf-a851-fa84d3eaea6c.png)

**Comment by chvp** [comment]
A setting in the evaluation seems like the most sensible. I would not replace it with an anonymized name, but just leave the name out.

**Comment by BramDevlaminck** [comment]
You mean 1 toggle button for the whole evaluation? This seems the most consistent indeed. It would be weird to see the name of a reviewer on 1 exercise of a series and not on the next one.

**Comment by chvp** [comment]
That's what I mean, yes.

**Comment by pdawyndt** [comment]
I would also do this for an entire evaluation, but it would be handy if students could still see which annotations come from linting (no name attached) and which assessments come from a manual code review, even in case we do not show the actual name of who did the manual code review.

**Comment by BramDevlaminck** [comment]
In that case some placeholder name for a reviewer could make the distinction between these 2 kinds of annotations. We could use "reviewer" or just "rubber duck" as you suggested above.

**Comment by chvp** [comment]
They are still distinct through the annotation type.

**Comment by chvp** [comment]
Is there an easy way for me to view both in context? Some line I can comment out/uncomment in the current state of the PR?

**Comment by BramDevlaminck** [comment]
> Is there an easy way for me to view both in context? Some line I can comment out/uncomment in the current state of the PR?

The easiest way will be to create some feedback on an evaluation and then just edit the html in your browser via *inspect element*.

**Comment by chvp** [comment]
I agree that the version without any info looks kinda weird.

**Comment by BramDevlaminck** [comment]
I'd like to add some way of showing if the anonymiser is activated for the evaluation or not in the evaluation overview.

It seems logical to add it somewhere here in this screen. I thought about adding it between the header and the small phrase that describes the amount of students, when the deadline is,... Does anyone have any other suggestions?

<img width="1326" alt="image" src="https://user-images.githubusercontent.com/68779933/184318130-60453f63-373a-47fc-93a9-396ed4f43a86.png">
