### ISSUE TITLE
Display of toggled content in descriptions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2751]
Is there an action needed to update the HTML of "toggled content" in descriptions?

Example: exercise [Light work](https://dodona.ugent.be/en/activities/819600301/)

![image](https://user-images.githubusercontent.com/5736113/119156556-a0a32e00-ba54-11eb-84a9-a14b103591cf.png)

**Comment by pdawyndt** [comment]
Display of toggled content still isn't 100% correct.

**Comment by bmesuere** [comment]
The title should be a block element.

**Comment by chvp** [comment]
`panel-title` should indeed be a `div`, not a `span`. This seems to me like something that should be fixed in the exercises, not in Dodona.

**Comment by chvp** [comment]
I fixed this in the exercises using a span for the title element.
