### ISSUE TITLE
Extra coloring when clicking menu items

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2753]
Is it intentional that clicking a menu items, temporarily gives the item a pronounced background color?

Light mode:

![image](https://user-images.githubusercontent.com/5736113/119158996-1b6d4880-ba57-11eb-9b58-ade1da5e62f9.png)

Dark mode:

![image](https://user-images.githubusercontent.com/5736113/119159098-3475f980-ba57-11eb-8227-6de234017cd6.png)

**Comment by bmesuere** [comment]
yes
