### ISSUE TITLE
Superfluous newline and padding in code tag

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2763]
If a code tag is in a pre tag, there is a superfluous newline. This is important because students need to know when to print a newline.

This a minimal example:
````
**Invoer:**

    abcdef

**Uitvoer:**

    123456 
    789123  
````

Render in VS Code:
![image](https://user-images.githubusercontent.com/56451049/119331127-48a03d80-bc87-11eb-9b0b-cfedfb758fdf.png)

Render in PyCharm:
![image](https://user-images.githubusercontent.com/56451049/119331651-e431ae00-bc87-11eb-87cc-83be6897de02.png)

Render on Dodona:
![image](https://user-images.githubusercontent.com/56451049/119331176-59e94a00-bc87-11eb-85b3-61423bb5590f.png)

**Comment by niknetniko** [comment]
This doesn't happen for me in Firefox.

In Chrome, the culprit seems to be the `unicode-bidi: bidi-override`, which is set by bootstrap I think. Setting `unicode-bidi: normal` on the `pre` element seems to reliably fix it, but unsure if this is the real culprit.

**Comment by BTWS2** [comment]
If there are two lines in the code tag, the first one is recessed. This is caused by the padding. To students this may come across as a whitespace.
![image](https://user-images.githubusercontent.com/56451049/119350980-3ed70400-bca0-11eb-98d2-ec7059342710.png)

**Comment by niknetniko** [comment]
The extra space at the start is a `padding-left: 3px;` on the `code` element inside the `pre`.
