### ISSUE TITLE
Highlight prompt in dark mode

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2778]
In highlighted code in exercise descriptions, prompts only get a distinct color in white mode, not in dark mode.

**Comment by chvp** [comment]
Can you add a screenshot?

**Comment by bmesuere** [comment]
The syntax highlighting colors are done by a separate css file and were not touched in the bootstrap migration. Are you sure this was different before?

**Comment by pdawyndt** [comment]
No, not sure.

**Comment by TimonDB** [comment]
Similar to #2411, prompts get also a distinct colour in dark mode. However, this colour is #f8f8f2 which is the same as the other text. Should this prompt colour in dark mode be adapted or can this issue be closed?

`rouge-dark.css.scss`
![Screenshot from 2021-08-02 17-05-13](https://user-images.githubusercontent.com/53220653/127883349-48694d00-5641-4467-b595-a5c0e863ee6f.png)

**Comment by bmesuere** [comment]
Replacing `#f8f8f2` with something more prominent seems the way to go. You should probably pick a color that's already used in the rouge-dark file so we keep using the same theme.
