### ISSUE TITLE
Going back doesn't show scores in evaluation

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2813]
Clicking the ⬅ button in the browser (Chrome), goes to the previous student, but doesn't show the entered scores. If you try to enter the scores again you get the warning `This score was already changed by another user` and the previously entered scores load.

Is it possible to load the scores immediately after clicking ⬅?

**Comment by chvp** [comment]
Probably due to browser-level caching

**Comment by BTWS2** [comment]
@chvp It works on Firefox, but not on Chrome and Edge.

**Comment by bmesuere** [comment]
In general, Firefox restores more form field input when going back than Chrome. It seems here that Chrome (and Edge) reload the original version instead of the user-edited one. Autocomplete: false probably also plays a role.

**Comment by bmesuere** [comment]
I cannot reproduce this on Chrome, Firefox or Safari on mac. Everything works as expected.
- open an evaluation page where no scores are filled in yet
- enter a score, eg: "1"
- click the next button
- click the browser back button
- "1" is still there

**Comment by BTWS2** [comment]
@bmesuere strange, I tried similar steps on Windows.
https://user-images.githubusercontent.com/56451049/121187967-e9d2ea80-c868-11eb-9d51-fb2c3acfb255.mp4

**Comment by niknetniko** [comment]
I can't seem to reproduced with Chrome on Windows either, so it doesn't seem OS specific.

https://user-images.githubusercontent.com/1756811/121190680-93b37680-c86b-11eb-88a7-b86e99fa0ea4.mp4

**Comment by chvp** [comment]
@BTWS2 could you try opening the developer tools of your browser and see what headers are sent for that last request? The issue you're seeing shouldn't be related to form caching, because the problem there is that the browser restores too much, not too little. I think your browser is caching the original page load, but our cache control headers should prevent that. A look at the headers of your request(s) might illuminate the problem. Make sure to censor your cookie headers, to prevent impersonation.

**Comment by chvp** [comment]
Seems like chromium does not respect the cache headers like it should: https://bugs.chromium.org/p/chromium/issues/detail?id=516846. I still don't get why we can't reproduce this though. I would prefer not to change our cache header though.

**Comment by BTWS2** [comment]
I updated Chrome today to 91.0.4472.124, but the issue persists. I will use a non-chromium-based browser for grading. Going back doesn't happen that often, but I still wanted to signal this bug.

**Comment by chvp** [comment]
I think I figured out why we weren't able to reproduce this. The profiler we use for requests overrides the cache headers to `no-store`, which avoids the issue.
