### ISSUE TITLE
Remove ability to make score is more than maximum score when clicking next

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2814]
If you click `NEXT` when the total score is more than maximum score (25/4.5), Dodona does't give a warning.

![image](https://user-images.githubusercontent.com/56451049/120847845-55207200-c574-11eb-9274-24f16b6c3eeb.png)

**Comment by chvp** [comment]
I think this is intended? IIRC, @pdawyndt wanted to be able to exceed the possible scores (similar as in Ufora).

**Comment by chvp** [comment]
We have not seen any use of the ability to exceed the limits, so we're just going to remove the ability to do that, since we don't have a clear usecase.
