### ISSUE TITLE
Review panel sticky position doesn't work anymore

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2818]
If a submission has many lines of code, the review panel stays at the top. To enter the scores more easily it would improve the UX if the panel moves down when the user scrolls down (shown in this video).
https://user-images.githubusercontent.com/56451049/120853654-4fc72580-c57c-11eb-9c08-1a172f575f3a.mp4

**Comment by chvp** [comment]
We'll need to figure out what to do if the panel is taller than the viewport height, but I definitely agree that this would be very useful.

**Comment by pdawyndt** [comment]
If I'm not mistaken, it used to scroll along with the page. Broken since Bootstrap 5 migration?

**Comment by chvp** [comment]
There is indeed a `position: sticky` already set. Marking this as a bug.

**Comment by chvp** [comment]
Setting a height attribute fixes the stickyness. The behaviour when the panel is taller than the viewport height is broken though.

**Comment by niknetniko** [comment]
We might want the height to be something like `100vh - $(the sum of the various paddings)` and then make the panel itself scrollable if it is too high.

**Comment by chvp** [comment]
The following works for me:
```
 min-height: 100px;
 max-height: calc(100vh - 70px);
 overflow-y: scroll;
```

**Comment by chvp** [comment]
I wrote a quick userstyle until this is fixed (can be used with the Stylus extension): https://gist.github.com/chvp/61458686fea6a86081152c649b2fe3a0/raw/970975d0622c181513374ef62d5d0968b765e975/sticky_feedback.user.css
