### ISSUE TITLE
Add delete icon to evaluation menu

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2819]
Before:
![image](https://user-images.githubusercontent.com/56451049/120854665-c3b5fd80-c57d-11eb-9713-e85895b88c20.png)

After:
![image](https://user-images.githubusercontent.com/56451049/120855125-60789b00-c57e-11eb-8f6b-0afde0b9feba.png)
Similar to #2811.

**Comment by bmesuere** [comment]
Merged into #2811
