### ISSUE TITLE
Allow multi-line annotations

### ISSUE THREAD

**Issue by chvp** [dodona-edu/dodona#2826]
Allow to add comments/questions on a continuous selection of multiple lines.

From https://github.com/dodona-edu/dodona/issues/1852#issue-599457917

**Comment by bmesuere** [comment]
Github behaviour:
- if you hover over a line, a plus button appears in the left margin
- if you hover over the button, the button grows in size
- if you click the button, the comment form appears
- if you drag the button, the button stays in place but a thick line in the color of the button appears in the margin
  - you can only drag down, not up
- if you release the drag, the comment form appears. The button and line disappear, but the selected lines are highlighted in yellow. Above the text area, a small help text "Commenting on lines xx to xx" is shown. For single line comments, the highlight and info text is not present.
- when rendering a multi-line comment in the code view, GitHub does **not** show which lines the comment belongs to. It is rendered under the last line of the selection as a normal comment. In the PR-comment view where just the comments are rendered the additional lines are included in the small code snippet that shows context.

**Comment by pdawyndt** [comment]
Maybe related:

- comments could be moved to another location by updating the numbers in a help text like "Commenting on lines xx to xx" (both for single line and multiline)
- I often repeat the same comment within the same submission: copy followed by move might speed up this process
