### ISSUE TITLE
Add external URL to machine annotations

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#2845]
We could add a `link` or `external` (the name is debatable, e.g. `info`, `external-info`, `url`, `external-url`, ...) field to the annotation data, which would contain a URL. Dodona can then render this link.

One use-case is linking to additional information for linter messages (see https://github.com/dodona-edu/universal-judge/issues/210). TESTed used to do this itself by rendering HTML, but this doesn't work anymore since #2844.

**Comment by pdawyndt** [comment]
Brings suggestion in #255 back to live!

**Comment by bmesuere** [comment]
I suggest we decide the server text in the renderer so we can choose between "more information" or an icon depending on where we want to add this to the layout.


- In the spirit of keeping it simple, I would use `link`
- This needs to be added to the json schema
- This needs to be added to the documentation
- This needs to be tested with the universal judge

Mockups
![image](https://user-images.githubusercontent.com/481872/121731444-3d576980-caf1-11eb-9af8-333beb286a99.png)
![image](https://user-images.githubusercontent.com/481872/121731686-90c9b780-caf1-11eb-8cac-1d7d0933d865.png)
