### ISSUE TITLE
Uncaught DOMException: Failed to execute 'querySelector' on 'Document' in submission

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2862]
Uncaught DOMException when trying to open a tab in this submission: https://dodona.ugent.be/nl/submissions/7895331/. I'm unable to open the tabs with test cases. This worked in the past, so assume it has to do with bootstrap 5 and/or the fact that the tab name starts with a number.

![image](https://user-images.githubusercontent.com/56451049/122237040-4a90a180-cebf-11eb-8ff5-96b14e7b4be4.png)
`Uncaught DOMException: Failed to execute 'querySelector' on 'Document': '#1tem100beide-1' is not a valid selector.`

**Comment by bmesuere** [comment]
id's indeed can't start with with a number in html. We'll have to prefix this when generating the id's.

**Comment by chvp** [comment]
@BTWS2 how soon do you neer this fixed? We are planning a release on Friday, but if you neer this before then I can do a release with just this.

**Comment by BTWS2** [comment]
@chvp It's not that urgent. Since it's my own exercise I can change the tab name if needed.
