### ISSUE TITLE
Easy fetch last submission in hand in area

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#2886]
Marleen Denert wonders if it would be a useful feature to add a "fetch latest submission"- button when starting an exercise in the hand in area. This would allow for students to continue where they left off without much hassle.

In the current situation you have to start from the series:
> Go to series:
> ![image](https://user-images.githubusercontent.com/56451049/123393939-e2b51780-d59e-11eb-97f5-9e2381bfc366.png)
> Modify submission:
> ![image](https://user-images.githubusercontent.com/56451049/123394033-fa8c9b80-d59e-11eb-9eb3-f80c4d6bc2fc.png)

Suggested situation: notify the user in the hand in area that there is a previous submission available and they can continue where they left off.
> ![image](https://user-images.githubusercontent.com/56451049/123395034-0b89dc80-d5a0-11eb-9864-f5947105c7a1.png)

**Comment by pdawyndt** [comment]
@BTWS2: next to the "hand in" tab is the "submission" tab where students can see their previous submission and continue from any of those submissions (the last submission is on top of that list). So the functionality you are looking for already seems to be there.

**Comment by BTWS2** [comment]
Another possibility is to indicate if or how many previous submission are available, but it doesn't look as clean as before. The number of submission doesn't matter that much, but the user should see somehow that there are previous submission available.
![image](https://user-images.githubusercontent.com/56451049/123424971-d098a080-d5c1-11eb-824a-e64a43e00252.png)
![image](https://user-images.githubusercontent.com/56451049/123425369-5d435e80-d5c2-11eb-9828-d8cd0b2cce7a.png)

Currently, there is no distinction between new and already made exercises until "Submissions" is clicked.
![image](https://user-images.githubusercontent.com/56451049/123425244-2b31fc80-d5c2-11eb-95f0-3f3fa8ef5635.png)

Fetching the last submission could be an optional feature of the plugin/extension.

**Comment by chvp** [comment]
Not showing the Submissions tab if there aren't any seems like an easy way to fix that.

**Comment by BTWS2** [comment]
@chvp that's also ok for me.

**Comment by bmesuere** [comment]
We will automatically load a previous submission in the hand in area if there is one available. We should display a message that the previous submission was loaded automatically and add an option to clear/restore the boilerplate code.
