### ISSUE TITLE
Score items keep spinning after being cleared

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2891]
First fill a score item and then clear it again: score items keeps spinning. You can use this to create some cool effects though:

https://user-images.githubusercontent.com/5736113/123450563-2af32a80-d5dd-11eb-8529-0c45738a2714.mp4

**Comment by pdawyndt** [comment]
Also noticed in video that total score isn't updated neither.

**Comment by chvp** [comment]
I can't reproduce this.

**Comment by pdawyndt** [comment]
Google Chrome. Windows 10.

**Comment by chvp** [comment]
Can't reproduce in Chrome either, but I'm obviously not on Windows.

**Comment by niknetniko** [comment]
@pdawyndt  Did you "clear" the scores using the backspace key while typing? I can reproduce the spinning that way.

**Comment by pdawyndt** [comment]
yes

**Comment by chvp** [comment]
Ah, I can reproduce it in that case as well. I was using the clear button.

**Comment by niknetniko** [comment]
- The spinning is because of changes in #2865
- Pressing the backspace didn't/doesn't clear the score, normally you'll get a message like this: 
![image](https://user-images.githubusercontent.com/1756811/123453521-f2a11b80-d5df-11eb-8f2b-43cfd53c8948.png)
(although the message is bit delayed since #2865)

**Comment by niknetniko** [comment]
I think we could do the following: 

- Don't start spinning if the value is invalid (since it will give the impression it is being saved, while that's not true)
- Perhaps add a special case where an empty input field is considered "clearing" the score, and send a clear request instead
