### ISSUE TITLE
Add citation to repository

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#2937]
[Add a citation](https://twitter.com/natfriedman/status/1420122675813441540) for the Dodona publication (submitted) to the GitHub repository.

**Comment by pdawyndt** [comment]
reference for CFF-format: https://citation-file-format.github.io/

**Comment by bmesuere** [comment]
The current version only allows to cite the repo itself, not a publication. So we can't do this right now but this will probably change in the future.
