### ISSUE TITLE
Improve CI ruby test speed

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3016]
The ruby tests are slow using GitHub Actions. While rails supports running tests in parallel, this is disabled in our config. The reason for this was that codecov reported incorrect results when running tests in parallel (only the results of 1 of the threads were uploaded).

This was a few years ago and is probably already fixed at the codecov side.

**Comment by chvp** [comment]
Note that this is not a codecov problem but a simplecov problem.
