### ISSUE TITLE
Remove the color property from the course table

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3035]
This field isn't used anymore since Dodona 5.0 but was kept in the database to be able to revert the color changes. If there's no protest in the first few weeks, this field can be removed.

**Comment by ninewise** [comment]
I, too, used the colours to find courses in previous years (manually setting the same colour every year).

**Comment by pdawyndt** [comment]
Received from Dries Benoit:

> Ik was wat in de war van deze kleuren. Mijn cursussen van vorig jaar zijn groen en nu rood, maar ik geloof dat dit toeval is en dat deze kleuren gewoon deel uitmaken van de color palette die gebruikt wordt? We twijfelden of dit met 'goed' en 'fout' te interpreteren moest?
