### ISSUE TITLE
Merging institutions sometimes fails

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3040]
Merging institution sometimes fails with this error:

```
An ActionView::Template::Error occurred while POST </nl/institutions/699/merge/?other_institution_id=30> was processed by institutions#do_merge
Exception
undefined method 'identifier_string' for nil:NilClass
Hostname
dodona
Backtrace
app/views/institutions/_merge_changes.html.erb:19
app/views/institutions/merge.html.erb:42
app/controllers/institutions_controller.rb:64:in `do_merge'
app/controllers/application_controller.rb:170:in `user_time_zone'
```

Some users might be in limbo due to this:
- users of institution 699 when merging into 30
- users of institution 350 when merging into 301

**Comment by chvp** [comment]
Not sure if this is something we want/need to fix. This can only happen if an institution does not have a `prefer`red provider, which is not actually allowed by the provider validations. The institutions where this is/was the case were probably institutions that were merged manually before the merging was added.

No users should be affected by this, the only merge code that relies on this is the summary of changes before a merge actually happens.

**Comment by bmesuere** [comment]
I manually fixed all all users and institutions in limbo.
