### ISSUE TITLE
Restrict fill to empty score items for global thumbs up/down

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3068]
Seems better UX if the global thumbs up/down buttons in the grading module would only fill up the empty score items, instead of also overwriting the score items that already have been filled. This is also more complementary to the upcoming global clear button to clear all score items coming in the 5.0 release.

**Comment by TimonDB** [comment]
This is also mentioned in a comment on issue #2716 and is taken care of in PR #3032, but since #3032 is currently on hold we might want to consider creating a new PR for this
