### ISSUE TITLE
Consistent usage of decimal dot/comma for score items

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3069]
The total score uses a decimal dot in English and a decimal comma in Dutch. However, the individual score items remain as filled by the reviewer. This might give a sloppy mix of decimal dots and commas. For example, this is how it could look in Enlish/Dutch:

![image](https://user-images.githubusercontent.com/5736113/132127757-3ecd2190-36f4-4caf-97f0-d9553fcf70bf.png)

Note: the English view is what you see when filling up the scores for the first time. Visiting the page again, consistently uses commas for the individual score items, both in English and Dutch.

I guess the same sloppy mix might appear in the view students get to see.

Suggestion: systematically display decimal dots in English and decimal commas in Dutch, both for total score and individual score items.

**Comment by pdawyndt** [comment]
NOTE: In the grade overview, all scores use decimal dots in English and decimal commas in Dutch. So the score cards next to a submission in an evaluation are not consistent with the grade overview.

**Comment by chvp** [comment]
This is only for the entered data, refreshing the page makers it consistent (they're stored as numbers in the database). I don't agree that this is a problem. Changing the entered data right after entering might be jarring.

**Comment by pdawyndt** [comment]
No it is not OK: in English the total score is displayed with a decimal dot and the individual score items are displayed with a decimal comma (after page refresh/revisit).

**Comment by chvp** [comment]
That is due to your browser's language settings. We can't do anything about how browsers show values in input fields except for using fake input fields which come at a much larger implementation cost for us and introduce their own host of accessability (and other) issues.
