### ISSUE TITLE
Unclear message for grade overview

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3070]
I have no idea what the last sentence in the grade overview message means. I tought we abandonned the idea of leaving submissions incomplete when having a grade rubric set up.

> If the score is gray, the submission is not yet completed.

![image](https://user-images.githubusercontent.com/5736113/132128100-7c430388-d339-4f51-900b-30c9e6007e47.png)

**Comment by chvp** [comment]
What is unclear? The message says what it means to say: if the submission has not received data for all score items, the number will be gray instead of black.

**Comment by pdawyndt** [comment]
I assumed that situation was not longer possible, i.e. that you could no leave a submission incomplete

**Comment by chvp** [comment]
It is definitely still possible, if not all score items are filled.

**Comment by bmesuere** [comment]
The wording might be improved a bit. Without knowing where we came from "submission not yet completed" doesn't make a lot of sense since we don't use that wording anymore for grades. Something like "Gray scores are still incomplete" might be better.
