### ISSUE TITLE
Only last score item is updated when entering scores too fast

### ISSUE THREAD

**Issue by pverscha** [dodona-edu/dodona#3072]
When grading exercises, it often occurs that a student only solves the first few steps of an exercise. In this case, I often just fill in all other score items with a zero by clicking the first box and then pressing 0, TAB, 0, TAB, 0, TAB, etc. However, if I do this too fast, only the last score item is updated and the loading indicator is never hidden. No errors are shown in the console, but when I take a look in the network tab of the browser's developer tools I see that only one request is performed.

I double checked and the entered scores are not saved and need to be entered again.

**Comment by chvp** [comment]
Probably due to our debounce logic?
