### ISSUE TITLE
HTML-renderer changes the entire dodona look

### ISSUE THREAD

**Issue by QuintenVervynck** [dodona-edu/dodona#3112]
We're making a html/css-judge and encountered the following bug.

The HTML renderer can change the css values of the dodona website, when it should only apply the css-rules to the html passed to the renderer

the html_content I submitted looked like this
```html
<!DOCTYPE html>
<html>
  <head>
    <style>
        * {
            background-color:black;
            color:black;
        }
        div {
            background-color:red;
            color:red;
        }
    </style>
  </head>
</html>
```
So this does nothing except css, but when you include a body tag and so on the result remains the same:
![Screenshot from 2021-09-17 09-29-24](https://user-images.githubusercontent.com/68075051/133742637-39e59f7d-8102-431e-9f65-c30571c45691.png)

As you can see the css is applied to the entire website, not just the html I wanted to render (the html I submitted).

**Comment by chvp** [comment]
This is not a Dodona issue, since this is how HTML and CSS works. Judges should take care not to output global css (and/or unprocessed user input).
