### ISSUE TITLE
Fix deprecation warnings when building assets

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3142]
The asset compilation generates a long list of deprecation warnings from sass. Recently, Babel joined the club and thousands of log lines are generated.

**Comment by jorg-vr** [comment]
I remember getting the sass deprecation warnings as well, but can't seem to reproduce them. 
Could you provide reproduction steps?
Or maybe these where fixed by https://github.com/dodona-edu/dodona/pull/3272

**Comment by bmesuere** [comment]
They were about variables not being assigned at the top level and that this would break in future versions. However, they were assigned at the top level so maybe this is fixed by renaming the imports.
