### ISSUE TITLE
Add option to rename repository

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#3210]
If users make a typo or want to change the name to a better one, there is no option to do so currently.

![image](https://user-images.githubusercontent.com/56451049/141787155-69ae7965-335d-4261-8286-ba8291ae2c51.png)

~~Bart noted that the repo name is used as location on the server. A rename on the website should result in a move in the file system.~~

**Comment by chvp** [comment]
Note that the name being used as a location is no longer true, so this is not a problem.

**Comment by BTWS2** [comment]
Solved by #4381.
