### ISSUE TITLE
Easy embedding of Markdown code fragments

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3216]
I don't know if we want to evolve to using a rich Markdown editor, but while code reviewing it would be handy if at least we could have support to include code fragments into a comment. Inline code fragments
```
`xxx`{:.language-python}
```
and code fragment blocks
`````
```python
xxx
```
`````
require some typing. Would be handy if users quickly could add stubs to a Markdown field. When reviewing code, the programming language of the code is known, so could be filled up automatically as well.

**Comment by niknetniko** [comment]
Maybe we could introduce a toolbar, similar to the one on [Github](https://github.com/github/markdown-toolbar-element)? Another button we could add is a copy the line on which the annotation is added into the annotation text field button. There have been a few times where I missed such a feature. (Although I realize it is very easy to just manually copy the line instead)

**Comment by bmesuere** [comment]
This would be useful, but is too much work to implement. (if github would open source their component, that would be nice)
