### ISSUE TITLE
Support proper rendering of JFIF formatted images

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3237]
JFIF images are properly rendered when embedded in a HTML page, but not when rendererd standalone ([example](https://dodona.ugent.be/nl/repositories/76/public/aoc/2021/day11.jfif)). As a result of the latter, they are also not properly rendered in a lightbox.

**Comment by chvp** [comment]
Rails' [`lookup_by_extension`](https://api.rubyonrails.org/classes/Mime/Type.html#method-c-lookup_by_extension) does not recognize `"jfif"`. JFIF is an obsolete standard that we are not going to add special-casing for on top of Rails to support. Closing as wontfix (just use normal JPEG).
