### ISSUE TITLE
allow to disable Python Tutor for certain contexts

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#326]
On SPOJ, we used to disable the Python Tutor for exercises that use files. As long as we don't support file handling in the Python Tutor, we could do something similar.

I will look to see if I can add a parameter in the JSON output that indicates that the Tutor should be disabled. Can this parameter then be supported in Dodona?

_[Original issue](https://github.ugent.be/dodona/dodona/issues/326) by @pdawyndt on Mon Dec 05 2016 at 13:29._

**Comment by chvp** [comment]
Original usecase is no longer relevant, and we haven't seen any demand for this in the past five years.
