### ISSUE TITLE
Smooth expanding/collapsing of Bootstrap panel groups

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3264]
Expanding or collapsing a Bootstrap panel group in the description of an exercise, make the page jump all around (probably resulting from changing the height of the iframe containing the description). Would be nice if these transitions go without these jumps.

**Comment by bmesuere** [comment]
This is due to the iframe resize library we use. The height of the iframe is adapted to the height of the content. If the content height changes, the iframe will adapt. Not much we can do about this.

**Comment by bmesuere** [comment]
Upon review, this has nothing to do with resizing the iframe (example at https://dodona.ugent.be/nl/courses/773/series/8694/activities/412723997/). The collapse there uses a href anchor as target which scrolls into view. Switching to a data attribute will probably fix this. This is also recommended in the bootstrap docs:

> Generally, we recommend using a button with the data-bs-target attribute. While not recommended from a semantic point of view, you can also use a link with the href attribute (and a role="button"). In both cases, the data-bs-toggle="collapse" is required.

**Comment by pdawyndt** [comment]
@bmesuere: Thanks. That indeed does the job.
