### ISSUE TITLE
scss files no longer rebuild automatically

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#3289]
This bug was created by: https://github.com/dodona-edu/dodona/pull/3272

The issue is also mentioned here: https://github.com/sass/sassc-rails/issues/55
https://files.slack.com/files-pri/TNLH8C0LC-F02TF607XN1/image.png

### Workaround:
`rm -rf tmp/cache`

### Tested  and failed solutions:

Keeping only `.css` extensions on import statements results in the following bug:
```
ActionView::Template::Error (Error: Undefined variable: "$development".
        on line 70:5 of app/assets/stylesheets/theme/theme-light.css.scss
        from line 11:9 of app/assets/stylesheets/base.css.scss
>> @if $development == true {

   ----^
):
```

removing all extensions on import results in the following bug:
```
Error: File to import not found or unreadable: base.
        on line 6:1 of app/assets/stylesheets/application.css.scss.erb
>> @import "base";
```

**Comment by chvp** [comment]
If/when we switch to webpacker to build our non-JS assets, this would be fixed, I'd assume.

**Comment by bmesuere** [comment]
This apparently was also a problem when deploying to naos earlier, so the impact is bigger than just local development 😞
