### ISSUE TITLE
Be clearer that Dodona needs push rights to exercise repositories

### ISSUE THREAD

**Issue by chvp** [dodona-edu/dodona#3298]
At least [this translation](https://github.com/dodona-edu/dodona/blob/develop/config/locales/views/repositories/nl.yml#L4) needs to be updated, but if we could somehow check at creation time that we have the correct rights and refuse to create if not that would be optimal I think.

**Comment by chvp** [comment]
Apparently we also don't error if pushing fails due to insufficient access? Which I find confusing, since we occasionally see errors when pushing fails due to other reasons (at least I think we do).

**Comment by jorg-vr** [comment]
Did some research:
The only way to check push rights on creation time, is by pushing a dummy commit and seeing if it works. (https://stackoverflow.com/questions/22811045/how-can-i-check-write-access-to-a-remote-git-repository-can-i-push/40326507)
This will probably only be possible to do cleanly after cloning the repo, which will be made async by https://github.com/dodona-edu/dodona/pull/3295

So the check at creation time will be hard to achieve.

**Comment by chvp** [comment]
If it's not possible at creation time, we should at least error when pushing fails and notify the user about it, IMO. Right now neither we nor the user are aware there is any problem.
