### ISSUE TITLE
Proper HTML escaping in score item tooltips of evaluation

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3319]
![image](https://user-images.githubusercontent.com/5736113/150203406-46297d87-27f1-425d-87fb-8986246ebbeb.png)

Example: [evaluation](https://dodona.ugent.be/nl/evaluations/258/feedbacks/99901733/)

**Comment by bmesuere** [comment]
Two options here:
- Fix the encoding
- [add](https://getbootstrap.com/docs/5.1/components/tooltips/#examples) `data-bs-html`
