### ISSUE TITLE
Bump eslint-plugin

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3337]
One of our dependencies is `@typescript-eslint/eslint-plugin` which is pinned at version 4 in our package.json file. A [recent dependabot PR](https://github.com/dodona-edu/dodona/pull/3335) is incompatible with this version so we should probably update to version 5.10.

Related, it might be worth figuring out why we are still at version 4. Why didn't dependabot bump this version (and that of eslint-parser, eslint itself, jest, etc). Is it because this is a dev dependency?

**Comment by jorg-vr** [comment]
Can't really find why some are ignored. Our `dependabot.yml` looks fine 

Although our package ecosystem is npm instead of yarn => Is this on purpose? Maybe updating this can solve it?

It is unlikely to be caused by them being `devDependencies` as  `eslint-plugin-jest` was also a `devDependency`

**Comment by bmesuere** [comment]
AFAIK our dependabot.yml was generated automatically based on the old settings on the dependabot website. If there is an option to set yarn instead of npm, we should indeed use that.

**Comment by bmesuere** [comment]
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem

The docs mention `npm` as key for yarn.
