### ISSUE TITLE
Highlighting of Python !r format specifier

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3350]
Subtle issue with parsing/highlighting the `!r` format specifier in Python code snippets inside code annotations.

![image](https://user-images.githubusercontent.com/5736113/152639436-7be741a9-56a0-4364-ba11-3f093cbb4c9b.png)

Code review example: https://dodona.ugent.be/nl/feedbacks/655690770/

**Comment by bmesuere** [comment]
This is an issue with Rouge: http://rouge.jneen.net/v3.28.0/python/cmV0dXJuIGYiUm9sbGVuKHtzZWxmLmJlc3RhbmQhcn0pIg

**Comment by chvp** [comment]
My fix has been merged in upstream. This should be fixed on the next rouge update.
