### ISSUE TITLE
Series graphs default end time should be the deadline

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3353]
The series graphs now have a selectable time range. Previously, the deadline was taken as the end time, but this is no longer the case. This behaviour should be restored.

**Comment by bmesuere** [comment]
The bug seems to be more subtle. In exam group 1 in https://dodona.ugent.be/en/courses/359, the end of this month is taken as end date. In exam group 1 in https://dodona.ugent.be/en/courses/773, the deadline is taken.

**Comment by pdawyndt** [comment]
Somehow showing the deadline as a reference point in the visualisation would also be an asset.
