### ISSUE TITLE
The repositories table is broken due to long clone URLs

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#3430]
On https://dodona.ugent.be/nl/repositories/

![image](https://user-images.githubusercontent.com/21177904/155283716-caa1842e-97d4-4e8e-9bd5-3b4971f9d57e.png)

Probably caused by:
![image](https://user-images.githubusercontent.com/21177904/155283818-c97e7eb0-78af-4a06-8888-d38a90107500.png)

**Comment by chvp** [comment]
What's broken? There is horizontal scroll to see the elements to the right.

**Comment by jorg-vr** [comment]
Hmm not broken but not very intuitive in that case.
I had to scroll down a rather long page to find the scroll bar. I think we should limit the size for some columns

**Comment by bmesuere** [comment]
I'm used to horizontal scrolling with my touchpad so it didn't occur to me that to need to scroll to the bottom to use the horizontal scroll bar otherwise. Would adding pagination (and filtering) help with this?

**Comment by jorg-vr** [comment]
As we have limited this page to own repositories for teachers (#4380 ), and teachers see one column less (so the with is less often an issue), this becomes a feature that is only relevant for zeus users

I suggest closing it
