### ISSUE TITLE
A better onboarding experience

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3433]
When a user signs in for the first time, we should provider a better welcome and onboarding experience. One way to do this is to redirect them to a special page or modal. This page can introduce several things:

- The contact form
- The documentation
- If a new institution was created (i.e. this user is the only one for their institution), this is possibly a teacher. Direct them to the getting started page in the docs.
- The page to add courses
- Our "your data" page
- Our twitter and facebook accounts
- In the future, as part of #2597, the implicit approval of our privacy policy if they start using the platform.

In addition, should we illustrate how dodona works and how to sign in?

**Comment by jorg-vr** [comment]
I would not notify first time user of 'The contact form' or 'Our twitter and facebook accounts'.
Links to these are present on every page in the footer, where they are findable for anyone who wants to reach out or follow us. I don't see why anyone would use them directly after their first sign in?

"The page to add courses"
Is already very prominently shown on the home page as long as you haven't subscribed to any courses
![image](https://github.com/dodona-edu/dodona/assets/21177904/e0ef58b0-d43c-4913-bd2a-cb41b7195668)

The "your data" page and the "approval of our privacy policy" is already part of the login flow for private users. See https://github.com/dodona-edu/dodona/pull/3859
Do we also want to show the same info for other users? Again this info is already in the footer and I guess actually reading this info will be done by very few students on first login.

So the only TODO left is detecting new Teachers and directing them to the docs?

**Comment by jorg-vr** [comment]
Update: The links for your data and privacy policy are already on the home page for institutional users without courses:
![image](https://github.com/dodona-edu/dodona/assets/21177904/6245048f-1120-4268-831e-8e1e9821d55a)

**Comment by bmesuere** [comment]
I agree with most remarks. I don't think it would hurt to show the privacy/data card for all users without courses?

**Comment by jorg-vr** [comment]
we currently only not show it for personal accounts. And those have had to specifically agree with it when opening an account. So I would think that is covered
