### ISSUE TITLE
Error on course copy

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3434]
The new course copy behavior seems to still contain a little bug. This error was logged:

```

A NoMethodError occurred in courses#index:

  undefined method `admin_of?' for nil:NilClass
  app/controllers/courses_controller.rb:30:in `block in index'


-------------------------------
Request:
-------------------------------

  * URL        : https://dodona.ugent.be/nl/courses?copy_courses=true&page=1&format=js
```

**Comment by jorg-vr** [comment]
I assumed `current_user` would be set, but as the policy for `index` is `true` this will not always be the case

Do I make a specific `index_copy_courses` policy or do I change the code to `current_user&.admin_of?(course)` (Where the `&` is newly added)
