### ISSUE TITLE
Add support for signing in using SURFconext

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3440]
We want to allow Dutch schools to sign in using SURFconext. More information can be found at https://wiki.surfnet.nl/display/surfconextdev/How+to+connect+your+service

Some remarks:
- we want to use their [OpenID Connect](https://wiki.surfnet.nl/display/surfconextdev/Preparation+with+OpenID+Connect) implementation and not SAML
- they have a [test environment](https://wiki.surfnet.nl/display/surfconextdev/Connect+to+the+Test+environment) to be able to test stuff
- We will probably have to add some logic to create new institutions automatically
- We will have to choose which attributes we want.

Note: schools won't have automatic access to Dodona. The school admin must enable this for their school in the dashboard.

We will need an eduID to be able to sign in into their dashboard. Creation is easy on [eduid.nl](https://eduid.nl). Ping me after account creation, I can add you to the dashboard.

**Comment by jorg-vr** [comment]
First draft of potentially useful attributes: (from https://wiki.surfnet.nl/display/surfconextdev/OpenID+Connect+claims+in+SURFconext)

User:
```
given_name => user.first_name
family_name => user.last_name
preferred_username => user.username
locale => user.lang
email => user.email
```
Institution:
```
schac_home_organisation => institution.generated_name
schac_home_organization_type => institution.category
# In practice, this attribute is not/hardly used by IdP's or SP's
# Please contact support@surfconext.nl if you would like to use this attribute
```
Identity:
```
sub => identity.identifier
```
