### ISSUE TITLE
Python linter gives unhelpful info message

### ISSUE THREAD

**Issue by TomAlard** [dodona-edu/dodona#3517]
When defining a method in Python with a name which (presumably) doesn't match this regex `[_A-Za-z0-9]{1,30}$`, the following info message is shown:

![image](https://user-images.githubusercontent.com/31311896/162611804-b681e7a5-c66a-4582-8547-1e1ddb16c731.png)

This happens when the name of the function is longer than 30 characters (like in the case above), or when the function contains Unicode characters outside the ASCII range:

![image](https://user-images.githubusercontent.com/31311896/162611940-ead8c8ab-cbea-401a-9504-f7da856db8ac.png)

The same results can be observed for constants:

![image](https://user-images.githubusercontent.com/31311896/162612693-a858dd92-ee5c-4082-a55d-af1b4f88a7c0.png)

Class names seem to be exempt from the maximum length:

![image](https://user-images.githubusercontent.com/31311896/162612761-e590e8a3-6891-45ac-9fe3-164ab1aea93d.png)

... but do not tolerate non-ASCII characters, interestingly, the message here is similar but more informative, which makes me suspect that this is in fact a bug:

![image](https://user-images.githubusercontent.com/31311896/162612827-713adacf-a575-4c82-b59d-0c495950f7d6.png)

This regex check appears to only exist for Python, as both JavaScript and C do not give info messages for the same function names:

![image](https://user-images.githubusercontent.com/31311896/162612275-678e55e2-2ce3-470b-89af-10caad004e9c.png)

![image](https://user-images.githubusercontent.com/31311896/162612299-d8debce8-e912-46c4-8658-91a244d11d77.png)

The Python [docs](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-identifier) say this about valid identifiers:

> Within the ASCII range (U+0001..U+007F), the valid characters for identifiers are the same as in Python 2.x: the uppercase and lowercase letters A through Z, the underscore _ and, except for the first character, the digits 0 through 9. Python 3.0 introduces additional characters from outside the ASCII range (see [PEP 3131](https://www.python.org/dev/peps/pep-3131)). For these characters, the classification uses the version of the Unicode Character Database as included in the [unicodedata](https://docs.python.org/3/library/unicodedata.html#module-unicodedata) module. Identifiers are unlimited in length. Case is significant.

Therefore, the regex `[_A-Za-z0-9]{1,30}$` matches with *all* valid Python identifiers except for those that

- Contain non-ASCII characters, but this is already handled by the other check
- Are longer than 30 characters

Therefore, wouldn't it make more sense to replace the regex with one like this `^.{1,30}$` and change the info message to something like `Function/Constant/... name should not be longer than 30 characters`? This would be a more helpful message, and would also prevent showing two messages when a non-ASCII character is used in an identifier.

**Comment by chvp** [comment]
We use pylint under the hood to generate these messages. We do a few customizations to it, but generally try to avoid it to ease upgrading. I will look into this at pylint's repo on monday.
