### ISSUE TITLE
Papyros offcanvas-button always seems to trigger horizontal scrollbar

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3548]
The "Run your code" offcanvas-button always seems to trigger a horizontal scrollbar, that disappears as soon as Papyros is brought on canvas. Try to avoid this horizontal scrollbar if not needed.

Example: https://naos.ugent.be/en/courses/56/series/591/activities/203584369/

![image](https://user-images.githubusercontent.com/5736113/164295783-286537ab-71ea-425e-858b-c4708b57ad8d.png)

![image](https://user-images.githubusercontent.com/5736113/164295832-2cc758f6-26b1-4e8d-aef6-c917d65a7996.png)

**Comment by bmesuere** [comment]
The PR is still open, so added there as a comment.
