### ISSUE TITLE
Run code keyboard shortcut

### ISSUE THREAD

**Issue by jay-tux** [dodona-edu/dodona#3564]
It would (in my opinion) be quite helpful if it were possible to run code with a simple shortcut from the keyboard. After developing locally (using an IDE, ...), we could then just copy-paste our code into the Dodona input field, then hit the shortcut (as we have our fingers already on the Ctrl-V keys).

I suggest the combination Ctrl-Enter (which is the same as Github uses for submission and I believe quite a few others).

**Comment by BTWS2** [comment]
There is an [extension available for VS Code](https://marketplace.visualstudio.com/items?itemName=thepieterdc.dodona-plugin-vscode) and a [plugin for JetBrains IDE's (e.g. PyCharm)](https://plugins.jetbrains.com/plugin/11166-dodona). This allows for a seamless experience with customizable shortcuts. Documentation is available here:
* https://docs.dodona.be/nl/guides/pycharm-plugin/
* https://docs.dodona.be/nl/guides/vs-code-extension/

Which IDE are you using?

I agree that a shortcut to submit would be a good addition though.

**Comment by jay-tux** [comment]
I usually use github's Atom editor.

**Comment by bmesuere** [comment]
At the moment we don't support shortcuts at all. If we see this as a general shortcut, #2817 is related.
If we see this as an ACE editor addition, #3332 is related. We must however be cautious that we don't trigger accident hand-ins or bind to an existing ACE shortcut.
