### ISSUE TITLE
Number test cases in feedback table and make it possible to link to them

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#357]
A student brought up the idea of numbering the test cases in the feedback table. I would think this could help in referencing specific testcases, but I don't see any specific reason for that. So I asked the student about how he could benefit from this.

_[Original issue](https://github.ugent.be/dodona/dodona/issues/357) by @pdawyndt on Tue Jan 10 2017 at 13:43._

**Comment by chvp** [comment]
We want test cases to be linkable.

**Comment by bmesuere** [comment]
This has been implemented in #5102
