### ISSUE TITLE
Fix io-wait and strscan dependency

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3574]
See #3412 and #3616

**Comment by chvp** [comment]
I think an upgrade to Ruby 3.1 should fix this. The bundler included with it should be aware that `io-wait` is bundled with ruby.

**Comment by bmesuere** [comment]
We now have the same problem with `strscan` as mentioned in #3643 

> You have already activated strscan 3.0.1, but your Gemfile requires strscan 3.0.3. Since strscan is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports strscan as a default gem.

**Comment by winniederidder** [comment]
More detailed issue concerning this: #3645
