### ISSUE TITLE
Store selected filters in local storage for exercise search within a course

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#3578]
> Given this refactor, how hard would it be to store the selected filters for the exercise search within a course (on the series edit page) in local storage and restore them if present? In this case, I think teachers mostly use the same settings to find exercises (certain programming language/repo/language) in a certain course so this would speed things up for them.

It would be very doable to to store selected filters in local storage. An easy solution would be to store the last used search url, and use it for the existing setbasurl method to initialize search params on a new page load without search params. 

I'll make an issue for this

_Originally posted by @jorg-vr in https://github.com/dodona-edu/dodona/issues/3498#issuecomment-1114590314_

**Comment by BramDevlaminck** [comment]
I suspect that as a teacher you don't search for the same exercise multiple times in different series. That's why I would not store the value of what was typed in the search field (only the other filters would be stored). But I might be wrong in assuming this, what do you think?

**Comment by jorg-vr** [comment]
I understand your reasoning, but I would still store all filters.
It will be easier to implement. It could also feel unintuitive to the user that some filters are stored and others are not.
They will also most likely always edit this filter field. So in that case it does not matter that much if it starts empty or not.
