### ISSUE TITLE
Improve discoverability of student list export

### ISSUE THREAD

**Issue by rien** [dodona-edu/dodona#3617]
Course admins are currently able to download a CSV with user information (dodona id, user email, user labels) by using the `Edit all labels` wizard:
![image](https://user-images.githubusercontent.com/3226995/167636614-ab8a16d7-bf94-416f-8577-b24b394b1594.png)

This CSV can be useful in some cases (e.g. programmatically adding users to an evaluation). So I think it may be a good idea to add a separate action to the context menu of the members table. For example:
![image](https://user-images.githubusercontent.com/3226995/167637281-effc9b4f-2263-4cc3-82a4-c11b37fac712.png)

This export can be identical to the one downloaded with the `Edit all labels`-wizard.

**Comment by jorg-vr** [comment]
When we have a specific export, this could contain some extra useful feastures, such as sorting or filtering.

One suggested usecase by a teacher:

> Die lijst is enkel de naam, nummer en email. Maar de voortgang zit daar niet bij. De lijst sorteert ook niet volgens de sortering die in Dodona op dat moment actief is…
> 
> Het was handig geweest om in Excel de naam, email en voortgang te hebben zodat we met een mailing list automatisch iedereen konden aanschrijven die minder dan x% oefeningen had gemaakt bijvoorbeeld.
