### ISSUE TITLE
Hide group progress in series export

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3635]
When the group progress is hidden in a series, students can still see the data when downloading an export of the series. Progress fields should also be hidden from the series export.

**Comment by bmesuere** [comment]
To be exact, the progress isn't part of the export but is shown as a first step in the wizard:
![image](https://user-images.githubusercontent.com/481872/168981056-45a02796-0175-471f-ad21-8d7fd661521b.png)

**Comment by pdawyndt** [comment]
Aha. I was informed by some students during yesterday's demo session that the series export was leaking the student progress when it is disabled for a series. This must indeed be the place where students could still see the progress.
