### ISSUE TITLE
Introduce a dark dark mode

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#3723]
The current dark mode theme for Dodona is too light for some users. Once we can offer themes using pure css, rename the current dark theme to "dim" and introduce a darker dark mode. Inspiration can be found in #3722.

**Comment by jorg-vr** [comment]
Will close this for now.
I have gotten used to the current theme, and we haven't had theme related feedback for a while now.

Also maintaining more theme's will also mean more things to check when developping
