### ISSUE TITLE
Institution dropdown on users page is (much) larger than page

### ISSUE THREAD

**Issue by chvp** [dodona-edu/dodona#3785]
![screenshot_2022-07-06-115009](https://user-images.githubusercontent.com/42220376/177523545-53ff9b04-65f7-4501-a78a-8216ff8552ed.png)

It's also not really useful if one can't search in it.

**Comment by BTWS2** [comment]
Idem for `Repository` in https://dodona.ugent.be/en/activities/, `Course` in https://dodona.ugent.be/en/questions/ and `Labels` and `Repository` in https://dodona.ugent.be/en/series/???/edit/.
