### ISSUE TITLE
Reduce size of buttons on change submission table

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3795]
The table that is used to change the selected submission of a student in an evaluation has buttons to the right of the table whose size could be reduce a bit.

![image](https://user-images.githubusercontent.com/5736113/177974083-82017dd4-5fac-4472-b29e-34449af33a3c.png)

**Comment by bmesuere** [comment]
The button size is fine, but they shouldn't all be (outlined) primary buttons. Because it is an important action, I would use a button with text instead. Maybe we can also indicate the currently selection solution?

**Comment by chvp** [comment]
The currently selected solution is indicated by the absence of the button. (But this can definitely be clearer.)
