### ISSUE TITLE
Use consistent font sizes

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3919]
Since the UI-update the font size used in the descriptions of learning activities does no long fit the font size for the menu labels. I would prefer to restore the old font size, to make all font sizes align better with each other.

**Comment by BTWS2** [comment]
The font size of the header of tables is small compared to the size of the text in the rows below.

```markdown
| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |
{: .table}
```

![image](https://user-images.githubusercontent.com/56451049/186878362-5a1c09ba-9bcb-412e-b669-8317d57660be.png)
