### ISSUE TITLE
Users overview course: switching tabs breaks in Chrome and Safari

### ISSUE THREAD

**Issue by BramDevlaminck** [dodona-edu/dodona#3928]
Switching between the *registered*, *pending* and *unregistered* users of a course breaks in Safari and Chrome (but works in Firefox).

Safari version:  15.6.1
Chrome version: 104.0.5112.101

Link to page: http://dodona.localhost:3000/en/courses/3/members/

**Comment by jorg-vr** [comment]
should be fixed by https://github.com/dodona-edu/dodona/pull/3972
