### ISSUE TITLE
Bash syntax highlighting ace editor

### ISSUE THREAD

**Issue by BramDevlaminck** [dodona-edu/dodona#3952]
Bash syntax highlighting is broken in the ace editor.

@jorg-vr noticed that it's broken for `bash` exercises, but it does work for `sh` exercises.

The error message in the console that happens is:
`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) [(mode-bash.js, line 0)](http://dodona.localhost:3000/assets/ace/mode-bash.js)`

**Comment by BramDevlaminck** [comment]
> This is probably not a bug. On `/programming_languages` admins can edit which mode should be loaded for which programming language. The default is the same as the programming language name, but this is not correct for bash. This is configured correctly in staging and production though.

This does indeed fix it. Maybe it's a good idea to set `sh` as default for bash exercises, since I don't really see any reason to use bash if there is no syntax highlighting there?

**Comment by chvp** [comment]
The programming language is not something we van really set as a default in Dodona. It is configured by the teachers creating exercises.
