### ISSUE TITLE
Series navigation should always bring selected series to top of viewport

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3962]
In [this course](https://dodona.ugent.be/en/courses/773/) with multiple series, this is the view I get after clicking the "exam (group 2)" series in the series nagivation in the right margin:

![image](https://user-images.githubusercontent.com/5736113/187957119-6dfc0ef5-2328-4690-a236-1990d6f2575c.png)

Two issues:

1. The series is not on top of the viewport, even though there's enough content below it to make this happen.
2. Another series is highlighted in the series navigation.

This no longer happens after series skeletons have been replaced with the full rendering of the series. A height difference between skeletons and full renderings of series might cause this issue (@chvp witnesses having observed this issue upon page loading).

**Comment by chvp** [comment]
I looked into this a while ago and did so again today. The first most obvious problem is that the height of the skeleton rows was not updated during the material 3 redesign. However, there is a bigger problem, namely that the size of a regular table is not consistent between browsers (and also depends on browser font settings, apparently). I think the only way to fix this consistently is to make the skeleton tables actual tables with a little bit of (static) text content. This text content can then be hidden to keep the current "redacted" look of the skeleton tables.

**Comment by niknetniko** [comment]
> I think the only way to fix this consistently is to make the skeleton tables actual tables with a little bit of (static) text content. This text content can then be hidden to keep the current "redacted" look of the skeleton tables.

If we are adding text to the tables, we should at least consider adding the actual exercise titles to the table (if possible with cheap queries of course). This would make all exercises findeable with the in-page search of the browser (I know we discussed this somewhere at one point, but I can't find an issue for it).
