### ISSUE TITLE
Properly render unicode ≮ characters ≯ and

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#3969]
Is there an easy fix to properly render unicode characters `&#8814;` (less than with strikethrough: ≮) and `&#8815;` (greater then with strikethrough: ≯). But even GitHub seems to have trouble to render these characters properly on my Windows machine. The first character, for example, should look like

![image](https://user-images.githubusercontent.com/5736113/188489950-2f69af2a-e45b-420a-8e93-3df8d1567f3a.png)

Example: [programming exercise description](https://dodona.ugent.be/nl/activities/1806941479/)

**Comment by chvp** [comment]
Do you have a screenshot? They seem to render fine on my devices (which means it's probably a local font issue).

**Comment by bmesuere** [comment]
This renders ok on Android as well

**Comment by pdawyndt** [comment]
Last line of last function description:

![image](https://user-images.githubusercontent.com/5736113/188502704-d900ab2b-a223-43e4-8ca2-eea20505f5bd.png)

In code example of description:

![image](https://user-images.githubusercontent.com/5736113/188502743-e3b21bf7-6b1c-4acc-bd5b-75b6aafdbbe0.png)

**Comment by chvp** [comment]
That does seem like a local font rendering issue with combining unicode characters. I don't think there's anything we can do about this; it's not like the browser is trying to render the wrong character. It is weird that it happens in Chrome and not in your HTML editor, but it's not impossible that they use a different font rendering stack.

**Comment by niknetniko** [comment]
Rather than the font rendering stack, it's probably the fonts on Windows, e.g. most of the monospace fonts (including the default used by Chrome, Consolas, which is what we use on Dodona, and the fallback fonts) don't support this character properly. If I set my monospace font to Noto Sans Mono, and override the CSS, it renders much nicer:

![image](https://user-images.githubusercontent.com/1756811/188506416-03d93e4c-15fe-495b-8a00-4ba31704710b.png)

Your editor probably has a better font set.

**Comment by jorg-vr** [comment]
Bootstrap lists the following monospace fonts by default:
`SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New"`

I tested all these (and roboto mono) and found only menlo supported the characters
![image](https://user-images.githubusercontent.com/21177904/188634417-e4af2c8f-7523-4532-814c-24c10c26127a.png)

Do we want to include a cdn for menlo to resolve this?

**Comment by bmesuere** [comment]
No, there will always be some character that is not part of some font.

**Comment by pdawyndt** [comment]
FYI: I've remove the two symbols from the description/tests of the assignment (to play on the safe side)
