### ISSUE TITLE
Selecting code also includes the annotations

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#3976]
It used to be possible to copy code without including the annotations. This is no longer possible:

![image](https://user-images.githubusercontent.com/1756811/189153412-5ed860d0-8931-4ced-80cd-9259c8484c3b.png)

Fixing this probably means that you can no longer copy annotations (which was also the case previously). 

However, especially during grading, I would argue not being able to copy a piece of code is more annoying than not being able to copy an annotation, as you can just click edit on the annotation and copy it that way. Copying code without the annotation means you need to scroll back to the top, hide the annotations, scroll back down, copy the code, scroll back up, re-enable annotations and scroll back down again.

**Comment by pdawyndt** [comment]
If you only want to select the code, you could hide all annotations before selecting and copying. This gives you the option to both select code with annotations and code without annotations, or only select text from the annotations.

**Comment by jorg-vr** [comment]
I am not a fan of this.

The suggested solutions makes copying annotations impossible. This would make annotations a lot less usable for students.

Potential use cases for copying annotation text:
- googling a certain error or warning
- copy pasting a code snipped provided in a manual answer by a teacher

A potential compromise would be only blocking copying annotations for teachers, or only in the evaluation view. But I am unsure if this is worth the effort, as there are already three methods of copying code without annotations:
- disabling annotations, as mentioned
- copying all code
- copying the code in multiple snippets (Working around the annotations)
