### ISSUE TITLE
LTI authentication error in Ufora

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4024]
When I want to make an LTI link to Dodona from Ufora, I get this authentication issue:

![image](https://user-images.githubusercontent.com/5736113/191286756-a51f528f-305b-4800-a8bd-09410facc767.png)

Veerle Fack pointed me on this issue. She already made links some two weeks ago (still worked back then), the links still worked some days ago, but she also noticed last Friday or last Monday that the links do not work anymore (she gets some LTI-related error). So probably also the same underlying LTI-authentication issue.

**Comment by thepieterdc** [comment]
Likely related to https://github.com/dodona-edu/dodona/pull/3476/ (`GET` methods are now `POST` and a `csrf` gem was added)
