### ISSUE TITLE
Authentication fails when using PyCharm plugin for Dodona

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4026]
Using an API token for authentication with the PyCharm plugin for Dodona fails with the following error message:

![image](https://user-images.githubusercontent.com/5736113/191736118-67fad496-c15c-43b5-b46d-07756f6900e6.png)

Reported by Pieter-Jan Kellens (PieterJan.Kellens@UGent.be).

**Comment by thepieterdc** [comment]
Addressed in https://github.com/thepieterdc/dodona-api-java/pull/84, will be released asap (JetBrains needs to review/publish this)
