### ISSUE TITLE
Add Previous submission button when grading exercises 

### ISSUE THREAD

**Issue by heremansgeert** [dodona-edu/dodona#4073]
When grading exercises there is a "next" button to switch to the next student submission. 
Could a "previous" button be added so it's easy to go back to the previous student?

![2022-10-07 10_43_37-Give feedback - Dodona](https://user-images.githubusercontent.com/28751060/194512105-cbf6e83b-6dd3-4432-bd79-ea708d4fb170.png)

**Comment by jorg-vr** [comment]
In this case you can use the browser functionality (the back button or typing backspace)
