### ISSUE TITLE
Duplicate entries in search dropdown on repository details page

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#4126]
On the repository details page, the search dropdown contains duplicate entries, it seems to be one entry for each exercise. This happens for all searchable dropdowns:

![image](https://user-images.githubusercontent.com/1756811/199773583-27f4e7c8-793b-41d4-bcd2-e37e1ea4ab45.png)

**Comment by rien** [comment]
This bug also occurs with labels on the repository details page: 
![image](https://user-images.githubusercontent.com/3226995/213452591-5fa20a4d-da0a-47bc-ae05-3e7178edd777.png)
