### ISSUE TITLE
Rework evaluation creation and submission selection

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#4174]
This feature request tries to achieve three goals:
1. Make evaluations more discoverable
2. Block students from submitting after they leave the room
3. Remove the hassle of emailing secret links to lists of students at the start time of the evaluation

Suggested changes:
1. An evaluation is a series setting
  - On the series setting, you should be able to toggle evaluation/grading on/off (Toggling of should trigger a warning)
  - This way the feature is already discoverable upon creating a series
  - Allows a combination with other settings (Such as only make a series visible between start time and end time)
  - This is reasonable as it is almost always known upon series creation that this series will be used for an evaluation
2. On this setting you should be able to select the students that can participate in this evaluation
  - There is a case to be made to link the list of participating students to the deadline instead of to the evaluation directly (This would allow for students with a special status to work on the same series)
4. A user in an evaluation will see a hand in button upon the series. When the user is finished he can press the button. This will hand in their final submission for each exercise. From that moment the hand in button will be disabled and their further submissions won't be accounted for.
5. A teacher can see a list of every user that has handed in. Easy to check if a student leaving the room has finalized his result. A teacher has the option to undo a hand in, or to hand in for a student.
6. When the deadline passes, the hand in function is automatically called, handing in  the last submission before the deadline for each remaining student.

**Comment by pdawyndt** [comment]
Some additional considerations:

1. If we have multiple evaluation series for different groups of students, we publish all series for all students after releasing the grades. Students still need to be linked to the series or we loose their evaluation result, but we should find a way that other students (that are not linked to the series/evaluation) can see the exercises afterwards and even submit solutions (e.g. in preparation of a later evaluation/exam).
2. Some secondary school teachers use the same Dodona course for different groups of students. They want to have different submission deadlines for different groups of students (but the same exercises in the series). Check if this use case is also covered (I guess it is, if the submission deadlines per student is also what the students get to see).
3. Could this also be used to differentiate among a class of students: clever students see a series with harder exercises, and students that have problems with programming get to see a series with easier exercises (so not linked to an evaluation with assessments to be done by hand)

**Comment by jorg-vr** [comment]
We have discussed this issue and decided for a slightly different approach. There is no need to make evaluations into a setting. And most other needs can be done without this change.

I split this issue in the following four issues:
- https://github.com/dodona-edu/dodona/issues/5408
- https://github.com/dodona-edu/dodona/issues/5409
- https://github.com/dodona-edu/dodona/issues/5410
- https://github.com/dodona-edu/dodona/issues/4940
