### ISSUE TITLE
Submission page margin is too wide on smaller screens

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#4191]
When my screen becomes less wide than 1400px, Dodona shrinks the page width. However, this results in relatively wasteful margins; the content becomes smaller than needed.

For comparison, the course page with the same browser width is attached as the second screenshot.

![image](https://user-images.githubusercontent.com/1756811/203837023-25fe3d84-e25e-4838-bf0b-0ce6c432fd4a.png)

![image](https://user-images.githubusercontent.com/1756811/203837146-536099f3-ea38-478a-ac1a-986eab026a16.png)

**Comment by jorg-vr** [comment]
Fixed in ce56b6929ff1615bfaa2c84c0d50427cae7c407e
