### ISSUE TITLE
Second divider in profile menu is too short

### ISSUE THREAD

**Issue by chvp** [dodona-edu/dodona#4219]
![screenshot_2022-12-06-085829](https://user-images.githubusercontent.com/42220376/205853950-a04b1788-1beb-4fa1-a628-b0fe236bc320.png)

This could be related to my browser having a non-standard font size configured, but we shouldn't have this issue in that case either IMO.

**Comment by bmesuere** [comment]
I was not able to reproduce this on my mac

**Comment by chvp** [comment]
I did some further testing. If I restore my font size back to the default this issue disappears. But the user's configured font size shouldn't impact this, IMO.
