### ISSUE TITLE
UID 1000 required to run dockers

### ISSUE THREAD

**Issue by ninewise** [dodona-edu/dodona#422]
After some heavy debugging, I discovered the user runner rails should have UID1000 in order for the docker judges to work. When the required directories are mounted, these are owned by the same UID inside as outside the docker. The runner user is currently the first one created (so UID 1000 by default).

Possible fix: set the UID of runner upon creation (say, 5000) and use `chown -R 5000:5000` on every file outside the docker we want the runner user to own.

This doesn't break anything at the moment of writing, but should we base our dockers on dockers created users, runner might not be UID 1000, or should we create another user on a server, the rails running user might not be UID 1000.

relevant links:
- https://stackoverflow.com/questions/26500270/understanding-user-file-ownership-in-docker-how-to-avoid-changing-permissions-o
- https://groups.google.com/forum/#!topic/docker-user/VFdFuZ4Ze_A

_[Original issue](https://github.ugent.be/dodona/dodona/issues/422) by @ninewise on Wed May 31 2017 at 18:16._

**Comment by rien** [comment]
I bumped onto the same bug today, a docker image already had a user with UID 1000 so the created runner had UID 1001.
