### ISSUE TITLE
Ask confirmation when making series visible from main course page

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4243]
Making a series visible using the link on the main course is only one click away from inadvertently publishing a series that should be kept hidden/closed. Asking confirmation before performing the action might prevent unwanted actions (but no guarantee).

![image](https://user-images.githubusercontent.com/5736113/207581456-15814731-7273-42de-a1e4-56d00e2099f1.png)

**Comment by heremansgeert** [comment]
Altough I agree that this may cause inadvertently publishing a hidden course I like it that I don't need to confirm. When students are taking a test I close or hide series with the exercises that were made in class.

After the test it's now easy to quickly reopen the hidden series.

**Comment by chvp** [comment]
This issue was created after a very specific instance where exercises were shown to students before an evaluation. To avoid that happening again, it's my opinion that requiring one extra click from people doing it on purpose doesn't seem that bad.
