### ISSUE TITLE
Add more metadata to history of exported submissions

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4244]
When exporting submissions, it would be interesting to mention the number of exported submissions when the export becomes available. This information might be a confirmation whether proper settings have been chosen (there are some decisions to make here).

**Comment by pdawyndt** [comment]
Now that I have a log of some exports (some I wanted to reuse), I think we could do with some more metadata per export. In order of priority:

- export date
- number of submissions
- exercise(s) / programming language(s)
- series
- number of students

![image](https://user-images.githubusercontent.com/5736113/207892306-8b85cd6e-3432-4c3a-b6b1-0ba9a66ac2a8.png)

**Comment by pdawyndt** [comment]
I also lack a link somewhere that leads me back to my history of submissions (I had to make another submission to get access to the list).

**Comment by jorg-vr** [comment]
> I also lack a link somewhere that leads me back to my history of submissions (I had to make another submission to get access to the list).
Do you mean "exports" instead of "submissions"? 
Otherwise I do not understand the meaning of this sentence in the context of this issue

**Comment by pdawyndt** [comment]
> > I also lack a link somewhere that leads me back to my history of submissions (I had to make another submission to get access to the list).
> 
> Do you mean "exports" instead of "submissions"? Otherwise I do not understand the meaning of this sentence in the context of this issue

yes, exports instead of submissions (I had "exported submissions" in mind)

**Comment by jorg-vr** [comment]
We will remove this page. Users should manage their exported data on their own device
