### ISSUE TITLE
Weird behaviour with header when favouriting a course

### ISSUE THREAD

**Issue by LouiseDck** [dodona-edu/dodona#4262]
When I favourite a course on the Dodona homepage, the behaviour is both inconsistent and weird.
This shows a section my homepage with no favourited courses.
![Screenshot from 2022-12-20 15-19-18](https://user-images.githubusercontent.com/36621934/208689033-11c2b0fb-6a7c-43f8-b9bc-ea1e02ca9c27.png)

When I favourite the 'Programmeren' course, the course is displayed twice:
![Screenshot from 2022-12-20 15-19-48](https://user-images.githubusercontent.com/36621934/208689341-11e8653f-e3ea-414f-ab2f-772e40325549.png)

If I then refresh, a new heading '2022-2023' appears:
![Screenshot from 2022-12-20 15-20-06](https://user-images.githubusercontent.com/36621934/208689486-b24d0eec-34df-40b8-80c0-76fb193c4d14.png)

If I then unfavourite the top course, the 2022-2023 header remains:
![Screenshot from 2022-12-20 15-20-15](https://user-images.githubusercontent.com/36621934/208689657-9f1b4dfe-e3ed-44b3-9a0b-827068be4f69.png)

After a refresh, the header dissapears and the course is once again shown under 'Cursussen'.
![Screenshot from 2022-12-20 15-20-25](https://user-images.githubusercontent.com/36621934/208689755-c10a0d2c-834e-4737-b582-ad67f14facb2.png)

**Comment by chvp** [comment]
Maybe we should just do away with favouriting althogether? It's not our most-used feature, and seems even less useful with the redesign.

**Comment by jorg-vr** [comment]
bug solved by #4245

**Comment by jorg-vr** [comment]
With #4245 favouriting will be the only way to get courses from previous years directly on the he home page. 

Would wait a bit before removing it?

But maybe it is better to close this issue and create a new one to discuss removal of the favouriting feature

**Comment by bmesuere** [comment]
> Maybe we should just do away with favouriting althogether? It's not our most-used feature, and seems even less useful with the redesign.

Disagree, this is used by teachers, especially in the second semester and will become more useful after #4245 is merged because then you will need multiple clicks to access often-used older courses.

**Comment by pdawyndt** [comment]
I confirm I use the favorites to bring the second semester courses to top.
