### ISSUE TITLE
Keep list of exports scoped in course/series

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4304]
When exporting data from a series, at the very end of the process you get to see a list of exports that is no longer scoped in the course. While this is useful for accessing the list of all exports (as should be available from the right margin menu - which is now not the case), access to the course/series is lost at this point (making it more work to return to the course/series because no breadcrumbs are no longer available). We might consider to provided a list of exports that is scoped to the course/series here, in addition to a full list of exports that is available from the right margin.

**Comment by jorg-vr** [comment]
we will remove this list page
