### ISSUE TITLE
Submission table overflow

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#4355]
In some cases, the submission table overflows: 

https://dodona.ugent.be/nl/submissions/13030544/

**Comment by pdawyndt** [comment]
Score item edit table may also overflow:

![image](https://user-images.githubusercontent.com/5736113/217467263-fbd246a5-fbd1-43f4-98dd-efd5ac4b349e.png)

https://dodona.ugent.be/nl/evaluations/755/edit/
