### ISSUE TITLE
Series removal fails

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#4356]
We received a few error emails indication that removing a series failed. This seems to be a series with an evaluation associated with it.

I'm not sure if we want to allow removing such series because the evaluation will be gone as well.

```
An ActiveRecord::InvalidForeignKey occurred in series#destroy:

  Mysql2::Error: Cannot delete or update a parent row: a foreign key constraint fails (`dodona`.`evaluations`, CONSTRAINT `fk_rails_99f485b8d0` FOREIGN KEY (`series_id`) REFERENCES `series` (`id`) ON DELETE RESTRICT ON UPDATE RESTRICT)
  app/controllers/series_controller.rb:140:in `destroy'
```

**Comment by jorg-vr** [comment]
A series with an evaluation already ask to confirm: 
![image](https://user-images.githubusercontent.com/21177904/215040199-b1e1571c-bad6-4539-baca-450f049095af.png)
Not sure if we should restrict it even more.

Everything works locally

Can reproduce with the exact same series as the error on naos https://naos.ugent.be/nl/series/6903/
Cannot reproduce with a different evaluation series on naos, I'll have t look deeper into it.

Possibly related to #4332

**Comment by jorg-vr** [comment]
Problem detected: Multiple evaluations where associated with the same series
![image](https://user-images.githubusercontent.com/21177904/215045854-e597608b-631c-473e-b89a-0ba163082561.png)
![image](https://user-images.githubusercontent.com/21177904/215045883-c3293e02-77d0-437e-96c6-eb05cbe7a45f.png)

All created within about a second.

I'll create a unique index.

Right now there are 20 evalutions with a non unique series_id on naos:
![image](https://user-images.githubusercontent.com/21177904/215047725-d2f807c7-44d1-408f-a534-113c390e752c.png)

We'll have to carefully remove the duplicates

**Comment by bmesuere** [comment]
Possibly related: #3978
