### ISSUE TITLE
Reprocessing repository twice might result into timing related git conflicts

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#4413]
Er waren twee `reprocess_activities` processen tegelijk bezig
Die beide enkele commits willen doen om config files aan te passen

Twee gelijktijdige commits kan ervoor zorgen dat er 1 commit 'nothing to commit' terug krijgt, wat blijkbaar sinds kort resulteert in een error code( zie <https://github.com/dodona-edu/dodona/pull/4406>)

[Slack Message](https://dodona-edu.slack.com/archives/CNP7MDSHL/p1676304059659929)

**Comment by bmesuere** [comment]
This was fixed in #5024

**Comment by jorg-vr** [comment]
Although #5024 should have fixed this. There are 12 new delayed job failures that look like they have the same cause...
