### ISSUE TITLE
"hold on" message appears again when editing a submission that was blocked earlier on

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4420]
When you get to see this message after submitting a solution while another submission of yours is still being processed (= valid use case for this message), it appears again after you submitted your solution when no more of your submissions are being processed and then edit the submission (= after clicking the edit button, not the submit button; both buttons are at the same location)

![image](https://user-images.githubusercontent.com/5736113/219937825-93ae9610-41d9-409a-903d-41fa3527603a.png)

**Comment by pdawyndt** [comment]
To reproduce:

1. open two exercises (can be the same exercise) in two browser tabs
2. submit solutions for both exercises simultaneously
3. second submission will have to wait (above message), so wait and then submit
4. edit second submission (=> this is where the message appears, but it shouldn't)

**Comment by chvp** [comment]
More accurately: the message doesn't dissappear after a successful submission. (None of our messages do.)
