### ISSUE TITLE
Filter "last submission per user" (regardless of correctness)

### ISSUE THREAD

**Issue by WLamotte** [dodona-edu/dodona#4503]
When listing submissions for a certain exercise, there is the option to filter "most recent correct submission per user", but it would be helpful to be able to specify "last submission per user"  (regardless of correctness). This way, it is easier to see which students still have problems with a certain exercise, so these can be investigated deeper.
"most recent submission of those students who don't have a correct submission yet" would also be useful, but that's not such a nice description for the UI...

**Comment by chvp** [comment]
This was implemented (very recently) in https://github.com/dodona-edu/dodona/pull/4487. It will be present in the next release of Dodona.
