### ISSUE TITLE
Make Python Tutor debugger more discoverable 

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#4509]
The Python Tutor feature is pretty well hidden. Many students do not know that this feature exists. Knowing what the code is doing and debugging it is essential. This would only show up on hover. The orientation of `Debugger` would be like this:
![image](https://user-images.githubusercontent.com/56451049/227898155-0ef93324-35f0-4163-9ff3-e673c44e1c30.png)

![debugger](https://user-images.githubusercontent.com/56451049/227897690-5d7b0552-3351-43df-8f9f-4d34c8a26fd1.png)

**Comment by bmesuere** [comment]
I agree this needs to become more discoverable, but I propose to wait till our new (client-side) debugging experience is ready.

**Comment by BTWS2** [comment]
Related to #5101 and #5102. Good progress have been made. I think this issue can be closed because of the "Debug" button.
![image](https://github.com/dodona-edu/dodona/assets/56451049/45c8f618-650d-4ad8-a6dd-b0315a59eb32)
