### ISSUE TITLE
Blue outline on focussed tab

### ISSUE THREAD

**Issue by bmesuere** [dodona-edu/dodona#4569]
Our tabs sometimes show a blue line at the right:
![image](https://user-images.githubusercontent.com/481872/232036814-3e9d09a5-c407-4ae4-88e2-518ad46df285.png)

The line disappears when you interact with the page and seems to be consistently present when we switch tabs programmatically.

I think this is caused by `:focus-visible` on the `a` inside the `li`. At least, I can reproduce it when I force that state using the dev tools. Setting the outline to none for that pseudo class will probably solve this issue.

**Comment by pdawyndt** [comment]
Could be something recent, because this is how I now see it in an evaluation when clicking the Next button, but I have evaluated student code last week in Dodona, and hadn't observed this

![image](https://user-images.githubusercontent.com/5736113/232072829-6938bc1d-029b-43bd-a578-f1b94fe4a67c.png)
