### ISSUE TITLE
Handling of partial output format is slow

### ISSUE THREAD

**Issue by niknetniko** [dodona-edu/dodona#4579]
From executing https://dodona.ugent.be/nl/courses/2263/activities/649388223/ on my local machine:

![image](https://user-images.githubusercontent.com/1756811/232540910-ad867062-5840-4ac1-aacc-1dc8339086db.png)

Looking at the code, some obvious things seem the validation of each JSON object individually. The same exercise without validating each command gives:

![image](https://user-images.githubusercontent.com/1756811/232542903-d5ea98fa-ff23-4c02-bd68-2fe7e62fd502.png)

**Comment by bmesuere** [comment]
Validation of non-partial output can also take a while. This is from the legacy python judge from an exercise with 150 tests:
![image](https://user-images.githubusercontent.com/481872/232800273-d6e604a4-62cf-47b7-bfda-45831695039c.png)

**Comment by niknetniko** [comment]
Using the [`json_schemer`](https://github.com/davishmcclurg/json_schemer) gem (for the partial format):

![image](https://user-images.githubusercontent.com/1756811/233000533-e737d3ed-5b06-45bb-867e-cfc488582f09.png)

Modifying the code to only validate the result at the end gives:
![image](https://user-images.githubusercontent.com/1756811/233002571-32864ba9-4612-4d84-8c3d-b48ca6e19c56.png)

I would thus propose using the second approach: validate once at the end to ensure we don't get invalid data in the database, and put a rescue block around the partial updates to catch and handle those errors.

**Comment by chvp** [comment]
If the checking of the full format fails, could we still check each individual partial command after? For judge development that seems quite important.

I'm also not sure how robust the result constructor is when the partial commands are invalid.

**Comment by chvp** [comment]
Keeping the current behaviour in development also seems fine.

**Comment by bmesuere** [comment]
Switching to the new validator has improved things, but it can still be an issue for certain exercises: https://dodona.ugent.be/nl/submissions/13892016/

I propose to still implement the second part of the original PR.

Do note that there are 1000+ tests in this exercise, so this is also a case of users "consuming" all performance gains by creating more/bigger tests.

**Comment by jorg-vr** [comment]
The fixing pull request was reverted. see https://github.com/dodona-edu/dodona/pull/4647

**Comment by bmesuere** [comment]
Version 2 of the json schemer gem (#4913) has additional performance improvements.
The legacy exercise with a validation time of 4.75 seconds in https://dodona.be/nl/submissions/13892016/ dropped to 0.58 seconds in https://dodona.be/nl/courses/2263/activities/1565418465/

There is thus no real need to implement additional strategies to speed this up. If others agree, this issue can be closed.
