### ISSUE TITLE
Add 'Python' Tutor support to JavaScript excercises

### ISSUE THREAD

**Issue by GoedendagMC** [dodona-edu/dodona#4597]
Would it be possible to add this? Python Tutor supports JavaScript (just like C, C++, and Java, as it says on its site), so I can see it being useful just like it is with Python exercises for JS exercises.

**Comment by pdawyndt** [comment]
This "support" is a bit stretched. Try using the Python Tutor for JavaScript code on [their website](https://pythontutor.com/) and you'll see that the graphical representation is much more cluttered than it is for Python. In addition it does not support the latest JavaScript syntax features, may become really slow at times, crashes more than often and so on. We have tested this option ourselves, and have decided that it wasn't stable enough for integration in Dodona.
