### ISSUE TITLE
Revert to original motivational messages

### ISSUE THREAD

**Issue by GoedendagMC** [dodona-edu/dodona#4598]
More info at [Revert to original motivational messages #4595](https://github.com/orgs/dodona-edu/discussions/4595)

**Comment by BWindey** [comment]
As a student, I am much happier seeing all the green accents, and no red (indicating failed tests). It gives a sense of accomplishment after a difficult exercise, while the message + emoji isn't.

![image](https://github.com/dodona-edu/dodona/assets/93756910/e6c171c8-49ed-41c5-b83f-ae99cccf3ee2)
