### ISSUE TITLE
Inconsistent naming of menu options for comments on source code

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4648]
Menu options: 2 end with "comment", 1 doesn't.

We should also replace "annotations" by "comments" next to the buttons that select which comments are displayed inline, to make everything consistent.

![image](https://github.com/dodona-edu/dodona/assets/5736113/96431559-c33d-49f1-98f6-912a811043e9)

![image](https://github.com/dodona-edu/dodona/assets/5736113/74a8dc03-8c1a-4012-9863-5829d7530388)

**Comment by bmesuere** [comment]
I agree with tweaking the text of the remove option, but not with renaming annotations since they are not the same thing. Annotations are machine annotations + comments
