### ISSUE TITLE
Find a better way to release "Add a comment" for a selection

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4649]
When a some snippet of a submission is selected, this fixes the "Add a comment" button in the left margin.

![image](https://github.com/dodona-edu/dodona/assets/5736113/983e0ad9-63e2-4b54-a05c-44d7e523a894)

From now on, when you hoover the code or the left margin, the button no longer follows the mouse pointer. Is this wanted behaviour? You can undo this behaviour by clicking either the code or the line numbers to undo the selection. Maybe it would also be more logical if you coud undo the selection by clicking the left margin next to the line numbers, which is not the case right now.

**Comment by bmesuere** [comment]
The button should be shown when code is selected, so when the selection is lifted (by clicking anywhere on the page), the button should return to its default state.

**Comment by pdawyndt** [comment]
@bmesuere This is indeed what happens, but when you scroll down the code, it's not always obvious that you have selected some code elsewhere.

**Comment by bmesuere** [comment]
Yes, but the problem is that text unselection isn't working as expected right now, so it will exacerbate the problem.
