### ISSUE TITLE
Panel for comment description should always appear below current position

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4651]
This is some behaviour that I never observed before when adding comments to submission. Started to appear upon yesterday's release (6.8.0). It's a bit hard to describe so I made this sketch of the expected and observed (unwanted) behaviour.

![image](https://github.com/dodona-edu/dodona/assets/5736113/ec945a27-da93-403d-ada0-1e66a79398d3)

The unwanted behaviour that doesn't occur all the time, but happens too often so it's worth to have a look into it. I never saw it occur when the viewport was at the top of the page, so you'll have to scroll a bit down to try and reproduce it.

The issue is that when you click the button to add a comment to a line, upon displaying the panel where the comment can be described the viewport shifts such that the selected line is no longer at its original position. This leads to confusing UX.

**Comment by bmesuere** [comment]
I tried adding a lot of comments on the result page of an exercise (partial line, full line, multi line) and didn't manage to reproduce this. There was never an upward layout shift.
