### ISSUE TITLE
Use vertical dots to open comments menu

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4652]
Across Dodona, we use vertical dots as an icon on buttons to open a menu

![image](https://github.com/dodona-edu/dodona/assets/5736113/7dc0e5a3-0ce0-408d-8927-134ab4a62bab)

but we use horizontal dots for the same purpose on the button to open the comments menu

![image](https://github.com/dodona-edu/dodona/assets/5736113/01acdf9b-acf6-47c6-826d-bffda752bfd7)

**Comment by jorg-vr** [comment]
I am not a big fan of this.
When there are multiple comments in a thread this can create an ugly vertical line
Vertical dots are also harder to associate with the correct annotation horizontaly

![image](https://github.com/dodona-edu/dodona/assets/21177904/3f7c2b43-3377-477c-9ce1-b8275a5c4ff0)
vs
![image](https://github.com/dodona-edu/dodona/assets/21177904/d84026dd-f2df-42d2-9fa4-6d8740b8c814)
