### ISSUE TITLE
Remove button after adding comment to selected code fragment

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4656]
When a comment has been added for a selected code fragment, the button to add a comment for the selection is still there. When moving the mouse over other lines, this causes multiple buttons to be visible as long as the selection is still active.

![image](https://github.com/dodona-edu/dodona/assets/5736113/3d734bcc-db7e-40cc-9fd8-8076c2962d40)

**Comment by bmesuere** [comment]
@jorg-vr can you check if you can still reproduce this? I think it has been fixed by the rewrite.
