### ISSUE TITLE
Automatic extension of multiline select in submitted code includes embedded annotations

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4748]
When selecting part of a submission, care has been taken not to select annotations that have been added to the code

![image](https://github.com/dodona-edu/dodona/assets/5736113/24a43901-14de-42d8-8d7d-72a170fcd164)

However, as soon as you release the selection, the procedure that automatically converts a multiline selection into a selection that snaps to entire lines does include the embedded annotations:

![image](https://github.com/dodona-edu/dodona/assets/5736113/57ab451d-c401-49b2-8a65-c1071aed18aa)

**Comment by jorg-vr** [comment]
No it is not fixed an not related. Issue is in the selectHelpers code. Depends on when I reallow selection of annotations by adding/removing a specific css class

**Comment by bmesuere** [comment]
Aha, I could now reproduce it. On my first try, I dragged the button instead of making a selection. Only using the button is fine is seems.
