### ISSUE TITLE
Add draft state for activities

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#4845]
When people are creating new exercises, this often doesn't work from the start. This is not a problem, but we can try to improve the experience. This issue suggests adding a "draft" flag to the exercise config. Based on this flag, we can adapt our behaviour:

- If a submission results in an internal error, this triggers an email and slack mention. We could disable this for draft exercises.
- We can limit the visibility of draft exercises, i.e. not show them to everyone. We do have to think about the use case where an exercise is drafted by multiple people at the same time.
- If possible, show more information when something goes wrong.
- On the top of the exercise description, show a clear warning that the exercise is in draft mode (and can thus not be used by others) and give the option to disable draft mode from Dodona itself. Maybe also add a more prominent edit link to such exercises.
- If a draft exercise is removed, actually remove it from the Dodona database
- When creating an exercise, it is not super easy to find said exercise to try it out. I think most people add it to a (dummy) course. We could add a list of "your draft exercises" to the home page.
- Add the draft flag to all our example exercises so we don't get tens of copies of the same exercise.

**Comment by bmesuere** [comment]
I updated the issue description and added a priority because we discussed this again recently.

Other suggestions for changed behaviour are of course welcome. We could, for example, automatically add the draft flag to all new exercises. This would increase the uptake of this feature.
