### ISSUE TITLE
Update browserlist

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#4904]
Update the supported browser. (Drop support for older browsers)

**Comment by bmesuere** [comment]
The current list is
```
>= 1% and last 2 major versions and not dead
Chrome >= 86
Firefox >= 81
Firefox ESR
iOS >= 14
Safari >= 14
```

According to our policy, we should update to 
```
>= 1% and last 2 major versions and not dead
Chrome >= 94
Firefox >= 92
Firefox ESR
iOS >= 15
Safari >= 15
```

The PR that updates this should run webpack/babel with the verbose/debug flag to compare the listed transpilations and polyfills included.
