### ISSUE TITLE
Client-side processing of annotations sometimes eats code

### ISSUE THREAD

**Issue by chvp** [dodona-edu/dodona#4920]
See e.g. https://dodona.be/nl/submissions/14682928/. On line 19 there is an `else`. This can also be seen in the raw HTML returned from the server. This `else` is however not visible in the code view and also can't be found with "Inspect element".

**Comment by chvp** [comment]
Did some more investigating. An error happens when an annotation's starting column is past the end of the line (which happens with a missing `:`, because it is expected after the `else`).

**Comment by pdawyndt** [comment]
Current fix seems to have an unwanted side effect. Missing semicolons that used to be indicates with an anchor after the last character on the line are now indicates by underlining the entire line. This conflicts with how it was intended by the linter and how the linting messages are displayed in most editors.

![image](https://github.com/dodona-edu/dodona/assets/5736113/4ebb27d6-3e4f-4af6-abc0-011aabc784f1)

Example: [submission](https://dodona.be/nl/feedbacks/762554124/)

**Comment by chvp** [comment]
This was done by design (see the first line of the description of the fixing PR). There's no concept of "past the end of the line" in our code view, so I opted to let it signify "there's a problem on this line".
