### ISSUE TITLE
Go back to stacked layout to edit code annotations

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4939]
I find the side-by-side layout for editing and searching annotations a step back compared to the previous stacked annotations. When editing annotations, I'm loosing oversight on the content I'm creating due to the reduced screensize, both for the annotation text itself and for the title when saving the annotation. The same holds for searching previous annotations. The previous approach to stack edit area and search area on top of each other gave much more overview of what you were doing.

**Comment by chvp** [comment]
I like the current layout better than the previous one, personally.
