### ISSUE TITLE
Never cache saved annotations

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4947]
While reviewing code, it regularly occurs that you also update the title/description of a saved annotation. Since the latter happens in another tab and code reviews caches saved annotations (e.g. to compare if an annotation is the same/different), you end up in a situation where the outdated information is used while reviewing. The latter could be avoided if saved annotations are never cached when its needed to edit an annotation, if this wouldn't yield performance issues.

**Comment by bmesuere** [comment]
The cache was really needed here, so we can't remove it for this use case.
