### ISSUE TITLE
Erroneous syntax highlighting

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#4948]
Example: [submission](https://dodona.be/nl/feedbacks/1142240360/)

**Comment by pdawyndt** [comment]
Here are some more examples:

- [submission](https://dodona.be/nl/feedbacks/797661559/)
- [submission](https://dodona.be/nl/feedbacks/1113049987/)

What they also seem to have in common: Python code with doctests (but other examples of Python code with doctest is properly highlighted).

**Comment by niknetniko** [comment]
This is a bug in Rouge, filed a bug upstream: https://github.com/rouge-ruby/rouge/issues/1991

**Comment by jorg-vr** [comment]
I'll close this as it's a rouge issue
