### ISSUE TITLE
Integrate pyodide tutor

### ISSUE THREAD

**Issue by jorg-vr** [dodona-edu/dodona#5014]
The current python tutor implementation only works for the old python judge and requires backend support.

In https://github.com/dodona-edu/pyodide-tutor we have tested the usage of the python tutor with pyodide. This works well.
We should integrate this project in Dodona to support python debugging for all python judges.

### Questions of note:
The developer of the python tutor ([Philip Guo](https://pg.ucsd.edu/)) has made his [repo](https://github.com/pgbovine/OnlinePythonTutor/) private. What does this mean for the future development of the project?

A note from the developper on this from [here](https://docs.google.com/document/d/1quk8gdvgzaYrZaOSiVzCia8tCXBFmuTk0awMw_-OTuE/edit):
> Q: Can I run a local copy of Python Tutor on my own server? I want better reliability guarantees. Or I want to customize a version to integrate with my own course’s software or materials.
>
>A: Sorry, the code is not openly available. We do not have the resources to maintain a robust open-source codebase with the intricate customizations required to run a modern scalable web service. Also, we do not have the time to help install, configure, and customize the service on your end. Simply giving you the source code is not enough to get it up-and-running, since so much of the code is tied to our own custom infrastructure. If you want to integrate Python Tutor into your own software or materials, the [iframe embed technique](https://docs.google.com/document/d/1quk8gdvgzaYrZaOSiVzCia8tCXBFmuTk0awMw_-OTuE/edit#bookmark=id.pbz67veiykx5) is by far the best way to do so.

Both this project and https://github.com/dodona-edu/pyodide-tutor contain a local copy of the python tutor javascript, but in a different version. I assume we'll want to use https://github.com/dodona-edu/pyodide-tutor/blob/main/src/pytutor.ts as it seems most recent?

As the developer repo is private, we'll either have to contact him to keep up to date with changes, or claim our own responsibility to keep the project up to date.

Eg: Right now there is still a heavy dependency on jquery and everything is in a single file, if we claim ownership, we should probably clean up this code to make it more maintainable?

For future reference: [notes on the state and vision of the python tutor by the developper](https://docs.google.com/document/d/13_Bc-l2FKMgwPx4dZb0sv7eMfYMHhRVgBRShha8kgbU/edit).

- [x] Allow other judges to use the tutor
- [x] Use pyodide to run backend https://github.com/dodona-edu/pyodide-trace-library
- [x] cleanup backend code https://github.com/dodona-edu/json-tracer
- [x] cleanup frontend code https://github.com/dodona-edu/pyodide-tutor/pull/8
- [x] integrate with papyros https://github.com/dodona-edu/papyros/pull/536
- [ ] implement extra desired features/fixes https://github.ugent.be/pythia/judge/issues/530

**Comment by niknetniko** [comment]
There are some forks/repo's with the code still available in original format: like https://github.com/pathrise-eng/pathrise-python-tutor, https://github.com/seamile/PyTutor (only v5) and https://github.com/blmlove409/OnlinePythonTutor (v1-4).

I think the Dodona one still uses v3, but I am unsure which one is used by pyodide.

**Comment by pdawyndt** [comment]
Here are some ideas/observations that were written down when we integrated the “Online Python Tutor” for the first time, back in 2014:

https://github.ugent.be/pythia/judge/issues/530
