### ISSUE TITLE
Footer scrolling issue

### ISSUE THREAD

**Issue by heremansgeert** [dodona-edu/dodona#5077]
When scrolling the footer doens't stay at the bottom of the screen (Chrome 118.0.5993.89 ). 

![2023-10-23 21_20_07-Give feedback - Dodona](https://github.com/dodona-edu/dodona/assets/28751060/2c8392fe-f65d-4b4e-92eb-b5a5e96168ee)

Removing the css property **position:absolute** from the footer solves the issue

**Comment by bmesuere** [comment]
Thanks for reporting. Does this happen on all pages? This might be an issue with an unclosed html tag on a certain page.

**Comment by BTWS2** [comment]
I checked and this happens on evaluation pages like https://dodona.be/nl/evaluations/???/feedbacks/???/. I can't find any other occurrences for now.

**Comment by heremansgeert** [comment]
Same for me. Only on evaluation pages.
