### ISSUE TITLE
Client-side Python Tutor does not load on iPad

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5081]
The client-side Python Tutor doesn’t seem to load on my iPad: spinner kept running for some minutes before I closed the tutor app. On the same device, Papyrus is ready to run Python code almost instantly though.

**Comment by jorg-vr** [comment]
The python tutor did not work in general, could you retry?

**Comment by pdawyndt** [comment]
Nope, still doesn't run in my iPad, while it now works on my laptop.

**Comment by pdawyndt** [comment]
Checked it once more, and now it works.
