### ISSUE TITLE
Allow 'Reader view' for students with reading difficulties

### ISSUE THREAD

**Issue by DieterPi** [dodona-edu/dodona#5103]
As many Dodona exercises are often very text intensive, some students with reading difficulties have a hard time even understanding the question. 

Most browsers have a 'Reading view,' which allows for an uncluttered view of text. In Edge (not my favorite browser, but yeah 🙈️) there is even an immersive reader option. Which allows for students with heavy dyslexia to read out the text and having line focus.

In Firefox I can force Reading view by appending `about:reader?url=` to the exercise url. In Edge appending `read:` to the url also forces the Reading view, but the only thing that appears is:

> In dit venster kan je Python-code uitvoeren zonder iets te moeten installeren. De code die je hier schrijft wordt niet automatisch ingediend in Dodona. Deze functie is nog in volle ontwikkeling. We horen graag je suggesties en problemen via [het contactformulier](https://dodona.be/nl/contact/).

I guess 'Reader view' would  remove the Dodona editor, but still, making it easier for students with reading difficulties to understand the question would a plus.

**Comment by bmesuere** [comment]
Unfortunately, reader mode isn't a standard (yet). As you found out, this means each browser has its own way to determine what to show in reader mode and there is no way to trigger it automatically. I'll leave this issue since it would be a useful feature, but for now there is not a lot we can do.
