### ISSUE TITLE
Client-side diff generation instead of not diffing longer outputs

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5133]
Currently, longer outputs are not diffed, while this feature is even more relevant for longer files. The reason is performance for server-side rendering of the feedback table. We might consider generating a diffed version of longer outputs client-side.

Example: https://dodona.be/nl/feedbacks/2020775260/

See difference between first four (shorter) test cases where the comparison of the directory structures is diffed, and the fifth (longer) test case where no diffing is done.

**Comment by chvp** [comment]
Runtime is not the only reason we don't diff longer outputs. The amount of HTML generated by a full diff of such long outputs noticeably slows down browsers.
