### ISSUE TITLE
Filter on activities in concept

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#5208]
If you have a lot of exercises it's difficult to find which activities are still a concept (and need some polishing before publishing). Maybe _Activity type: Concept_?

![image](https://github.com/dodona-edu/dodona/assets/56451049/e6497642-4801-44ce-b284-3426f34c445e)

**Comment by jorg-vr** [comment]
Thanks for the suggestion. I wasn't sure this would still be needed with concept activities already being listed listed on the home page.

But this can certainly be added as well if there is a usecase for it. 

It would probably become a separate filter, as the filters are currently related to database fields.

**Comment by BTWS2** [comment]
If you want to add the activities to a series before publishing, you are also presented with a long list. I would really appreciate the extra filter in this case too.

![image](https://github.com/dodona-edu/dodona/assets/56451049/2c22cf72-9bcb-4acc-ab9b-97b11b68b9be)

I noticed they are indeed listed on the homepage and link to https://dodona.be/en/activities/?draft=true&tab=mine Adding a filter would eliminate this extra step. Thank you taking this in consideration.

**Comment by bmesuere** [comment]
@BTWS2 What is your use case for adding draft activities to a series? (we thought about disabling that altogether)

**Comment by BTWS2** [comment]
Teachers are used that activities are linked to a series. I think teachers think in terms of courses and series, not individual exercises. Making exercises outside of a series doesn't happen very often. I have a series of "new exercises" that I can use for tests/exams, some of them are (almost) finished, some of them still need some work. If i'm making exercises I add the activity to a series because this needs to be done anyway. It's also easier to find this way (I didn't remember the concepts are on the homepage). If I know to which series it belongs I add it straight away to the right series, otherwise to the hidden "new exercises" series.

Maybe I need to adjust my workflow, but I want to know which exercises still need some work and which exercises I never used in a series (and thus are perfect for tests/exams). Creating exercises is spread over multiple sessions. Keeping an overview is important. I don't use the homepage very often. I have bookmarks in the browser for all Dodona courses of this academic year, for easy and fast access.

Having the draft filter is better for new teachers. If they are looking for a recently added exercise and don't remember the name exactly, they can only show the exercises in the concept phase.
