### ISSUE TITLE
Discrepancy between json and html view of /submissions

### ISSUE THREAD

**Issue by BWindey** [dodona-edu/dodona#5248]
When using the provided API, I stumbled upon an issue with submissions. Some activities are set to private within a course, but get a link pointing to it without a reference to it's associated course. Trying to view this private activity (as a student) returns error 403 (forbidden). 
This issue does not occur when viewing the submissions through the browser, as their links correctly refer to the course.

This occurs both on the "global" submissions for my user-account, and for the submissions for a certain activity. Note however that on the html-version of activity-submissions their is no link included to the activity. This is only on the "global" submissions.

The json-version also does not include the name of the corresponding activity, while the html-one does. It would be a nice improvement if the API included the name as well. It would also reduce the amount of "GET" requests needed to get the info for submissions.

In the html-version:
![image](https://github.com/dodona-edu/dodona/assets/93756910/685f984a-0be0-4e6b-a77f-47a1eb2bd072)

In the json-version:
```
... 
{
    "created_at":"2023-12-15T11:14:20.000+01:00",
    "status":"correct","summary":"Correct",
    "accepted":true,"id":16399349,
    "url":"https://dodona.be/nl/submissions/16399349.json",
    "user":"https://dodona.be/nl/courses/2876/members/37325.json",
    "has_annotations":false,

    "exercise":"https://dodona.be/nl/activities/273501711.json",

    "course":"https://dodona.be/nl/courses/2876.json"
}, ....
```

**Comment by bmesuere** [comment]
Hi, can you be a bit more specific about the problem (it's not always clear what "this" refers to). What exactly is missing/wrong and what is expected on which part of which page?

**Comment by BWindey** [comment]
Yes, I'll do my best.

For the same submission in https://dodona.be/submissions there is a difference in how it references its activity. 
For the html-version, the activity get's referenced as `/nl/courses/<course_id>/activities/<activity_id>/`
For the json-version,  the activity get's referenced as `https://dodona.be/nl/activities/<activity_id>.json`. This misses the  `/courses/<course_id/` part.


This means that the activity in the html-version references its course, while it does not in the json-version. That reference is often not needed, but some activities are "private" (so I heared from prof. Dawyndt) and are only viewable through that course. Trying to access the activity without the reference to the course in the link, will result in a "403 forbidden" error.

I would expect both the html- and json-version to have the same link/reference to the activity from which the submission was posted. 
I would also like to note that the short link/reference as is present in the current html-version, would be preferable over the full link in the json-version, as per demonstration in the [Dodona Docs: API-tokens](https://docs.dodona.be/nl/faq/api-tokens/#hoe-kan-ik-de-dodona-api-gebruiken).

**Comment by jorg-vr** [comment]
Thanks for reporting this.

I would not classify this as a bug. We are not aiming for feature parity between our html and our json api.
Both are implemented according to there own requirements, although logically they often contain the same information for the same subject.

It is a valid enhancement request for the current json api though and I just reclassified it as such.

It might take some time until we get to implementing it as the json API isn't very high on our priority list and we don't have time to support third party feature requests for it.

Feel free to open a pull request though.

**Comment by BWindey** [comment]
I can agree with that.

The thing keeping me from opening a pull request is that I don't understand how this code-base works.
I will try though, as it would be nice to be able to create pull requests instead of opening issues for you to work on.

Thank you for having looked at this issue.
