### ISSUE TITLE
Scroll to top when switching tabs in feedback table

### ISSUE THREAD

**Issue by chvp** [dodona-edu/dodona#5251]
Since the feedback table rework, it's possible to switch tabs while scrolled down. When one does this, they end up somewhere in the middle of the tab they switched to, which is confusing (at least for a second, to me).

**Comment by jorg-vr** [comment]
Might be relevant for #5160
@bmesuere will you continue to work on this feature or do you want me to take over?

**Comment by bmesuere** [comment]
@jorg-vr feel free to continue
