### ISSUE TITLE
API /notifications.json has field ..._url but shows ..._path

### ISSUE THREAD

**Issue by BWindey** [dodona-edu/dodona#5286]
When looking at the output of [dodona.be/notifications.json](https://dodona.be/notifications.json), I notice that the field "notifiable_url" does not contain a url, but a path (doesn't contain "https://dodona.be"). 
This is inconsistent with other json pages.

![image](https://github.com/dodona-edu/dodona/assets/93756910/82495385-5ada-4581-a73e-f998b0f482de)
The 2 files that create the result:
https://github.com/dodona-edu/dodona/blob/main/app/views/notifications/_notification.json.jbuilder#3
https://github.com/dodona-edu/dodona/blob/main/app/helpers/notifications_helper.rb#9

**Comment by BWindey** [comment]
Was this fixed, or deemed unwanted?

**Comment by bmesuere** [comment]
Fixing this might break things, so it's not worth the fix.
