### ISSUE TITLE
Directly launch Dolos web app (plagiarism detection) from Dodona

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5338]
As an initial implementation, we will implement the following flow:

```mermaid
sequenceDiagram
  Dodona Front ->> Dodona Back: POST create export
  Note over Dodona Back: collect submissions
  Dodona Back -->> Dodona Front: export URL
  Dodona Front ->> Dolos API: POST create report with export URL
  Note over Dolos API: download export & start analysis job
  Dolos API -->> Dodona Front: report URL 
  Dodona Front ->> Dolos Front: GET report URL
  Note over Dolos Front: save report URL in LocalStorage
  loop untill ready
    Dolos Front ->> Dolos API: GET report status
    Dolos API -->> Dolos Front: status
  end
  Note over Dolos Front: show report
```

On the Dodona side, this requires adding a way to initialize this flow and an extra step in the end of the export feature (#3457).

Exports for Dolos are ideally created with the following configuration:
- Only submissions for one exercise
- Last submission per student (before deadline?)
- Grouped by exercise, then by student (`exercise_name/student_name.ext`)
- Include `info.csv`
- Only students who submitted at least once

On the Dolos side, this requires adding:
- Importing ZIP-files from an URL instead of including the ZIP itself in the `POST` request
- A loading page when sent to the report URL directly if the analysis is not complete yet

The current flow does not store anything in Dodona (yet) and is a first iteration of the integration with Dolos, so we can evaluate this initial step before expanding on it.

**Comment by pdawyndt** [comment]
Should reactivate #3530.

**Comment by rien** [comment]
@jorg-vr @bmesuere I have updated the initial post according to our brainstorm. If anything is not clear I can elaborate if needed.
