### ISSUE TITLE
"Edit all labels" functionality broken?

### ISSUE THREAD

**Issue by WLamotte** [dodona-edu/dodona#5367]
When trying to use the "Edit all labels" functionality on the members page, changes to the CSV file are not reflected in the members list after uploading the CSV - not even after an explicit page refresh. I successfully used this functionality in the previous academic years, so the functionality seems to be broken since last year.

**Comment by jorg-vr** [comment]
Could you give me more specifics, eg: which course and maybe even the desired CSV (you can email it to dodona@ugent.be if you do not want it to be public)

I just ran some basic tests and for me everything still seems to work, so it is probably a more specific issue

**Comment by WLamotte** [comment]
I sent a mail with more details

**Comment by WLamotte** [comment]
The issue turned out to be a consequence of editing the CSV in Excel, which caused extra quotes to be generating when saving again as CSV. Editing in a text editor solved the issue.
