### ISSUE TITLE
Activity Desription is still in darkmode after switching from system mode

### ISSUE THREAD

**Issue by matt01y** [dodona-edu/dodona#5403]
- https://dodona.be/en/courses/3360/series/36061/activities/1819227414/#

- Set system theme to dark mode. In Dodona switch to system mode. close page. open new page. switch to light mode in Dodona.

![image](https://github.com/dodona-edu/dodona/assets/34476708/3437ed28-f801-49ec-9ad0-d7d8a4807c1a)

**Comment by jorg-vr** [comment]
Thanks for notifying and the clear steps to reproduce, I can reproduce this.

Notes for me:
only happening when switching from system theme to specific theme (Not when switching between specific themes)

**Comment by chvp** [comment]
I think this is a known firefox bug where iframes are cached too aggressively. We've encountered this before, and marked it as a wontfix then (although I can't find the issue/PR where we talked about this/decided this).

**Comment by jorg-vr** [comment]
I can reproduce this in both Firefox and chrome.

As said it works perfectly when switching between themes, so that would suggest the caching bug is successfully avoided in the current version.
