### ISSUE TITLE
Add submission id to evaluator view

### ISSUE THREAD

**Issue by berombau** [dodona-edu/dodona#5470]
When evaluating (e.g. at `https://dodona.be/nl/feedbacks/FEEDBACK_ID/`), I want to look at the student's solution in other lists, which use the SUBMISSION_ID. Having the SUBMISSION_ID somewhere so I can copy-paste it would save three clicks or save looking it up via the student's name. I also prefer the SUBMISSION_ID because it works in anonymous mode.

The user link and exercise link are already in the title bar. I would suggest something like this so there is both the solution link and SUBMISSION_ID in plain text which allows quick selection by double-clicking, but anywhere easily selectable if fine:
```
De gebruiker had N voorgaande pogingen voor deze oefening. Selecteer een andere ingediende oplossing. 
```
```
De gebruiker had N voorgaande pogingen voor [deze oplossing](https://dodona.be/nl/submissions/SUBMISSION_ID/) met id SUBMISSION_ID. Selecteer een andere ingediende oplossing. 
```

**Comment by jorg-vr** [comment]
I've introduced a link to the submission directly on the feedback page in #5513

I haven't directly included the submission id in the text. These id's are only needed by advanced users and might confuse our other users.

I hope adding this link already improves your workflow, by saving you some clicks

**Comment by berombau** [comment]
Yes, it does, thanks! Good enough for me, I'll close this issue then.
