### ISSUE TITLE
Row for bottom exercise to high in series card

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5492]
Height of the row for the last exercise is too high compared to the rows for the other exercises. Extra vertical spacing seems not necessary due to the horizontal line that already separates the last exercise from the new footer row of the card.

![image](https://github.com/dodona-edu/dodona/assets/5736113/f0b31206-edae-42e1-b21d-5616a5d15937)

**Comment by jorg-vr** [comment]
The padding here is related to the card and not to the table. It also makes it clearer that the bottom line is not part of the table
I would not change this
