### ISSUE TITLE
Improve soft-wrapping in "Code"-tab of solution 

### ISSUE THREAD

**Issue by BWindey** [dodona-edu/dodona#5507]
When the submitted code has lines that are too long to fit on a single visual line, it wraps the line to the next one.
This however doesn't account for the current "depth" of the code, which makes it visually less easy to look at:
![image](https://github.com/dodona-edu/dodona/assets/93756910/53df757d-0487-4a07-9e3a-b847be4c7b95)
The issue is even more noticeable on smaller screens (f.e. when having 2 apps next to each other on 1 screen):
![image](https://github.com/dodona-edu/dodona/assets/93756910/3b6d8fb8-cb49-4c51-8935-98c8a31a72d0)

This could be solved in 2 ways:
- disable the wrapping and let the user scroll sideways to see the whole code (like in the code-editor on an exercise-page)
- let the soft-wrapping start a new visual line with indentation that matches the actual line  
- (force the user to use shorter lines of code)

**Comment by jorg-vr** [comment]
Thanks for taking the time to create this issue.

But I am not convinced with the proposed solutions. 
Disabling wrapping might result in having to scroll down before being able to scroll right on longer submissions. This will also cause design issues with other components such as annotations.

soft-wrapping with indent just feels odd and I don't know any other editor that works like this. There are also no css-rules for this behavior, thus we would need to make a full custom implementation.

Anyway, writing very long lines is a code smell, so I wouldn't put to much effort in providing better support for them.
