### ISSUE TITLE
Make main content-container wider on smaller screens

### ISSUE THREAD

**Issue by BWindey** [dodona-edu/dodona#5508]
When making an exercise, I often have my browser and code-editor open side-by-side, each taking up half of the screen. 
The Dodona-page on small screen has 2 very big borders surrounding the main content-container (which holds exercise-description, code-editor, submission-result, ...). With some measuring in GIMP, the borders seem to take up 39,6% of the whole width of the browser-window. 
I think it would be nice if the side-bars would be smaller when the screen is so small. 

![image](https://github.com/dodona-edu/dodona/assets/93756910/c33cf41d-2dd8-49be-b881-8fe6641697ed)
(The exact pixel measurements from GIMP in this picture are:
- 960p for full picture
- 2 x 190p for the side-bars)

The advantage to making the side-bars smaller, would be that the user has to scroll less to view all the content.

**Comment by bmesuere** [comment]
A rework of the exercise page is planned which will probably get rid of the card and will be more flexible with margin usage.

Do note that long lines are bad for legibility. The optimal line length is between 40 and 75 (and ideally between 50 and 60) characters (which is the case in your screenshot).
