### ISSUE TITLE
Add a `Detect plagiarism` button in the evaluation view

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#5528]
Teachers don't go very often to pages similar to https://dodona.be/en/courses/???/series/???/activities/???/submissions/.

In my opinion it makes sense to add `Detect plagiarism` button(s) in the evaluation view on pages similar to https://dodona.be/en/evaluations/???/ to make it more discoverable. Plagiarism checks makes most sense if the submissions are graded and students can earn points.

This is a quick mock-up what it could look like:
![image](https://github.com/dodona-edu/dodona/assets/56451049/d89bba24-db97-4edc-97cf-958da69fff14)

Detecting for plagiarism for a series in it's entirety would be even better, but Dolos doesn't support that.

**Comment by jorg-vr** [comment]
This was indeed the next step I had in mind.
This issue is related to https://github.com/dodona-edu/dodona/issues/2503

Thanks for making the clear mockup

**Comment by pdawyndt** [comment]
The proposed solution only works for exercises that are part of an "evaluation". While this is a good place to launch plagiarism, we also need a discoverable place for exercises outside an "evaluation".
