### ISSUE TITLE
Make primary update action for series more prominent

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#5551]
As a teacher, the update action is the primary action for series. This action requires opening the menu, but should be at least as prominent as the "status overview" and "evaluate series" actions.

**Comment by jorg-vr** [comment]
We have discussed this and disagree on the suggested prominence of this functionality.

One of the reasons that the other options received more prominence is that new users did not discover them. While we haven't experienced issues with user not discovering how to edit their series.

I'll close this issue for now. We might pick it up again in the future should we get similar input from other users.
