### ISSUE TITLE
combine judge and docker

### ISSUE THREAD

**Issue by ninewise** [dodona-edu/dodona#574]
It might be nice to combine our currently separate judge and docker, using https://blog.alexellis.io/mutli-stage-docker-builds/. This way we could compile/build the judge first and run it more lightweight later. The downside is we'd have to rebuild the docker on each judge update (but is that really a downside?).

_[Original issue](https://github.ugent.be/dodona/dodona/issues/574) by @ninewise on Wed Jan 10 2018 at 10:38._

**Comment by bmesuere** [comment]
Now that updating the images can be automated (and building images can take a long time), I think we can close this issue.
