### ISSUE TITLE
Rating system for exercises like Kattis (elo based)

### ISSUE THREAD

**Issue by DieterPi** [dodona-edu/dodona#5742]
I think it would be very useful to enable a automatic rating style system for exercises. This would give students a better feeling for their *level*. In Kattis this system already exists. They use some kind of elo based system.

![kattis](https://github.com/user-attachments/assets/4926acb5-5fa9-44f5-8ba7-d0a0ed135926)

Also referencing this issue https://github.com/dodona-edu/dodona/issues/2203. However, as a teacher, it isn't easy to decide an objective difficulty rating. I think it would make more sense to use the data of exercise submissions as automatic grading.

**Comment by pdawyndt** [comment]
We once had a teacher-assigned difficulty level for exercises in a previous system (x / 5 stars), but we did not feel very comfortable with this. As you say, it is very hard to assign difficulty levels upfront. Also depends both on intrinsic properties of the exercise itself, and the progress students already made in acquiring programming skills. Can also be very frustrating for students. For these reasons, we discontinued supporting the assignment of difficulty levels when we launched Dodona.
