### ISSUE TITLE
Block access to all series except test/exam serie - Block individual student to serie

### ISSUE THREAD

**Issue by DominiekVandewalle** [dodona-edu/dodona#5875]

**Comment by jorg-vr** [comment]
Could you provide some more details about your usecase?
What is the problem you are trying to solve with this issue?

**Comment by jorg-vr** [comment]
Thanks for reconfirming these needs.

We have a lot of open issues to rework in the context of evaluations, see https://github.com/dodona-edu/dodona/issues/4364

'Teachers should be able to set a group of users for which a series is visible' is part of this issue https://github.com/dodona-edu/dodona/issues/5410 which is on our planned TODO list. It has gotten a bit of a delay as I have been working less lately and we want to rework some more code related to where you can and cannot submit.

'Make it possible to disable access to other courses/previous exercises during a test (ie. support for closed book testing)' is mentioned in  https://github.com/dodona-edu/dodona/issues/4364 as something to further explore in the future.

I'll close this issue as duplicate for now. But again thanks for reporting it, as reconfirming the need will help put it higher on our agenda.

**Comment by DominiekVandewalle** [comment]
No problem. I will add my issues anyway. Of course you can close my issues if it’s duplicate of a part of an other issue.

Op 18 okt 2024, om 09:53 heeft jorg-vr ***@***.***> het volgende geschreven:



Thanks for reconfirming these needs.

We have a lot of open issues to rework in the context of evaluations, see #4364<https://github.com/dodona-edu/dodona/issues/4364>

'Teachers should be able to set a group of users for which a series is visible' is part of this issue #5410<https://github.com/dodona-edu/dodona/issues/5410> which is on our planned TODO list. It has gotten a bit of a delay as I have been working less lately and we want to rework some more code related to where you can and cannot submit.

'Make it possible to disable access to other courses/previous exercises during a test (ie. support for closed book testing)' is mentioned in #4364<https://github.com/dodona-edu/dodona/issues/4364> as something to further explore in the future.

I'll close this issue as duplicate for now. But again thanks for reporting it, as reconfirming the need will help put it higher on our agenda.
