### ISSUE TITLE
Copy paste score items visibility

### ISSUE THREAD

**Issue by BTWS2** [dodona-edu/dodona#6019]
When copying and pasting pasting a row with score items, true or false is pasted in the visibility column, but that isn't allowed.

![Image](https://github.com/user-attachments/assets/0c82806f-ac6f-4456-b566-9251b711f733)

Steps to reproduce error:
1. Right click on row number
2. Copy
3. Right click on next row number
4. Paste

**Comment by jorg-vr** [comment]
Thanks for the reproduction guide. It seems using the copy and past buttons has a different effect as `ctrl+c` + `ctrl+v`
Will look into this
