### ISSUE TITLE
LTI support

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#737]
Add LTI support to Dodona.

Official documentation: https://documentation.brightspace.com/EN/integrations/ipsis/LTI%20Advantage/intro_to_LTI.htm?tocpath=Administrators%7CIntegrations%7CLTI%20Advantage%7C_____0

LTI Advantage is the next iteration of LTI, consisting of a new launch protocol and a package of optional extensions:

* Launch: The LTI 1.3 core launch flow follows a more modern security approach by adopting OpenId Connect (OIDC) specifications, OAuth2 and JSON Web Tokens.
* Assignment and Grades Services v2.0 (AGS): A replacement for the Basic Outcome service. AGS allows the LTI tool to create and manage grade objects and exchange scores and instructor comments. AGS includes additional capabilities two-way gradebook integration, where the LTI tool can request updates to grade values linked to the tools Assignments; allowing the Brightspace gradebook and tool to stay in sync.
* Names and Roles Provisioning Services v2.0: The service that allows the LTI tool to request a list of participants in a course offering in a safe and secure fashion. Typically used to repopulate the classlist in the tool.
* Deep Linking 2.0: A replacement for Content Item Message (CIM) service. Provides an intuitive way to add content from a publisher directly into Brightspace content, creating a seamless learner experience.

_[Original issue](https://github.ugent.be/dodona/dodona/issues/737) by @pdawyndt on Thu Oct 18 2018 at 14:57._

**Comment by pdawyndt** [comment]
DICT has managed to link Curios to Ufora. We could ask if this was done through 
LTI or directly through the Brightspace API.

**Comment by pdawyndt** [comment]
Ufora-interface for setting up LTI connections with external tools (provided by Patrick Cool from DICT)

![LTI_ufora](https://user-images.githubusercontent.com/5736113/69233084-89982d00-0b8c-11ea-81ce-14c94ba5c51e.png)

**Comment by pdawyndt** [comment]
Veerle Fack on integration of Dodon in external learning platforms (from MS Teams):

> Peter Dawyndt Ik denk dat er toch eens werk moet van gemaakt worden om Dodona ook in Ufora te integreren. Wat we misschien allemaal nog als minpuntjes aan Bongo VC gaan ontdekken, het feit dat het in Ufora geintegreerd is, maakt het wel erg handig: studenten zitten er automatisch in, ingeplande sessies komen ook automatische in agenda, e.d.

**Comment by rien** [comment]
Which integrations would be desired?
- Automatic registration in a Dodona Course?
- Series deadlines appearing in Ufora agenda?

**Comment by pdawyndt** [comment]
I'm thing out loud:

- creeate Dodona course from Brightspace course (taking over properties like title, academic year, users, ...)
- integration of deadlines in calendar
- automatically update scoresheet (#correct exercises per series, grades assigned in Dodona if that comes later)
- embed exercise in learning path

**Comment by pdawyndt** [comment]
Feedback from Frederik Gailly:

Based on my experience with on the one hand LTI integrations with Ufora and the other hand Dodona, some issues to take into account when developing LTI support for Ufora:
·         Ufora supports LTI 1.3  but the number of integrations that make use of it is limited. However D2L wants in the future to only allow 1.3 integrations
·         The LTI 1.3 standard looks promising but in practice we saw that tool providers again moved to API integration for some of the functionalities. For example group sync between PeerScholar and Ufora uses the API and not LTI
·         When developing LTI support you should further investigate how to set up this functionality because this will determine how you can integrate the tool in Ufora. Some examples:
o    For the peerscholar 2.0 integration the teacher has to go to the content tool > add existing activities > exernal learning tools > PeerScholar 2.0. It would be better to make it available immediately under the external tools  menu but this is impossible for PeerScholar. One of the problems with this approach is that instructor need to create a PeerScholar activity link in the content tool before the activity is actually configured in Peer Scholar.
o    For Bongo the instructor can follow a different approach. The instructor needs to first create a bongo session by going to extra tools > Bongo Virtual classroom. Next the instructor can add a link to the content tool using the add existing activities. A drawboack of this approach is that a lot of the instructor do not add a Bongo Session link to their content tool because students can access the Bongo session also using the extra tools menu.
The approach followed by PeerScholar is also supported by Bongo but seems like a Bongo session is then created from within Ufora whereas for the other approach you go to the Bongo Environment
·         How do I see the Dodona - Ufora LTI integration:
o    An Ufora course can be linked to a course on Dodona.  This means that every student from the classlist should be subscribed for the course on Dodona.
o    Assignments are created from within the Dodona platform and available to be added as link to the content tool in Ufora.
o    An instructor can add a Dodona exercise using the add existing activities menu and next select the assignment. If the assignment has a deadline this deadline is also added to the Ufora agenda.
o    A student completes a Dodona Assignment by clicking on the assignment. The student does not go to dodona but instead an interface is provided that is similar to the corresponding one in Dodona. In this interface he can both see the task description, submit his solution and see the feedback. However the student cannot go to the next exercise.
o    An instructor can also add a link to a Dodona serie in Ufora using the same approach. Maybe now the students has to go to the Dodona environment to solve the different  exercises of that serie.
o    Points for series can be transferred to Ufora by clicking on sync button in the course in Dodona

**Comment by bmesuere** [comment]
This is mostly implemented. I will create a separate issue for LTI grading.
