### ISSUE TITLE
Add visualisation of submission history

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#925]
Related to #924, I think it would benefit both students and teachers if we combined

1. the listing of all submissions of a user for a particular exercise (in a particular course)
2. the page showing the details of a single submission

by adding iteration (like pagination) to the page showing the details of a single submission, so that one could iterate back and forth between successive submissions. Here's a quick mockup of some sort of submission timeline slider that could be used to jump to a particular submission

![image](https://github.ugent.be/storage/user/6/files/e103af00-4315-11e9-888b-ff08f43aeb87)

This would give a visual impression on the time the user spent on the exercise. And I could image additional features like

1. a `play` button that shows the evolution of the coding process by automatically moving from the first submission to the last submission
2. a double pointer on the submission timeline to compare (diff) two submissions
![image](https://github.ugent.be/storage/user/6/files/ed880780-4315-11e9-83da-e80830221a48)
3. a kind of gradient between submissions that indicates how "big" the change is between submissions (e.g. to detect big jumps in strategy to solve an exercise), could be done by diffing successive submissions and scoring the degree of change based on insertions/deletions
![image](https://github.ugent.be/storage/user/6/files/fc6eba00-4315-11e9-9925-89c416fe4beb)
4. an extra marker to indicate the deadline of an evaluation
5. more detailed statistics about the sequence of submissions (e.g. estimation of total time spent, taking into account time in between first and last submission that was spent on programming)

_[Original issue](https://github.ugent.be/dodona/dodona/issues/925) by @pdawyndt on Sun Mar 10 2019 at 09:19._

**Comment by pdawyndt** [comment]
Here's a ][way of representing the history](https://twitter.com/amasad/status/1570488498205126656) as I somewhat had it in mind.

**Comment by jorg-vr** [comment]
easier navigation already implemented, no need for the fancier stuff
