### ISSUE TITLE
Submission event drops/violin plot

### ISSUE THREAD

**Issue by pdawyndt** [dodona-edu/dodona#984]
The [EventDrops visualization](https://github.com/marmelab/EventDrops) would allow to

- display submission events of a single user for a single exercise on a submission page (with current submission highlighted) as a way to swith over to other submission for the same user/exercise; could also be used to select a period for a given series of events
- display submission events of a single user over a selection of exercises (e.g. all exercises in a single course); could give an impression on the "time spent on an exercise"; next to submission events, we could also track when user does page load of exercise or when he inspects the feedback page
- display submission events of a single user before the deadlines of the series in a course
- display submission events of multiple users (e.g. for same exercise or series)

![](https://cloud.githubusercontent.com/assets/688373/18343222/c0a897b2-75b2-11e6-96df-e72e4b02335a.gif)

_[Original issue](https://github.ugent.be/dodona/dodona/issues/984) by @pdawyndt on Tue Mar 26 2019 at 13:06._

**Comment by chvp** [comment]
This is basically the violin plot from #2598.
